INTERFACE
SUBROUTINE HORIZ_FIELD(KX,KY,PHFIELD)

USE PARKIND1  ,ONLY : JPIM     ,JPRB

IMPLICIT NONE

INTEGER(KIND=JPIM),   INTENT(IN)    :: KX
INTEGER(KIND=JPIM),   INTENT(IN)    :: KY
REAL(KIND=JPRB),      INTENT(OUT)   :: PHFIELD(KX,KY)
REAL(KIND=JPRB),      PARAMETER     :: PPI=3.141592
END SUBROUTINE HORIZ_FIELD
END INTERFACE
