INTERFACE
subroutine dbfgsl (K_N,YD_D,K_M,K_NYS,K_JMIN,K_JMAX,YD_YBAR,YD_SBAR,P_RHO,P_SIZE)
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE CONTROL_VECTORS_MOD
INTEGER(KIND=JPIM),INTENT(IN) :: K_M
INTEGER(KIND=JPIM) :: K_N
TYPE(CONTROL_VECTOR),INTENT(INOUT) :: YD_D
INTEGER(KIND=JPIM),INTENT(IN) :: K_NYS
INTEGER(KIND=JPIM),INTENT(IN) :: K_JMIN
INTEGER(KIND=JPIM),INTENT(IN) :: K_JMAX
TYPE(CONTROL_VECTOR),INTENT(IN) :: YD_YBAR(K_M)
TYPE(CONTROL_VECTOR),INTENT(IN) :: YD_SBAR(K_M)
REAL(KIND=JPRB) ,INTENT(OUT) :: P_RHO(K_M)
REAL(KIND=JPRB) ,INTENT(IN) :: P_SIZE
end subroutine dbfgsl
END INTERFACE
