INTERFACE
subroutine dysave (K_N,YD_Y,YD_S,P_YS,K_M,K_NYS,K_JMIN,K_JMAX,YD_YBAR,YD_SBAR,K_SELECT,&
 & K_IITER,P_OL,K_JOL,P_EPS,P_SIZE,K_MODE,K_PLEV,K_IO) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE PARKIND2 ,ONLY : JPRH
USE CONTROL_VECTORS_MOD
INTEGER(KIND=JPIM),INTENT(IN) :: K_M
INTEGER(KIND=JPIM) :: K_N
TYPE(CONTROL_VECTOR),INTENT(IN) :: YD_Y
TYPE(CONTROL_VECTOR),INTENT(IN) :: YD_S
REAL(KIND=JPRH) ,INTENT(IN) :: P_YS
INTEGER(KIND=JPIM),INTENT(INOUT) :: K_NYS
INTEGER(KIND=JPIM),INTENT(INOUT) :: K_JMIN
INTEGER(KIND=JPIM),INTENT(INOUT) :: K_JMAX
TYPE(CONTROL_VECTOR),INTENT(INOUT) :: YD_YBAR(K_M)
TYPE(CONTROL_VECTOR),INTENT(INOUT) :: YD_SBAR(K_M)
INTEGER(KIND=JPIM),INTENT(IN) :: K_SELECT
INTEGER(KIND=JPIM),INTENT(IN) :: K_IITER
REAL(KIND=JPRB) ,INTENT(INOUT) :: P_OL(K_M)
INTEGER(KIND=JPIM),INTENT(INOUT) :: K_JOL(K_M)
REAL(KIND=JPRB) ,INTENT(IN) :: P_EPS
REAL(KIND=JPRB) ,INTENT(OUT) :: P_SIZE
INTEGER(KIND=JPIM),INTENT(OUT) :: K_MODE
INTEGER(KIND=JPIM),INTENT(IN) :: K_PLEV
INTEGER(KIND=JPIM),INTENT(IN) :: K_IO
end subroutine dysave
END INTERFACE
