INTERFACE
SUBROUTINE EIGSOL(KFLEVG,KNFLEVG,PA,PFR,PFI,K,PMO,KWO,PWO,KER)
USE PARKIND1 ,ONLY : JPIM ,JPRB

INTEGER(KIND=JPIM),INTENT(IN)   :: KFLEVG
INTEGER(KIND=JPIM),INTENT(IN)   :: KNFLEVG
REAL(KIND=JPRB),INTENT(IN)      :: PA(*)
REAL(KIND=JPRB),INTENT(OUT)     :: PFR(*)
REAL(KIND=JPRB),INTENT(OUT)     :: PFI(*)
INTEGER(KIND=JPIM),INTENT(IN)   :: K
REAL(KIND=JPRB),INTENT(OUT)     :: PMO(*)
INTEGER(KIND=JPIM),INTENT(OUT)  :: KWO(*)
REAL(KIND=JPRB),INTENT(OUT)     :: PWO(*)
INTEGER(KIND=JPIM),INTENT(OUT)  :: KER

END SUBROUTINE EIGSOL
END INTERFACE
