INTERFACE
 SUBROUTINE INTAVG(PVLEV,PVI,KNIDIM,KNI,KNPROF,KNO,PPO,PVO)
 USE PARKIND1 ,ONLY : JPIM ,JPRB
 INTEGER(KIND=JPIM), INTENT(in) :: KNIDIM, KNI, KNO, KNPROF
 REAL(KIND=JPRB), INTENT(in) :: PVLEV(KNIDIM,KNPROF)
 REAL(KIND=JPRB), INTENT(in) :: PPO(KNO),PVI(KNIDIM,KNPROF)
 REAL(KIND=JPRB), INTENT(inout) :: PVO(KNO,KNPROF)
 END SUBROUTINE INTAVG
END INTERFACE
