INTERFACE
SUBROUTINE MINV_CALLER(LDSCALE,KDIM,PIN,POU)
USE PARKIND1 , ONLY : JPIM     ,JPRB
LOGICAL           ,INTENT(IN)     :: LDSCALE
INTEGER(KIND=JPIM),INTENT(IN)     :: KDIM
REAL(KIND=JPRB),INTENT(IN)        :: PIN(KDIM,KDIM)
REAL(KIND=JPRB),INTENT(OUT)       :: POU(KDIM,KDIM)
END SUBROUTINE MINV_CALLER
END INTERFACE
