INTERFACE
subroutine n1cga (simul,K_N,YD_X,YD_B,YD_Q,YD_R,YD_V,YD_RM,P_EPSNEG,P_EPS2,K_ITER,K_IMP,K_IO,&
 & K_MODE,&
 & K_BFGSP,&
 & K_M0,K_NYS0,K_JMIN0,K_JMAX0,YD_YBAR0,YD_SBAR0,P_SIZE0,&
 & K_BFGSB,&
 & K_M1,K_NYS1,K_JMIN1,K_JMAX1,K_JOL,YD_YBAR1,YD_SBAR1,P_SIZE1,P_OL,&
 & K_SELECT,&
 & P_RHO,P_F0,&
 & YD_YS,YD_YRS) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE CONTROL_VECTORS_MOD

external simul
INTEGER(KIND=JPIM),INTENT(IN)      :: K_M0
INTEGER(KIND=JPIM),INTENT(INOUT)   :: K_M1
INTEGER(KIND=JPIM),INTENT(IN)      :: K_N
TYPE(CONTROL_VECTOR),INTENT(INOUT) :: YD_X
TYPE(CONTROL_VECTOR),INTENT(INOUT) :: YD_B
TYPE(CONTROL_VECTOR),INTENT(INOUT) :: YD_Q
TYPE(CONTROL_VECTOR),INTENT(INOUT) :: YD_R
TYPE(CONTROL_VECTOR),INTENT(INOUT) :: YD_V
TYPE(CONTROL_VECTOR),INTENT(INOUT) :: YD_RM
REAL(KIND=JPRB)   ,INTENT(IN)      :: P_EPSNEG
REAL(KIND=JPRB)   ,INTENT(INOUT)   :: P_EPS2
INTEGER(KIND=JPIM),INTENT(INOUT)   :: K_ITER
INTEGER(KIND=JPIM),INTENT(IN)      :: K_IMP
INTEGER(KIND=JPIM),INTENT(IN)      :: K_IO
INTEGER(KIND=JPIM),INTENT(OUT)     :: K_MODE
INTEGER(KIND=JPIM),INTENT(IN)      :: K_BFGSP
INTEGER(KIND=JPIM),INTENT(IN)      :: K_NYS0
INTEGER(KIND=JPIM),INTENT(IN)      :: K_JMIN0
INTEGER(KIND=JPIM),INTENT(IN)      :: K_JMAX0
TYPE(CONTROL_VECTOR),INTENT(IN)    :: YD_YBAR0(K_M0)
TYPE(CONTROL_VECTOR),INTENT(IN)    :: YD_SBAR0(K_M0)
REAL(KIND=JPRB)   ,INTENT(IN)      :: P_SIZE0
INTEGER(KIND=JPIM),INTENT(IN)      :: K_BFGSB
INTEGER(KIND=JPIM),INTENT(INOUT)   :: K_NYS1
INTEGER(KIND=JPIM),INTENT(INOUT)   :: K_JMIN1
INTEGER(KIND=JPIM),INTENT(INOUT)   :: K_JMAX1
INTEGER(KIND=JPIM),INTENT(INOUT)   :: K_JOL(K_M1)
TYPE(CONTROL_VECTOR),INTENT(INOUT) :: YD_YBAR1(K_M1)
TYPE(CONTROL_VECTOR),INTENT(INOUT) :: YD_SBAR1(K_M1)
REAL(KIND=JPRB)   ,INTENT(OUT)     :: P_SIZE1
REAL(KIND=JPRB)   ,INTENT(INOUT)   :: P_OL(K_M1)
INTEGER(KIND=JPIM),INTENT(IN)      :: K_SELECT
REAL(KIND=JPRB)   ,INTENT(OUT)     :: P_RHO(K_M0)
REAL(KIND=JPRB)   ,INTENT(IN)      :: P_F0
TYPE(CONTROL_VECTOR) ,INTENT(IN)   :: YD_YS
TYPE(CONTROL_VECTOR) ,INTENT(IN)   :: YD_YRS

end subroutine n1cga
END INTERFACE
