! (C) Copyright 2001- ECMWF.
! (C) Copyright 2001- Meteo-France.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.
!

SUBROUTINE DIR_TRANS_FIELD_API(YDFSPVOR,YDFSPDIV,YDFSPSCALAR, &
                             & YDFU, YDFV, YDFSCALAR, &
                             & KSPEC, KPROMA, KGPBLKS, KGPTOT, KFLEVG, KFLEVL, KRESOL, &
                             & LDACC)


!**** *DIR_TRANS_FIELD_API* - Field API interface to direct spectral transform

!     Purpose.
!     --------
!        Allow to call DIR_TRANS with a list of fields from field API

!**   Interface.
!     ----------
!     CALL DIR_TRANS_FIELD_API(...)

!     Explicit arguments :
!     --------------------
!      output
!       YDFSPVOR(:)    - List of spectral vector fields (vorticity)
!       YDFSPDIV(:)    - List of spectral vector fields (divergence)
!       YDFSPSCALAR(:) - List of spectral scalar fields
!      input
!       YDFU(:)        - List of grid-point vector fields (u)
!       YDFV(:)        - List of grid-point vector fields (v)
!       YDFSCALAR(:)   - List of grid-point scalar fields
!       KSPEC          - Number of spectral coefficients
!       KPROMA         - Blocking factor
!       KGPBLKS        - Number of blocks
!       KGPTOT         - Number of total grid points
!       KFLEVG         - Number of levels
!       KFLEVL         - Number of local levels
!       LDACC          - Field and temporary data on the device

USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK, JPHOOK
USE ECTRANS_FIELD_API_BASIC_TYPE_MOD, ONLY : FIELD_BASIC_PTR
USE PARKIND1  ,ONLY : JPIM,JPRB

IMPLICIT NONE

TYPE(FIELD_BASIC_PTR),INTENT(IN), OPTIONAL  :: YDFSPVOR(:), YDFSPDIV(:)
TYPE(FIELD_BASIC_PTR),INTENT(IN), OPTIONAL  :: YDFSPSCALAR(:)

TYPE(FIELD_BASIC_PTR),INTENT(IN), OPTIONAL  :: YDFU(:),YDFV(:)
TYPE(FIELD_BASIC_PTR),INTENT(IN), OPTIONAL  :: YDFSCALAR(:)

INTEGER(KIND=JPIM), INTENT(IN) ::KSPEC
INTEGER(KIND=JPIM), INTENT(IN) ::KPROMA
INTEGER(KIND=JPIM), INTENT(IN) ::KGPBLKS
INTEGER(KIND=JPIM), INTENT(IN) ::KGPTOT
INTEGER(KIND=JPIM), INTENT(IN) :: KFLEVG
INTEGER(KIND=JPIM), INTENT(IN) :: KFLEVL
INTEGER(KIND=JPIM), INTENT(IN), OPTIONAL :: KRESOL
LOGICAL, INTENT(IN), OPTIONAL  :: LDACC

REAL(KIND=JPHOOK)  :: ZHOOK_HANDLE

#include "dir_trans.h"
#include "abor1.intfb.h"

!     ------------------------------------------------------------------
IF (LHOOK) CALL DR_HOOK('DIR_TRANS_FIELD_API',0,ZHOOK_HANDLE)

!----------------------------------------------------------------------------------------------------------------------------
! NEW IMPLEMENTATION USING FIELD_VIEW
!----------------------------------------------------------------------------------------------------------------------------
IF (.TRUE.) THEN
BLOCK
USE ECTRANS_FIELD_API_MOD, ONLY: MAKE_FIELD_VIEW
USE ECTRANS_FIELD_VIEW_MOD, ONLY: FIELD_VIEW, FIELD_VIEW_GET_DATA_PTR, GET_NPROMA, GET_NFLD, GET_NSPEC2, GET_NBLK

TYPE(FIELD_VIEW), ALLOCATABLE  :: YLFVGU(:), YLFVGV(:)
TYPE(FIELD_VIEW), ALLOCATABLE  :: YLFVGSCALAR(:)

TYPE(FIELD_VIEW), ALLOCATABLE  :: YLFVSVOR(:), YLFVSDIV(:)
TYPE(FIELD_VIEW), ALLOCATABLE  :: YLFVSSCALAR(:)

INTEGER, PARAMETER :: FIELD_TYPE = 0

INTEGER :: IFIELD
INTEGER :: NFIELD_UV, NFIELD_SCALAR

! -------------------------------------------------------------------------------------------------------------
! Convert FIELD_API input fields into FIELD_VIEW, an intermediate representation of fields specific to ectrans

NFIELD_UV = 0
NFIELD_SCALAR = 0
IF (PRESENT(YDFU) .AND. PRESENT(YDFV)) THEN
  NFIELD_UV = SIZE(YDFU)
ENDIF
IF (PRESENT(YDFSCALAR)) THEN
  NFIELD_SCALAR = SIZE(YDFSCALAR)
ENDIF
ALLOCATE(YLFVGU(NFIELD_UV))
ALLOCATE(YLFVGV(NFIELD_UV))
ALLOCATE(YLFVGSCALAR(NFIELD_SCALAR))
ALLOCATE(YLFVSVOR(NFIELD_UV))
ALLOCATE(YLFVSDIV(NFIELD_UV))
ALLOCATE(YLFVSSCALAR(NFIELD_SCALAR))
DO IFIELD=1,NFIELD_UV
  CALL MAKE_FIELD_VIEW(YLFVGU(IFIELD),   YDFU(IFIELD),     FIELD_TYPE, LDACC=.FALSE., LDRDONLY=.TRUE.)
  CALL MAKE_FIELD_VIEW(YLFVGV(IFIELD),   YDFV(IFIELD),     FIELD_TYPE, LDACC=.FALSE., LDRDONLY=.TRUE.)
  CALL MAKE_FIELD_VIEW(YLFVSVOR(IFIELD), YDFSPVOR(IFIELD), FIELD_TYPE, LDACC=.FALSE., LDRDONLY=.TRUE.)
  CALL MAKE_FIELD_VIEW(YLFVSDIV(IFIELD), YDFSPDIV(IFIELD), FIELD_TYPE, LDACC=.FALSE., LDRDONLY=.TRUE.)
ENDDO
DO IFIELD=1,NFIELD_SCALAR
  CALL MAKE_FIELD_VIEW(YLFVGSCALAR(IFIELD), YDFSCALAR(IFIELD),   FIELD_TYPE, LDACC=.FALSE., LDRDONLY=.TRUE.)
  CALL MAKE_FIELD_VIEW(YLFVSSCALAR(IFIELD), YDFSPSCALAR(IFIELD), FIELD_TYPE, LDACC=.FALSE., LDRDONLY=.TRUE.)
ENDDO

! -------------------------------------------------------------------------------------------------------------
! Copy fields from FIELD_VIEW into temporary arrays for use with existing DIR_TRANS

BLOCK
REAL(KIND=JPRB),ALLOCATABLE :: ZPGP(:,:,:)
REAL(KIND=JPRB),ALLOCATABLE :: ZPSPSCALAR_X(:,:)
REAL(KIND=JPRB),ALLOCATABLE :: ZPSPVOR_X(:,:)
REAL(KIND=JPRB),ALLOCATABLE :: ZPSPDIV_X(:,:)

! Allocate temporary arrays
BLOCK
INTEGER :: NPROMA, NBLK, NFIELD_TOTAL_UV, NFIELD_TOTAL_SCALAR, NSPEC2

NPROMA              = GET_NPROMA(YLFVGU, YLFVGV, YLFVGSCALAR)
NBLK                = GET_NBLK(YLFVGU, YLFVGV, YLFVGSCALAR)
NFIELD_TOTAL_UV     = GET_NFLD(YLFVGU)
NFIELD_TOTAL_SCALAR = GET_NFLD(YLFVGSCALAR)
NSPEC2              = GET_NSPEC2(YLFVSVOR, YLFVSDIV, YLFVSSCALAR)

ALLOCATE( ZPGP(NPROMA, NFIELD_TOTAL_UV * 2 + NFIELD_TOTAL_SCALAR, NBLK) )
ALLOCATE( ZPSPVOR_X(NFIELD_TOTAL_UV, NSPEC2) )
ALLOCATE( ZPSPDIV_X(NFIELD_TOTAL_UV, NSPEC2) )
ALLOCATE( ZPSPSCALAR_X(NFIELD_TOTAL_SCALAR, NSPEC2) )
END BLOCK

! Copy data from FIELD_VIEW to temporary arrays
BLOCK
INTEGER :: JROF, JLEV, JFLD, IFIELD_TOTAL
REAL(KIND=JPRB), POINTER :: PTR_2D(:,:), PTR_3D(:,:,:), PTR_4D(:,:,:,:)

IFIELD_TOTAL = 0
DO IFIELD=1,NFIELD_UV
  IF (YLFVGU(IFIELD)%RANK == 2) THEN
    CALL FIELD_VIEW_GET_DATA_PTR(YLFVGU(IFIELD), PTR_2D)
    IFIELD_TOTAL = IFIELD_TOTAL + 1
    ZPGP(:,IFIELD_TOTAL,:) = PTR_2D(:,:)
  ELSE IF (YLFVGU(IFIELD)%RANK == 3) THEN
    CALL FIELD_VIEW_GET_DATA_PTR(YLFVGU(IFIELD), PTR_3D)
    DO JLEV=1,YLFVGU(IFIELD)%EXTENTS(2)
      IFIELD_TOTAL = IFIELD_TOTAL + 1
      ZPGP(:,IFIELD_TOTAL,:) = PTR_3D(:,JLEV,:)
    ENDDO
  ELSE IF (YLFVGU(IFIELD)%RANK == 4) THEN
    CALL FIELD_VIEW_GET_DATA_PTR(YLFVGU(IFIELD), PTR_4D)
    DO JLEV=1,YLFVGU(IFIELD)%EXTENTS(2)
      DO JFLD=1,YLFVGU(IFIELD)%EXTENTS(3)
        IFIELD_TOTAL = IFIELD_TOTAL + 1
        ZPGP(:,IFIELD_TOTAL,:) = PTR_4D(:,JLEV,JFLD,:)
      ENDDO
    ENDDO
  ENDIF
ENDDO
DO IFIELD=1,NFIELD_UV
  IF (YLFVGV(IFIELD)%RANK == 2) THEN
    CALL FIELD_VIEW_GET_DATA_PTR(YLFVGV(IFIELD), PTR_2D)
    IFIELD_TOTAL = IFIELD_TOTAL + 1
    ZPGP(:,IFIELD_TOTAL,:) = PTR_2D(:,:)
  ELSE IF (YLFVGV(IFIELD)%RANK == 3) THEN
    CALL FIELD_VIEW_GET_DATA_PTR(YLFVGV(IFIELD), PTR_3D)
    DO JLEV=1,YLFVGV(IFIELD)%EXTENTS(2)
      IFIELD_TOTAL = IFIELD_TOTAL + 1
      ZPGP(:,IFIELD_TOTAL,:) = PTR_3D(:,JLEV,:)
    ENDDO
  ELSE IF (YLFVGV(IFIELD)%RANK == 4) THEN
    CALL FIELD_VIEW_GET_DATA_PTR(YLFVGV(IFIELD), PTR_4D)
    DO JLEV=1,YLFVGV(IFIELD)%EXTENTS(2)
      DO JFLD=1,YLFVGV(IFIELD)%EXTENTS(3)
        IFIELD_TOTAL = IFIELD_TOTAL + 1
        ZPGP(:,IFIELD_TOTAL,:) = PTR_4D(:,JLEV,JFLD,:)
      ENDDO
    ENDDO
  ENDIF
ENDDO
DO IFIELD=1,NFIELD_SCALAR
  IF (YLFVGSCALAR(IFIELD)%RANK == 2) THEN
    CALL FIELD_VIEW_GET_DATA_PTR(YLFVGSCALAR(IFIELD), PTR_2D)
    IFIELD_TOTAL = IFIELD_TOTAL + 1
    ZPGP(:,IFIELD_TOTAL,:) = PTR_2D(:,:)
  ELSE IF (YLFVGSCALAR(IFIELD)%RANK == 3) THEN
    CALL FIELD_VIEW_GET_DATA_PTR(YLFVGSCALAR(IFIELD), PTR_3D)
    DO JLEV=1,YLFVGSCALAR(IFIELD)%EXTENTS(2)
      IFIELD_TOTAL = IFIELD_TOTAL + 1
      ZPGP(:,IFIELD_TOTAL,:) = PTR_3D(:,JLEV,:)
    ENDDO
  ELSE IF (YLFVGSCALAR(IFIELD)%RANK == 4) THEN
    CALL FIELD_VIEW_GET_DATA_PTR(YLFVGSCALAR(IFIELD), PTR_4D)
    DO JLEV=1,YLFVGSCALAR(IFIELD)%EXTENTS(2)
      DO JFLD=1,YLFVGSCALAR(IFIELD)%EXTENTS(3)
        IFIELD_TOTAL = IFIELD_TOTAL + 1
        ZPGP(:,IFIELD_TOTAL,:) = PTR_4D(:,JLEV,JFLD,:)
      ENDDO
    ENDDO
  ENDIF
ENDDO
END BLOCK

! DO TRANSFORM WITH TEMPORARY ARRAYS

!!! TODO: USE IVSET
IF (NFIELD_UV > 0 .AND. NFIELD_SCALAR > 0) THEN
  CALL DIR_TRANS( &
               & PGP=ZPGP, &
               & PSPVOR=ZPSPVOR_X, PSPDIV=ZPSPDIV_X, PSPSCALAR=ZPSPSCALAR_X, &
               & KPROMA = KPROMA, KRESOL = KRESOL)
ELSE IF (NFIELD_SCALAR > 0) THEN
  CALL DIR_TRANS(PGP = ZPGP, PSPSCALAR = ZPSPSCALAR_X, &
               & KPROMA = KPROMA, KRESOL = KRESOL)
ELSE IF (NFIELD_UV > 0) THEN
  CALL DIR_TRANS(PSPVOR = ZPSPVOR_X, PSPDIV = ZPSPDIV_X, PGP = ZPGP, &
               & KPROMA = KPROMA, KRESOL = KRESOL)
ENDIF

! UNPACK TEMPORARY SPECTRAL FIELDS BACK INTO FIELD_VIEW
BLOCK
INTEGER :: JROF, JLEV, JFLD, IFIELD_TOTAL
REAL(KIND=JPRB), POINTER :: PTR_1D(:), PTR_2D(:,:), PTR_3D(:,:,:), PTR_4D(:,:,:,:)
IFIELD_TOTAL = 0
DO IFIELD=1,NFIELD_UV
  IF (YLFVSVOR(IFIELD)%RANK == 1) THEN
    CALL FIELD_VIEW_GET_DATA_PTR(YLFVSVOR(IFIELD), PTR_1D)
    IFIELD_TOTAL = IFIELD_TOTAL + 1
    PTR_1D(:) = ZPSPVOR_X(IFIELD_TOTAL,:)
  ELSE IF (YLFVSVOR(IFIELD)%RANK == 2) THEN
    CALL FIELD_VIEW_GET_DATA_PTR(YLFVSVOR(IFIELD), PTR_2D)
    DO JFLD = 1, YLFVSVOR(IFIELD)%EXTENTS(1)
      IFIELD_TOTAL = IFIELD_TOTAL + 1
      PTR_2D(JFLD,:) = ZPSPVOR_X(IFIELD_TOTAL,:)
    ENDDO
  ELSE
    CALL ABOR1("[DIRTRANS_FIELD_API] Unsupported rank for vorticity field")
  ENDIF
ENDDO
IFIELD_TOTAL = 0
DO IFIELD=1,NFIELD_UV

  IF (YLFVSDIV(IFIELD)%RANK == 1) THEN
    CALL FIELD_VIEW_GET_DATA_PTR(YLFVSDIV(IFIELD), PTR_1D)
    IFIELD_TOTAL = IFIELD_TOTAL + 1
    PTR_1D(:) = ZPSPDIV_X(IFIELD_TOTAL,:)
  ELSE IF (YLFVSDIV(IFIELD)%RANK == 2) THEN
    CALL FIELD_VIEW_GET_DATA_PTR(YLFVSDIV(IFIELD), PTR_2D)
    DO JFLD = 1, YLFVSDIV(IFIELD)%EXTENTS(1)
      IFIELD_TOTAL = IFIELD_TOTAL + 1
      PTR_2D(JFLD,:) = ZPSPDIV_X(IFIELD_TOTAL,:)
    ENDDO
  ELSE
    CALL ABOR1("[DIRTRANS_FIELD_API] Unsupported rank for divergence field")
  ENDIF
ENDDO
IFIELD_TOTAL = 0
DO IFIELD=1,NFIELD_SCALAR
  IF (YLFVSSCALAR(IFIELD)%RANK == 1) THEN
    CALL FIELD_VIEW_GET_DATA_PTR(YLFVSSCALAR(IFIELD), PTR_1D)
    IFIELD_TOTAL = IFIELD_TOTAL + 1
    PTR_1D(:) = ZPSPSCALAR_X(IFIELD_TOTAL,:)
  ELSE IF (YLFVSSCALAR(IFIELD)%RANK == 2) THEN
    CALL FIELD_VIEW_GET_DATA_PTR(YLFVSSCALAR(IFIELD), PTR_2D)
    DO JFLD = 1, YLFVSSCALAR(IFIELD)%EXTENTS(1)
      IFIELD_TOTAL = IFIELD_TOTAL + 1
      PTR_2D(JFLD,:) = ZPSPSCALAR_X(IFIELD_TOTAL,:)
    ENDDO
  ELSE
    CALL ABOR1("[DIRTRANS_FIELD_API] Unsupported rank for scalar field")
  ENDIF
ENDDO

END BLOCK

END BLOCK

END BLOCK

RETURN

ENDIF

!----------------------------------------------------------------------------------------------------------------------------
! PREVIOUS IMPLEMENTATION
!----------------------------------------------------------------------------------------------------------------------------
BLOCK
USE ECTRANS_FIELD_API_MOD, ONLY: SPEC_VIEW, GRID_VIEW, LS_COUNT, LG_COUNT, LS, LG

  ! Local variables

! List of FIELD_VIEW: intermediate representation of fields to facilitate copy to temporary arrays
TYPE(SPEC_VIEW), ALLOCATABLE  :: YLSPVVOR(:), YLSPVDIV(:)
TYPE(SPEC_VIEW), ALLOCATABLE  :: YLSPVSCALAR(:)

TYPE(GRID_VIEW), ALLOCATABLE  :: YLGVU(:),YLGVV(:)
TYPE(GRID_VIEW), ALLOCATABLE  :: YLGVSCALAR(:)

! Temporary arrays for dir_trans
REAL(KIND=JPRB),POINTER :: ZPSPVOR(:,:),ZPSPDIV(:,:)  ! spectral vector fields (out)
REAL(KIND=JPRB),POINTER :: ZPSPSC2(:,:)               ! spectral scalar fields(out)
REAL(KIND=JPRB),POINTER :: ZPGPUV(:,:,:,:)            ! grid vector fields (in)
REAL(KIND=JPRB),POINTER :: ZPGP2(:,:,:)               ! grid scalar fields (in)

REAL(KIND=JPRB), POINTER :: ZZ1_1(:)
REAL(KIND=JPRB), POINTER :: ZZ1_2(:)
REAL(KIND=JPRB), POINTER :: ZZ2_1(:,:)
REAL(KIND=JPRB), POINTER :: ZZ2_2(:,:)
REAL(KIND=JPRB):: S
INTEGER(KIND=JPIM) :: C

! b-set for dir-trans
INTEGER(KIND=JPIM),ALLOCATABLE :: IVSETUV(:)
INTEGER(KIND=JPIM),ALLOCATABLE :: IVSETSC2(:)

INTEGER(KIND=JPIM) :: IFLDXG
INTEGER(KIND=JPIM) :: IFLDXL
INTEGER(KIND=JPIM) :: IFLDSPVOR
INTEGER(KIND=JPIM) :: IFLDSPSC
INTEGER(KIND=JPIM) :: IUVG
INTEGER(KIND=JPIM) :: IUVDIM
INTEGER(KIND=JPIM) :: ID
INTEGER(KIND=JPIM) :: IOFFSET
INTEGER(KIND=JPIM) :: JLEV      ! Level counter
INTEGER(KIND=JPIM) :: JFLD      ! Field counter

IFLDXG  = 0
IFLDXL = 0
IFLDSPVOR= 0
IFLDSPSC= 0
IUVG = 0
JFLD  = 0
IUVDIM = 0
ID = 0
IOFFSET = 0
JLEV = 0
JFLD = 0

! 1. Vector fields transformation to spectral space

! Preliminary checks
IF (PRESENT(YDFU) .NEQV. PRESENT(YDFV)) CALL ABOR1("[DIR_TRANS_FIELD_API] YDFU and YDFV must be provided together")

! Do we have vector fields?
IF (PRESENT(YDFU)) THEN

  IF ((SIZE(YDFU)/= SIZE(YDFV)).OR.(SIZE(YDFU)/= SIZE(YDFSPDIV)).OR.(SIZE(YDFU)/= SIZE(YDFSPVOR))) THEN
     CALL ABOR1("[DIR_TRANS_FIELD_API] The vector arrays have inconsitent sizes: YDFU, YDFV, YDFSPDIV, YDFSPVOR")
  ENDIF

  ! Convert list of spectral vector fields into a list of 2d FIELD_VIEW
  IFLDSPVOR = LS_COUNT(YDFSPVOR)

  ALLOCATE(YLSPVVOR(IFLDSPVOR))
  ALLOCATE(YLSPVDIV(IFLDSPVOR))

  ! Convert list of grid-point vector fields into a list of 2d FIELD_VIEW
  ALLOCATE(YLGVU(LG_COUNT(YDFU)))
  ALLOCATE(YLGVV(LG_COUNT(YDFV)))
  IF ((SIZE (YLGVU) /= SIZE (YLGVV)) .OR. (SIZE (YLSPVVOR) /= SIZE (YLSPVDIV))) THEN
     CALL ABOR1("[DIR_TRANS_FIELD_API] inconsistent number of field_view for vectors")
  ENDIF
   IF (((SIZE (YLGVU) / SIZE (YDFU)) /= KFLEVG) .OR. ((SIZE (YLSPVVOR) / SIZE (YDFSPVOR)) /= KFLEVL)) THEN
     CALL ABOR1("[DIR_TRANS_FIELD_API] inconsistent kflevg or kflevl")
  ENDIF

  IUVG = SIZE(YDFU)
  
  IUVDIM = 2

  ! allocate temporary vector field arrays in spectral space
  ALLOCATE(ZPSPVOR(IFLDSPVOR,KSPEC))
  ALLOCATE(ZPSPDIV(IFLDSPVOR,KSPEC))

  ! allocate temporary vector field array in grid space
  ALLOCATE(ZPGPUV(KPROMA,KFLEVG, IUVG * IUVDIM,KGPBLKS))

  ! allocate 'b-set' for vector fields
  ALLOCATE(IVSETUV(KFLEVG))


! temporary copies on gpu
   if ( LDACC ) THEN
    !$ACC ENTER DATA CREATE(ZPSPVOR,ZPSPDIV,ZPGPUV)
  ENDIF

  IOFFSET = 0
  C = LG(YDFU, YLGVU, LDACC, .TRUE.)
  C = LG(YDFV, YLGVV, LDACC, .TRUE.)

  ! Copy list of 2d views of grid point vector fields into temporary arrays
    DO JFLD=1,IUVG
      DO JLEV=1,KFLEVG
        ID = JLEV + (JFLD -1) * KFLEVG
        ZZ2_1=>YLGVU(ID)%P
        ZZ2_2=>YLGVV(ID)%P
        IF (LDACC) THEN
          !$ACC KERNELS PRESENT(ZPGPUV,ZZ2_1,ZZ2_2)
          ZPGPUV(:,JLEV,JFLD+IOFFSET*IUVG,:) = ZZ2_1(:,:)
          ZPGPUV(:,JLEV,JFLD+(IOFFSET+1)*IUVG,:) = ZZ2_2(:,:)
          !$ACC END KERNELS
        ELSE
          ZPGPUV(:,JLEV,JFLD+IOFFSET*IUVG,:) = ZZ2_1(:,:)
          ZPGPUV(:,JLEV,JFLD+(IOFFSET+1)*IUVG,:) = ZZ2_2(:,:)
        ENDIF
      ENDDO
    ENDDO

    IF (LDACC) THEN
    !$ACC UPDATE SELF(ZPGPUV)
    ENDIF

  DO JFLD=1,IUVG
    DO JLEV=1,KFLEVG
      ID = JLEV + (JFLD -1) * KFLEVG
      IF (JFLD .EQ. 1) IVSETUV(JLEV) = YLGVU(ID)%IVSET
      IF (IVSETUV(JLEV) .NE. YLGVV(ID)%IVSET)  CALL ABOR1("[DIR_TRANS_FIELD_API] ivsetuv inconsistent with ylgvv%ivset")
    ENDDO
  ENDDO
ELSE
  ! No vector field provided
  IUVG = 0  
  ZPGPUV=>NULL()
  ZPSPVOR=>NULL()
  ZPSPDIV=>NULL()
ENDIF

! 2. scalar fields transformation

! Preliminary checks
IF (PRESENT(YDFSPSCALAR) .NEQV. PRESENT(YDFSCALAR))  CALL ABOR1("[DIR_TRANS_FIELD_API] YDFSPSCALAR and YDFSCALAR &
                                                               & must be provided together")

! Do we have scalar fields?
IF (PRESENT(YDFSPSCALAR)) THEN
  IF ((SIZE(YDFSPSCALAR)/= SIZE(YDFSCALAR)))  CALL ABOR1("[DIR_TRANS_FIELD_API] Inconsistent size &
                                                         & for YDFSPSCALAR and YDFSCALAR")

  ! Convert list of spectral scalar fields of any dimension into a list of 2d fields
  ALLOCATE(YLGVSCALAR(LG_COUNT(YDFSCALAR)))

  IFLDXG = SIZE(YLGVSCALAR)

  IFLDSPSC = LS_COUNT(YDFSPSCALAR)
  ALLOCATE(YLSPVSCALAR(IFLDSPSC))


  ! count the number of fields present on the processor
  C = LS(YDFSPSCALAR, YLSPVSCALAR, LDACC,.TRUE.)
  IFLDXL = 0
  DO JFLD = 1, IFLDSPSC
    IF (ASSOCIATED(YLSPVSCALAR(JFLD)%P)) IFLDXL = IFLDXL + 1
  END DO
   ! Allocate temporary scalar field array in spectral space
  ALLOCATE(ZPSPSC2(IFLDXL,KSPEC))

  ! Allocate temporary scalar field array in grid space
  ALLOCATE(ZPGP2(KPROMA,IFLDXG,KGPBLKS))

  ! allocate 'b-set' for scalar fields
  ALLOCATE(IVSETSC2(IFLDXG))

  ! temporary copies on gpu
   if ( LDACC ) THEN
    !$ACC ENTER DATA CREATE(ZPSPSC2,ZPGP2)
  ENDIF

  ! Copy list of scalar fields into temporary arrays (2d copy thanks to field_view)
  C = LG(YDFSCALAR, YLGVSCALAR, LDACC,.TRUE.)
  DO JFLD=1, IFLDXG
    ZZ2_1=>YLGVSCALAR(JFLD)%P
    IF (LDACC) THEN
      !$ACC KERNELS PRESENT(ZPGP2,ZZ2_1)
      ZPGP2(:,JFLD,:) = ZZ2_1(:,:)
      !$ACC END KERNELS
    ELSE
      ZPGP2(:,JFLD,:) = ZZ2_1(:,:)
    ENDIF
  ENDDO
    IF (LDACC) THEN
    !$ACC UPDATE SELF(ZPGP2)
    ENDIF
  
  DO JFLD=1, IFLDXG
    IVSETSC2(JFLD) = YLGVSCALAR(JFLD)%IVSET
  ENDDO

ELSE
  !No scalar field provided  
  IFLDXG = 0
  ZPGP2=>NULL()
  ZPSPSC2=>NULL()
ENDIF

! 3. CALL DIR_TRANS using the regular interface and the temporary arrays

! We have to perform separated calls for nvfortran
IF (ASSOCIATED(ZPGP2) .AND. ASSOCIATED(ZPGPUV)) THEN
	CALL DIR_TRANS(PSPVOR = ZPSPVOR,PSPDIV = ZPSPDIV,PGPUV = ZPGPUV,KVSETUV = IVSETUV, &
	             & PSPSC2 = ZPSPSC2,PGP2 = ZPGP2, KVSETSC2 = IVSETSC2, &
	             & KPROMA = KPROMA, KRESOL = KRESOL)
ELSE IF (ASSOCIATED(ZPGP2)) THEN
	CALL DIR_TRANS(PSPSC2 = ZPSPSC2,PGP2 = ZPGP2, KVSETSC2 = IVSETSC2, &
	             & KPROMA = KPROMA, KRESOL = KRESOL)
ELSE IF (ASSOCIATED(ZPGPUV)) THEN
	CALL DIR_TRANS(PSPVOR = ZPSPVOR,PSPDIV = ZPSPDIV,PGPUV = ZPGPUV,KVSETUV = IVSETUV, &
	             & KPROMA = KPROMA, KRESOL = KRESOL)
ENDIF
! 4. Copy back temporary array data into spectral fields

! copy spectral vorticity and divergence
IF (IUVG>0) THEN
    IF (LDACC) THEN
    !$ACC UPDATE SELF(ZPSPVOR,ZPSPDIV)
    ENDIF

    C = LS(YDFSPVOR, YLSPVVOR, LDACC, .FALSE.)
    C = LS(YDFSPDIV, YLSPVDIV, LDACC, .FALSE.)

    DO JFLD=1,IFLDSPVOR
      IF (ASSOCIATED(YLSPVVOR(JFLD)%P)) THEN
        ZZ1_1=>YLSPVVOR(JFLD)%P
        ZZ1_2=>YLSPVDIV(JFLD)%P
        IF (LDACC) THEN
         !$ACC KERNELS PRESENT(ZPSPVOR,ZPSPDIV,ZZ1_1,ZZ1_2)
          ZZ1_1(:) = ZPSPVOR(JFLD,:)
          ZZ1_2(:) = ZPSPDIV(JFLD,:)
          !$ACC END KERNELS
        ELSE
          ZZ1_1(:) = ZPSPVOR(JFLD,:)
          ZZ1_2(:) = ZPSPDIV(JFLD,:)
        ENDIF
      ENDIF
      ENDDO

ENDIF

! copy spectral scalar fields
 IF (IFLDSPSC > 0) THEN

   IF (LDACC) THEN
   !$ACC UPDATE SELF(ZPSPSC2)
   ENDIF

   C = LS(YDFSPSCALAR, YLSPVSCALAR, LDACC,.FALSE.)
   ID = 1
   DO JFLD = 1, IFLDSPSC
      IF (ASSOCIATED(YLSPVSCALAR(JFLD)%P)) THEN
        ZZ1_1=>YLSPVSCALAR(JFLD)%P
        IF (LDACC) THEN
          !$ACC KERNELS PRESENT(ZPSPSC2,ZZ1_1)
           ZZ1_1(:) = ZPSPSC2(ID,:)
          !$ACC END KERNELS
        ELSE
           ZZ1_1(:) = ZPSPSC2(ID,:)
        ENDIF
        ID = ID + 1
      ENDIF
   ENDDO
  ENDIF
! 5. Final cleanup

! delete temporary arrays

 IF ( LDACC ) THEN
  IF (ASSOCIATED(ZPSPVOR))  THEN
      !$ACC EXIT DATA DELETE(ZPSPVOR)
  ENDIF
  IF (ASSOCIATED(ZPSPDIV)) THEN
   !$ACC EXIT DATA DELETE(ZPSPDIV)
  ENDIF
  IF (ASSOCIATED(ZPGPUV)) THEN
     !$ACC EXIT DATA DELETE(ZPGPUV)
  ENDIF
  IF (ASSOCIATED(ZPSPSC2)) THEN
   !$ACC EXIT DATA DELETE(ZPSPSC2)
  ENDIF
  IF (ASSOCIATED(ZPGP2)) THEN
     !$ACC EXIT DATA DELETE(ZPGP2)
  ENDIF
ENDIF

IF (ASSOCIATED(ZPSPVOR)) DEALLOCATE(ZPSPVOR)
IF (ASSOCIATED(ZPSPDIV)) DEALLOCATE(ZPSPDIV)
IF (ASSOCIATED(ZPSPSC2)) DEALLOCATE(ZPSPSC2)
IF (ASSOCIATED(ZPGPUV))  DEALLOCATE(ZPGPUV)
IF (ASSOCIATED(ZPGP2))   DEALLOCATE(ZPGP2)
IF (ALLOCATED(IVSETUV))  DEALLOCATE(IVSETUV)
IF (ALLOCATED(IVSETSC2)) DEALLOCATE(IVSETSC2)

! delete FIELD_VIEWS
IF (ALLOCATED(YLSPVVOR))    DEALLOCATE(YLSPVVOR)
IF (ALLOCATED(YLSPVDIV))    DEALLOCATE(YLSPVDIV)
IF (ALLOCATED(YLSPVSCALAR)) DEALLOCATE(YLSPVSCALAR)
IF (ALLOCATED(YLGVU))       DEALLOCATE(YLGVU)
IF (ALLOCATED(YLGVV))       DEALLOCATE(YLGVV)
IF (ALLOCATED(YLGVSCALAR))  DEALLOCATE(YLGVSCALAR)

END BLOCK

IF (LHOOK) CALL DR_HOOK('DIR_TRANS_FIELD_API',1,ZHOOK_HANDLE)
!     ------------------------------------------------------------------

END SUBROUTINE DIR_TRANS_FIELD_API
