! (C) Copyright 2026- ECMWF.
! (C) Copyright 2026- Meteo-France.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.
!

SUBROUTINE DIR_TRANS_FIELD_VIEW(    &
    & YDGPSCALAR, YDGPU, YDGPV,     &
    & YDSPSCALAR, YDSPVOR, YDSPDIV, &
    & KRESOL)

USE EC_PARKIND, ONLY : JPIM
USE ECTRANS_FIELD_VIEW_MOD, ONLY: FIELD_VIEW

IMPLICIT NONE

! Arguments
TYPE(FIELD_VIEW),   INTENT(IN)           :: YDGPSCALAR(:), YDGPU(:), YDGPV(:)
TYPE(FIELD_VIEW),   INTENT(INOUT)        :: YDSPSCALAR(:), YDSPVOR(:), YDSPDIV(:)
INTEGER(KIND=JPIM), INTENT(IN), OPTIONAL :: KRESOL

! Interfaces
#include "dir_trans.h"
#include "abor1.intfb.h"

! Implementation
BLOCK
USE YOMHOOK  ,ONLY : LHOOK, DR_HOOK, JPHOOK
USE PARKIND1 ,ONLY : JPRB
USE ECTRANS_FIELD_VIEW_MOD, ONLY: FIELD_VIEW_GET_DATA_PTR, GET_NPROMA, GET_NFLD, GET_NSPEC2, GET_NBLK

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

INTEGER(KIND=JPIM) :: NFIELD_UV, NFIELD_SCALAR
INTEGER(KIND=JPIM) :: NPROMA, NBLK, NFIELD_TOTAL_UV, NFIELD_TOTAL_SCALAR, NSPEC2

REAL(KIND=JPRB),ALLOCATABLE :: ZPGP(:,:,:)
REAL(KIND=JPRB),ALLOCATABLE :: ZPSPSCALAR(:,:)
REAL(KIND=JPRB),ALLOCATABLE :: ZPSPVOR(:,:)
REAL(KIND=JPRB),ALLOCATABLE :: ZPSPDIV(:,:)

IF (LHOOK) CALL DR_HOOK('DIR_TRANS_FIELD_VIEW',0,ZHOOK_HANDLE)

NFIELD_UV           = SIZE(YDGPU)
NFIELD_SCALAR       = SIZE(YDGPSCALAR) 
NPROMA              = GET_NPROMA(YDGPU, YDGPV, YDGPSCALAR)
NBLK                = GET_NBLK(YDGPU, YDGPV, YDGPSCALAR)
NFIELD_TOTAL_UV     = GET_NFLD(YDGPU)
NFIELD_TOTAL_SCALAR = GET_NFLD(YDGPSCALAR)
NSPEC2              = GET_NSPEC2(YDSPVOR, YDSPDIV, YDSPSCALAR)

! Allocate temporary arrays
ALLOCATE( ZPGP(NPROMA, NFIELD_TOTAL_UV * 2 + NFIELD_TOTAL_SCALAR, NBLK) )
ALLOCATE( ZPSPVOR(NFIELD_TOTAL_UV, NSPEC2) )
ALLOCATE( ZPSPDIV(NFIELD_TOTAL_UV, NSPEC2) )
ALLOCATE( ZPSPSCALAR(NFIELD_TOTAL_SCALAR, NSPEC2) )

! Copy data from FIELD_VIEW to temporary arrays
BLOCK
INTEGER :: JROF, JLEV, JFLD, IFIELD_TOTAL, IFIELD
REAL(KIND=JPRB), POINTER :: PTR_2D(:,:), PTR_3D(:,:,:), PTR_4D(:,:,:,:)

IFIELD_TOTAL = 0
DO IFIELD=1,NFIELD_UV
  IF (YDGPU(IFIELD)%RANK == 2) THEN
    CALL FIELD_VIEW_GET_DATA_PTR(YDGPU(IFIELD), PTR_2D)
    IFIELD_TOTAL = IFIELD_TOTAL + 1
    ZPGP(:,IFIELD_TOTAL,:) = PTR_2D(:,:)
  ELSE IF (YDGPU(IFIELD)%RANK == 3) THEN
    CALL FIELD_VIEW_GET_DATA_PTR(YDGPU(IFIELD), PTR_3D)
    DO JLEV=1,YDGPU(IFIELD)%EXTENTS(2)
      IFIELD_TOTAL = IFIELD_TOTAL + 1
      ZPGP(:,IFIELD_TOTAL,:) = PTR_3D(:,JLEV,:)
    ENDDO
  ELSE IF (YDGPU(IFIELD)%RANK == 4) THEN
    CALL FIELD_VIEW_GET_DATA_PTR(YDGPU(IFIELD), PTR_4D)
    DO JLEV=1,YDGPU(IFIELD)%EXTENTS(2)
      DO JFLD=1,YDGPU(IFIELD)%EXTENTS(3)
        IFIELD_TOTAL = IFIELD_TOTAL + 1
        ZPGP(:,IFIELD_TOTAL,:) = PTR_4D(:,JLEV,JFLD,:)
      ENDDO
    ENDDO
  ENDIF
ENDDO
DO IFIELD=1,NFIELD_UV
  IF (YDGPV(IFIELD)%RANK == 2) THEN
    CALL FIELD_VIEW_GET_DATA_PTR(YDGPV(IFIELD), PTR_2D)
    IFIELD_TOTAL = IFIELD_TOTAL + 1
    ZPGP(:,IFIELD_TOTAL,:) = PTR_2D(:,:)
  ELSE IF (YDGPV(IFIELD)%RANK == 3) THEN
    CALL FIELD_VIEW_GET_DATA_PTR(YDGPV(IFIELD), PTR_3D)
    DO JLEV=1,YDGPV(IFIELD)%EXTENTS(2)
      IFIELD_TOTAL = IFIELD_TOTAL + 1
      ZPGP(:,IFIELD_TOTAL,:) = PTR_3D(:,JLEV,:)
    ENDDO
  ELSE IF (YDGPV(IFIELD)%RANK == 4) THEN
    CALL FIELD_VIEW_GET_DATA_PTR(YDGPV(IFIELD), PTR_4D)
    DO JLEV=1,YDGPV(IFIELD)%EXTENTS(2)
      DO JFLD=1,YDGPV(IFIELD)%EXTENTS(3)
        IFIELD_TOTAL = IFIELD_TOTAL + 1
        ZPGP(:,IFIELD_TOTAL,:) = PTR_4D(:,JLEV,JFLD,:)
      ENDDO
    ENDDO
  ENDIF
ENDDO
DO IFIELD=1,NFIELD_SCALAR
  IF (YDGPSCALAR(IFIELD)%RANK == 2) THEN
    CALL FIELD_VIEW_GET_DATA_PTR(YDGPSCALAR(IFIELD), PTR_2D)
    IFIELD_TOTAL = IFIELD_TOTAL + 1
    ZPGP(:,IFIELD_TOTAL,:) = PTR_2D(:,:)
  ELSE IF (YDGPSCALAR(IFIELD)%RANK == 3) THEN
    CALL FIELD_VIEW_GET_DATA_PTR(YDGPSCALAR(IFIELD), PTR_3D)
    DO JLEV=1,YDGPSCALAR(IFIELD)%EXTENTS(2)
      IFIELD_TOTAL = IFIELD_TOTAL + 1
      ZPGP(:,IFIELD_TOTAL,:) = PTR_3D(:,JLEV,:)
    ENDDO
  ELSE IF (YDGPSCALAR(IFIELD)%RANK == 4) THEN
    CALL FIELD_VIEW_GET_DATA_PTR(YDGPSCALAR(IFIELD), PTR_4D)
    DO JLEV=1,YDGPSCALAR(IFIELD)%EXTENTS(2)
      DO JFLD=1,YDGPSCALAR(IFIELD)%EXTENTS(3)
        IFIELD_TOTAL = IFIELD_TOTAL + 1
        ZPGP(:,IFIELD_TOTAL,:) = PTR_4D(:,JLEV,JFLD,:)
      ENDDO
    ENDDO
  ENDIF
ENDDO
END BLOCK

! DO TRANSFORM WITH TEMPORARY ARRAYS

!!! TODO: USE IVSET
IF (NFIELD_UV > 0 .AND. NFIELD_SCALAR > 0) THEN
  CALL DIR_TRANS( &
               & PGP=ZPGP, &
               & PSPVOR=ZPSPVOR, PSPDIV=ZPSPDIV, PSPSCALAR=ZPSPSCALAR, &
               & KPROMA = NPROMA, KRESOL = KRESOL)
ELSE IF (NFIELD_SCALAR > 0) THEN
  CALL DIR_TRANS(PGP = ZPGP, PSPSCALAR = ZPSPSCALAR, &
               & KPROMA = NPROMA, KRESOL = KRESOL)
ELSE IF (NFIELD_UV > 0) THEN
  CALL DIR_TRANS(PSPVOR = ZPSPVOR, PSPDIV = ZPSPDIV, PGP = ZPGP, &
               & KPROMA = NPROMA, KRESOL = KRESOL)
ENDIF

! UNPACK TEMPORARY SPECTRAL FIELDS BACK INTO FIELD_VIEW
BLOCK
INTEGER(KIND=JPIM) :: JROF, JLEV, JFLD, IFIELD_TOTAL, IFIELD
REAL(KIND=JPRB), POINTER :: PTR_1D(:), PTR_2D(:,:), PTR_3D(:,:,:), PTR_4D(:,:,:,:)
IFIELD_TOTAL = 0
DO IFIELD=1,NFIELD_UV
  IF (YDSPVOR(IFIELD)%RANK == 1) THEN
    CALL FIELD_VIEW_GET_DATA_PTR(YDSPVOR(IFIELD), PTR_1D)
    IFIELD_TOTAL = IFIELD_TOTAL + 1
    PTR_1D(:) = ZPSPVOR(IFIELD_TOTAL,:)
  ELSE IF (YDSPVOR(IFIELD)%RANK == 2) THEN
    CALL FIELD_VIEW_GET_DATA_PTR(YDSPVOR(IFIELD), PTR_2D)
    DO JFLD = 1, YDSPVOR(IFIELD)%EXTENTS(1)
      IFIELD_TOTAL = IFIELD_TOTAL + 1
      PTR_2D(JFLD,:) = ZPSPVOR(IFIELD_TOTAL,:)
    ENDDO
  ELSE
    CALL ABOR1("[DIRTRANS_FIELD_VIEW] Unsupported rank for vorticity field")
  ENDIF
ENDDO
IFIELD_TOTAL = 0
DO IFIELD=1,NFIELD_UV

  IF (YDSPDIV(IFIELD)%RANK == 1) THEN
    CALL FIELD_VIEW_GET_DATA_PTR(YDSPDIV(IFIELD), PTR_1D)
    IFIELD_TOTAL = IFIELD_TOTAL + 1
    PTR_1D(:) = ZPSPDIV(IFIELD_TOTAL,:)
  ELSE IF (YDSPDIV(IFIELD)%RANK == 2) THEN
    CALL FIELD_VIEW_GET_DATA_PTR(YDSPDIV(IFIELD), PTR_2D)
    DO JFLD = 1, YDSPDIV(IFIELD)%EXTENTS(1)
      IFIELD_TOTAL = IFIELD_TOTAL + 1
      PTR_2D(JFLD,:) = ZPSPDIV(IFIELD_TOTAL,:)
    ENDDO
  ELSE
    CALL ABOR1("[DIRTRANS_FIELD_VIEW] Unsupported rank for divergence field")
  ENDIF
ENDDO
IFIELD_TOTAL = 0
DO IFIELD=1,NFIELD_SCALAR
  IF (YDSPSCALAR(IFIELD)%RANK == 1) THEN
    CALL FIELD_VIEW_GET_DATA_PTR(YDSPSCALAR(IFIELD), PTR_1D)
    IFIELD_TOTAL = IFIELD_TOTAL + 1
    PTR_1D(:) = ZPSPSCALAR(IFIELD_TOTAL,:)
  ELSE IF (YDSPSCALAR(IFIELD)%RANK == 2) THEN
    CALL FIELD_VIEW_GET_DATA_PTR(YDSPSCALAR(IFIELD), PTR_2D)
    DO JFLD = 1, YDSPSCALAR(IFIELD)%EXTENTS(1)
      IFIELD_TOTAL = IFIELD_TOTAL + 1
      PTR_2D(JFLD,:) = ZPSPSCALAR(IFIELD_TOTAL,:)
    ENDDO
  ELSE
    CALL ABOR1("[DIRTRANS_FIELD_VIEW] Unsupported rank for scalar field")
  ENDIF
ENDDO

END BLOCK

IF (LHOOK) CALL DR_HOOK('DIR_TRANS_FIELD_VIEW',1,ZHOOK_HANDLE)

END BLOCK

END SUBROUTINE