! (C) Copyright 2026- ECMWF.
! (C) Copyright 2001- Meteo-France.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.

MODULE ECTRANS_FIELD_API_MOD

USE PARKIND1, ONLY : JPIM, JPRB
USE FIELD_ACCESS_MODULE, ONLY: GET_HOST_DATA_RDWR, GET_DEVICE_DATA_RDWR, GET_HOST_DATA_RDONLY,GET_DEVICE_DATA_RDONLY
USE FIELD_BASIC_MODULE, ONLY: FIELD_BASIC
USE FIELD_MODULE, ONLY:FIELD_1RB, FIELD_2RB, FIELD_3RB, FIELD_4RB, FIELD_2RB_VIEW, FIELD_3RB_VIEW
USE ECTRANS_FIELD_VIEW_MOD, ONLY: FIELD_VIEW

USE, INTRINSIC :: ISO_C_BINDING, ONLY: C_PTR, C_INT, C_F_POINTER, C_FUNPTR, C_INTPTR_T, C_LOC, C_NULL_PTR
IMPLICIT NONE

PRIVATE

PUBLIC :: FIELD_GRID, FIELD_SPEC, MAKE_FIELD_GRID, MAKE_FIELD_SPEC, MAKE_FIELD_VIEW

TYPE FIELD_GRID
  ! A pointer to field API field with additional METADATA
  CLASS (FIELD_BASIC), POINTER :: PTR      ! POINTER TO FIELD_BASIC from field API
  CHARACTER(LEN=10)            :: NAME     ! Name
  INTEGER(KIND=JPIM)           :: DIM_V    ! Vertical dimension (0 if not applicable)
END TYPE

TYPE FIELD_SPEC
  ! A pointer to field API field with additional METADATA
  CLASS (FIELD_BASIC), POINTER    :: PTR      ! POINTER TO FIELD_BASIC from field API
  CHARACTER(LEN=10)               :: NAME     ! Name
  INTEGER(KIND=JPIM), ALLOCATABLE :: IVSET(:) ! b-set for spectral fields
END TYPE

INTERFACE MAKE_FIELD_GRID
  MODULE PROCEDURE :: MAKE_FIELD_GRID_1RB, MAKE_FIELD_GRID_2RB, MAKE_FIELD_GRID_3RB, MAKE_FIELD_GRID_4RB
END INTERFACE

INTERFACE MAKE_FIELD_SPEC
  MODULE PROCEDURE :: MAKE_FIELD_SPEC_1RB, MAKE_FIELD_SPEC_2RB, MAKE_FIELD_SPEC_3RB
END INTERFACE

INTERFACE MAKE_FIELD_VIEW
  MODULE PROCEDURE :: MAKE_FIELD_VIEW_SPEC, MAKE_FIELD_VIEW_GRID
END INTERFACE

! We use ABOR1 and not ABORT_TRANS because ABORT_TRANS is to be private to trans routines,
! and this interface is conceptually outside trans.
#include "abor1.intfb.h"

CONTAINS

SUBROUTINE PREVENT_COMPILER_OPTIMISATION(F)
  TYPE(FIELD_SPEC), TARGET, INTENT(INOUT) :: F
  INTEGER(KIND=JPIM), POINTER, VOLATILE, SAVE :: IVSET_DUMMY(:)
  IF (ALLOCATED(F%IVSET)) THEN
    IVSET_DUMMY => F%IVSET
  ELSE
    IVSET_DUMMY => NULL()
  END IF
END SUBROUTINE PREVENT_COMPILER_OPTIMISATION

FUNCTION MAKE_FIELD_SPEC_1RB(YLF,NAME,IVSET)
  ! Creation of a FIELD_SPEC encapsulating a FIELD_1RB field
  TYPE (FIELD_SPEC) :: MAKE_FIELD_SPEC_1RB
  CLASS (FIELD_1RB), INTENT(IN), POINTER :: YLF
  CHARACTER(LEN=*), INTENT(IN) :: NAME
  INTEGER(KIND=JPIM), INTENT(IN), OPTIONAL :: IVSET(:)

  MAKE_FIELD_SPEC_1RB%PTR => YLF
  MAKE_FIELD_SPEC_1RB%NAME = NAME
  IF (PRESENT(IVSET)) THEN
    ALLOCATE(MAKE_FIELD_SPEC_1RB%IVSET(SIZE(IVSET)))
    MAKE_FIELD_SPEC_1RB%IVSET = IVSET
  ENDIF
  CALL PREVENT_COMPILER_OPTIMISATION(MAKE_FIELD_SPEC_1RB)
END FUNCTION MAKE_FIELD_SPEC_1RB

FUNCTION MAKE_FIELD_SPEC_2RB(YLF,NAME,IVSET)
  ! Creation of a FIELD_SPEC encapsulating a FIELD_2RB field
  TYPE (FIELD_SPEC) :: MAKE_FIELD_SPEC_2RB
  CLASS (FIELD_2RB), INTENT(IN), POINTER :: YLF
  CHARACTER(LEN=*), INTENT(IN) :: NAME
  INTEGER(KIND=JPIM), INTENT(IN), OPTIONAL :: IVSET(:)

  MAKE_FIELD_SPEC_2RB%PTR => YLF
  MAKE_FIELD_SPEC_2RB%NAME = NAME
  IF (PRESENT(IVSET)) THEN
    ALLOCATE(MAKE_FIELD_SPEC_2RB%IVSET(SIZE(IVSET)))
    MAKE_FIELD_SPEC_2RB%IVSET = IVSET
  ENDIF
  CALL PREVENT_COMPILER_OPTIMISATION(MAKE_FIELD_SPEC_2RB)
END FUNCTION MAKE_FIELD_SPEC_2RB

FUNCTION MAKE_FIELD_SPEC_3RB(YLF,NAME,IVSET)
  ! Creation of a FIELD_SPEC encapsulating a FIELD_3RB field
  TYPE (FIELD_SPEC) :: MAKE_FIELD_SPEC_3RB
  CLASS (FIELD_3RB), INTENT(IN), POINTER :: YLF
  CHARACTER(LEN=*), INTENT(IN) :: NAME
  INTEGER(KIND=JPIM), INTENT(IN), OPTIONAL :: IVSET(:)

  MAKE_FIELD_SPEC_3RB%PTR => YLF
  MAKE_FIELD_SPEC_3RB%NAME = NAME
  IF (PRESENT(IVSET)) THEN
    ALLOCATE(MAKE_FIELD_SPEC_3RB%IVSET(SIZE(IVSET)))
    MAKE_FIELD_SPEC_3RB%IVSET = IVSET
  ENDIF
  CALL PREVENT_COMPILER_OPTIMISATION(MAKE_FIELD_SPEC_3RB)
END FUNCTION MAKE_FIELD_SPEC_3RB


FUNCTION MAKE_FIELD_GRID_1RB(YLF,NAME)
  ! Creation of a FIELD_GRID encapsulating a FIELD_1RB field
  TYPE (FIELD_GRID) :: MAKE_FIELD_GRID_1RB
  CLASS (FIELD_1RB), INTENT(IN), POINTER :: YLF
  CHARACTER(LEN=*), INTENT(IN) :: NAME

  MAKE_FIELD_GRID_1RB%PTR => YLF
  MAKE_FIELD_GRID_1RB%NAME = NAME
  MAKE_FIELD_GRID_1RB%DIM_V = 0
END FUNCTION MAKE_FIELD_GRID_1RB

FUNCTION MAKE_FIELD_GRID_2RB(YLF,NAME)
  ! Creation of a FIELD_GRID encapsulating a FIELD_2RB field
  TYPE (FIELD_GRID) :: MAKE_FIELD_GRID_2RB
  CLASS (FIELD_2RB), INTENT(IN), POINTER :: YLF
  CHARACTER(LEN=*),  INTENT(IN) :: NAME

  MAKE_FIELD_GRID_2RB%PTR => YLF
  MAKE_FIELD_GRID_2RB%NAME = NAME
  MAKE_FIELD_GRID_2RB%DIM_V = 0
END FUNCTION MAKE_FIELD_GRID_2RB

FUNCTION MAKE_FIELD_GRID_3RB(YLF,NAME)
  ! Creation of a FIELD_GRID encapsulating a FIELD_3RB field
  TYPE (FIELD_GRID) :: MAKE_FIELD_GRID_3RB
  CLASS (FIELD_3RB), INTENT(IN), POINTER :: YLF
  CHARACTER(LEN=*), INTENT(IN) :: NAME

  MAKE_FIELD_GRID_3RB%PTR => YLF
  MAKE_FIELD_GRID_3RB%NAME = NAME
  MAKE_FIELD_GRID_3RB%DIM_V = 1
END FUNCTION MAKE_FIELD_GRID_3RB

FUNCTION MAKE_FIELD_GRID_4RB(YLF,NAME)
  ! Creation of a FIELD_SPEC encapsulating a FIELD_4RB field
  TYPE (FIELD_GRID) :: MAKE_FIELD_GRID_4RB
  CLASS (FIELD_4RB), INTENT(IN), POINTER :: YLF
  CHARACTER(LEN=*), INTENT(IN) :: NAME

  MAKE_FIELD_GRID_4RB%PTR => YLF
  MAKE_FIELD_GRID_4RB%NAME = NAME
  MAKE_FIELD_GRID_4RB%DIM_V = 1
END FUNCTION MAKE_FIELD_GRID_4RB


SUBROUTINE SET_STRIDES_1RB(ARRAY, STRIDES)
  REAL(JPRB), POINTER :: ARRAY(:)
  INTEGER(C_INT), INTENT(OUT) :: STRIDES(:)
  TYPE(C_PTR) :: ADDR1, ADDR2
  INTEGER(C_INTPTR_T) :: STRIDE_BYTES
  STRIDES(:) = 0
  IF (SIZE(ARRAY) == 1) THEN
    STRIDES(1) = 1
    RETURN
  ENDIF
  ! At this code location we can be sure that there is more than 1 element in the array
  ADDR1 = C_LOC(ARRAY(1))
  ADDR2 = C_LOC(ARRAY(2))
  STRIDE_BYTES = TRANSFER(ADDR2, STRIDE_BYTES) - TRANSFER(ADDR1, STRIDE_BYTES)
  STRIDES(1) = STRIDE_BYTES / (STORAGE_SIZE(ARRAY) / 8)
END SUBROUTINE

SUBROUTINE SET_STRIDES_2RB(ARRAY, STRIDES)
  REAL(JPRB), POINTER :: ARRAY(:,:)
  INTEGER(C_INT), INTENT(OUT) :: STRIDES(:)
  TYPE(C_PTR) :: ADDR1, ADDR2
  INTEGER(C_INTPTR_T) :: STRIDE_BYTES
  IF (SIZE(ARRAY) == 0) THEN
    STRIDES(:) = 0
    RETURN
  ENDIF
  IF (SIZE(ARRAY) == 1) THEN
    STRIDES(:) = 1
    RETURN
  ENDIF
  ! At this code location we can be sure that there is more than 1 element in the array
  ADDR1 = C_LOC(ARRAY(1,1))

  ! Find STRIDES(1)
  IF (SIZE(ARRAY, 1) > 1) THEN
    ADDR2 = C_LOC(ARRAY(2,1))
  ELSE IF (SIZE(ARRAY, 2) > 1) THEN
    ADDR2 = C_LOC(ARRAY(1,2))
  ELSE
    CALL ABOR1("We should not be here, as SIZE(ARRAY) > 1")
  ENDIF
  STRIDE_BYTES = TRANSFER(ADDR2, STRIDE_BYTES) - TRANSFER(ADDR1, STRIDE_BYTES)
  STRIDES(1) = STRIDE_BYTES / (STORAGE_SIZE(ARRAY) / 8)

  ! Find STRIDES(2)
  IF (SIZE(ARRAY, 2) > 1) THEN
    ADDR2 = C_LOC(ARRAY(1,2))
    STRIDE_BYTES = TRANSFER(ADDR2, STRIDE_BYTES) - TRANSFER(ADDR1, STRIDE_BYTES)
    STRIDES(2) = STRIDE_BYTES / (STORAGE_SIZE(ARRAY) / 8)
  ELSE
    STRIDES(2) = STRIDES(1) * SIZE(ARRAY, 1)
  ENDIF
END SUBROUTINE

SUBROUTINE SET_STRIDES_3RB(ARRAY, STRIDES)
  REAL(JPRB), POINTER :: ARRAY(:,:,:)
  INTEGER(C_INT), INTENT(OUT) :: STRIDES(:)
  TYPE(C_PTR) :: ADDR1, ADDR2
  INTEGER(C_INTPTR_T) :: STRIDE_BYTES
  IF (SIZE(ARRAY) == 0) THEN
    STRIDES(:) = 0
    RETURN
  ENDIF
  IF (SIZE(ARRAY) == 1) THEN
    STRIDES(:) = 1
    RETURN
  ENDIF
  ! At this code location we can be sure that there is more than 1 element in the array
  ADDR1 = C_LOC(ARRAY(1,1,1))

  ! Find STRIDES(1)
  IF (SIZE(ARRAY, 1) > 1) THEN
    ADDR2 = C_LOC(ARRAY(2,1,1))
  ELSE IF (SIZE(ARRAY, 2) > 1) THEN
    ADDR2 = C_LOC(ARRAY(1,2,1))
  ELSE IF (SIZE(ARRAY, 3) > 1) THEN
    ADDR2 = C_LOC(ARRAY(1,1,2))
  ELSE
    CALL ABOR1("We should not be here, as SIZE(ARRAY) > 1")
  ENDIF
  STRIDE_BYTES = TRANSFER(ADDR2, STRIDE_BYTES) - TRANSFER(ADDR1, STRIDE_BYTES)
  STRIDES(1) = STRIDE_BYTES / (STORAGE_SIZE(ARRAY) / 8)

  ! Find STRIDES(2)
  IF (SIZE(ARRAY, 2) > 1) THEN
    ADDR2 = C_LOC(ARRAY(1,2,1))
    STRIDE_BYTES = TRANSFER(ADDR2, STRIDE_BYTES) - TRANSFER(ADDR1, STRIDE_BYTES)
    STRIDES(2) = STRIDE_BYTES / (STORAGE_SIZE(ARRAY) / 8)
  ELSE
    STRIDES(2) = STRIDES(1) * SIZE(ARRAY, 1)
  ENDIF

  ! Find STRIDES(3)
  IF (SIZE(ARRAY, 3) > 1) THEN
    ADDR2 = C_LOC(ARRAY(1,1,2))
    STRIDE_BYTES = TRANSFER(ADDR2, STRIDE_BYTES) - TRANSFER(ADDR1, STRIDE_BYTES)
    STRIDES(3) = STRIDE_BYTES / (STORAGE_SIZE(ARRAY) / 8)
  ELSE
    STRIDES(3) = STRIDES(2) * SIZE(ARRAY, 2)
  ENDIF
END SUBROUTINE

SUBROUTINE SET_STRIDES_4RB(ARRAY, STRIDES)
  REAL(JPRB), POINTER :: ARRAY(:,:,:,:)
  INTEGER(C_INT), INTENT(OUT) :: STRIDES(:)
  TYPE(C_PTR) :: ADDR1, ADDR2
  INTEGER(C_INTPTR_T) :: STRIDE_BYTES
  IF (SIZE(ARRAY) == 0) THEN
    STRIDES(:) = 0
    RETURN
  ENDIF
  IF (SIZE(ARRAY) == 1) THEN
    STRIDES(:) = 1
    RETURN
  ENDIF
  ! At this code location we can be sure that there is more than 1 element in the array
  ADDR1 = C_LOC(ARRAY(1,1,1,1))

  ! Find STRIDES(1)
  IF (SIZE(ARRAY, 1) > 1) THEN
    ADDR2 = C_LOC(ARRAY(2,1,1,1))
  ELSE IF (SIZE(ARRAY, 2) > 1) THEN
    ADDR2 = C_LOC(ARRAY(1,2,1,1))
  ELSE IF (SIZE(ARRAY, 3) > 1) THEN
    ADDR2 = C_LOC(ARRAY(1,1,2,1))
  ELSE IF (SIZE(ARRAY, 4) > 1) THEN
    ADDR2 = C_LOC(ARRAY(1,1,1,2))
  ELSE
    CALL ABOR1("We should not be here, as SIZE(ARRAY) > 1")
  ENDIF
  STRIDE_BYTES = TRANSFER(ADDR2, STRIDE_BYTES) - TRANSFER(ADDR1, STRIDE_BYTES)
  STRIDES(1) = STRIDE_BYTES / (STORAGE_SIZE(ARRAY) / 8)

  ! Find STRIDES(2)
  IF (SIZE(ARRAY, 2) > 1) THEN
    ADDR2 = C_LOC(ARRAY(1,2,1,1))
    STRIDE_BYTES = TRANSFER(ADDR2, STRIDE_BYTES) - TRANSFER(ADDR1, STRIDE_BYTES)
    STRIDES(2) = STRIDE_BYTES / (STORAGE_SIZE(ARRAY) / 8)
  ELSE
    STRIDES(2) = STRIDES(1) * SIZE(ARRAY, 1)
  ENDIF

  ! Find STRIDES(3)
  IF (SIZE(ARRAY, 3) > 1) THEN
    ADDR2 = C_LOC(ARRAY(1,1,2,1))
    STRIDE_BYTES = TRANSFER(ADDR2, STRIDE_BYTES) - TRANSFER(ADDR1, STRIDE_BYTES)
    STRIDES(3) = STRIDE_BYTES / (STORAGE_SIZE(ARRAY) / 8)
  ELSE
    STRIDES(3) = STRIDES(2) * SIZE(ARRAY, 2)
  ENDIF

  ! Find STRIDES(4)
  IF (SIZE(ARRAY, 4) > 1) THEN
    ADDR2 = C_LOC(ARRAY(1,1,1,2))
    STRIDE_BYTES = TRANSFER(ADDR2, STRIDE_BYTES) - TRANSFER(ADDR1, STRIDE_BYTES)
    STRIDES(4) = STRIDE_BYTES / (STORAGE_SIZE(ARRAY) / 8)
  ELSE
    STRIDES(4) = STRIDES(3) * SIZE(ARRAY, 3)
  ENDIF
END SUBROUTINE


SUBROUTINE SET_EXTENTS_1RB(ARRAY, EXTENTS)
  REAL(JPRB), POINTER :: ARRAY(:)
  INTEGER(C_INT), INTENT(OUT) :: EXTENTS(:)
  EXTENTS = 0
  EXTENTS(1) = SIZE(ARRAY)
END SUBROUTINE

SUBROUTINE SET_EXTENTS_2RB(ARRAY, EXTENTS)
  REAL(JPRB), POINTER :: ARRAY(:,:)
  INTEGER(C_INT), INTENT(OUT) :: EXTENTS(:)
  EXTENTS = 0
  EXTENTS(1) = SIZE(ARRAY,1)
  EXTENTS(2) = SIZE(ARRAY,2)
END SUBROUTINE

SUBROUTINE SET_EXTENTS_3RB(ARRAY, EXTENTS)
  REAL(JPRB), POINTER :: ARRAY(:,:,:)
  INTEGER(C_INT), INTENT(OUT) :: EXTENTS(:)
  EXTENTS = 0
  EXTENTS(1) = SIZE(ARRAY,1)
  EXTENTS(2) = SIZE(ARRAY,2)
  EXTENTS(3) = SIZE(ARRAY,3)
END SUBROUTINE

SUBROUTINE SET_EXTENTS_4RB(ARRAY, EXTENTS)
  REAL(JPRB), POINTER :: ARRAY(:,:,:,:)
  INTEGER(C_INT), INTENT(OUT) :: EXTENTS(:)
  EXTENTS = 0
  EXTENTS(1) = SIZE(ARRAY,1)
  EXTENTS(2) = SIZE(ARRAY,2)
  EXTENTS(3) = SIZE(ARRAY,3)
  EXTENTS(4) = SIZE(ARRAY,4)
END SUBROUTINE




SUBROUTINE SET_DATA_RDWR_1RB(YLFV, FIELD, LDACC, LDRDONLY)
  TYPE(FIELD_VIEW), INTENT(INOUT) :: YLFV
  CLASS(FIELD_1RB), POINTER, INTENT(IN) :: FIELD
  LOGICAL, INTENT(IN) :: LDACC
  LOGICAL, INTENT(IN) :: LDRDONLY
  REAL(JPRB), POINTER :: PTR(:)
  IF (LDACC) THEN
    IF (LDRDONLY) THEN
      CALL FIELD%GET_DEVICE_DATA_RDONLY(PTR)
    ELSE
      CALL FIELD%GET_DEVICE_DATA_RDWR(PTR)
    ENDIF
  ELSE
    IF (LDRDONLY) THEN
      CALL FIELD%GET_HOST_DATA_RDONLY(PTR)
    ELSE
      CALL FIELD%GET_HOST_DATA_RDWR(PTR)
    ENDIF
  ENDIF
  YLFV%DATA = C_LOC(PTR(1))
  YLFV%KIND = STORAGE_SIZE(PTR) / 8
  YLFV%RANK = 1
  CALL SET_EXTENTS_1RB(PTR, YLFV%EXTENTS)
  CALL SET_STRIDES_1RB(PTR, YLFV%STRIDES)
END SUBROUTINE

SUBROUTINE SET_DATA_RDWR_2RB(YLFV, FIELD, LDACC, LDRDONLY)
  TYPE(FIELD_VIEW), INTENT(INOUT) :: YLFV
  CLASS(FIELD_2RB), POINTER, INTENT(IN) :: FIELD
  LOGICAL, INTENT(IN) :: LDACC
  LOGICAL, INTENT(IN) :: LDRDONLY
  REAL(JPRB), POINTER :: PTR(:,:)
  IF (LDACC) THEN
    IF (LDRDONLY) THEN
      CALL FIELD%GET_DEVICE_DATA_RDONLY(PTR)
    ELSE
      CALL FIELD%GET_DEVICE_DATA_RDWR(PTR)
    ENDIF
  ELSE
    IF (LDRDONLY) THEN
      CALL FIELD%GET_HOST_DATA_RDONLY(PTR)
    ELSE
      CALL FIELD%GET_HOST_DATA_RDWR(PTR)
    ENDIF
  ENDIF
  YLFV%DATA = C_LOC(PTR(1,1))
  YLFV%KIND = STORAGE_SIZE(PTR) / 8
  YLFV%RANK = 2
  CALL SET_EXTENTS_2RB(PTR, YLFV%EXTENTS)
  CALL SET_STRIDES_2RB(PTR, YLFV%STRIDES)
END SUBROUTINE

SUBROUTINE SET_DATA_RDWR_3RB(YLFV, FIELD, LDACC, LDRDONLY)
  TYPE(FIELD_VIEW), INTENT(INOUT) :: YLFV
  CLASS(FIELD_3RB), POINTER, INTENT(IN) :: FIELD
  LOGICAL, INTENT(IN) :: LDACC
  LOGICAL, INTENT(IN) :: LDRDONLY
  REAL(JPRB), POINTER :: PTR(:,:,:)
  IF (LDACC) THEN
    IF (LDRDONLY) THEN
      CALL FIELD%GET_DEVICE_DATA_RDONLY(PTR)
    ELSE
      CALL FIELD%GET_DEVICE_DATA_RDWR(PTR)
    ENDIF
  ELSE
    IF (LDRDONLY) THEN
      CALL FIELD%GET_HOST_DATA_RDONLY(PTR)
    ELSE
      CALL FIELD%GET_HOST_DATA_RDWR(PTR)
    ENDIF
  ENDIF
  YLFV%DATA = C_LOC(PTR(1,1,1))
  YLFV%KIND = STORAGE_SIZE(PTR) / 8
  YLFV%RANK = 3
  CALL SET_EXTENTS_3RB(PTR, YLFV%EXTENTS)
  CALL SET_STRIDES_3RB(PTR, YLFV%STRIDES)
END SUBROUTINE

SUBROUTINE SET_DATA_RDWR_4RB(YLFV, FIELD, LDACC, LDRDONLY)
  TYPE(FIELD_VIEW), INTENT(INOUT) :: YLFV
  CLASS(FIELD_4RB), POINTER, INTENT(IN) :: FIELD
  LOGICAL, INTENT(IN) :: LDACC
  LOGICAL, INTENT(IN) :: LDRDONLY
  REAL(JPRB), POINTER :: PTR(:,:,:,:)
  IF (LDACC) THEN
    IF (LDRDONLY) THEN
      CALL FIELD%GET_DEVICE_DATA_RDONLY(PTR)
    ELSE
      CALL FIELD%GET_DEVICE_DATA_RDWR(PTR)
    ENDIF
  ELSE
    IF (LDRDONLY) THEN
      CALL FIELD%GET_HOST_DATA_RDONLY(PTR)
    ELSE
      CALL FIELD%GET_HOST_DATA_RDWR(PTR)
    ENDIF
  ENDIF
  YLFV%DATA = C_LOC(PTR(1,1,1,1))
  YLFV%KIND = STORAGE_SIZE(PTR) / 8
  YLFV%RANK = 4
  CALL SET_EXTENTS_4RB(PTR, YLFV%EXTENTS)
  CALL SET_STRIDES_4RB(PTR, YLFV%STRIDES)
END SUBROUTINE

SUBROUTINE SET_NAME(YLFV, NAME)
  TYPE(FIELD_VIEW), INTENT(INOUT) :: YLFV
  CHARACTER(LEN=*), TARGET, INTENT(IN) :: NAME
  YLFV%NAME = C_LOC(NAME(1:1))
  YLFV%NAME_SIZE = LEN_TRIM(NAME)
END SUBROUTINE

SUBROUTINE SET_FIELD_TYPE(YLFV, FIELD_TYPE)
  TYPE(FIELD_VIEW), INTENT(INOUT) :: YLFV
  INTEGER, INTENT(IN) :: FIELD_TYPE
  YLFV%FIELD_TYPE = FIELD_TYPE
END SUBROUTINE

SUBROUTINE SET_IVSET(YLFV, IVSET)
  TYPE(FIELD_VIEW), INTENT(INOUT) :: YLFV
  INTEGER(C_INT), TARGET, ALLOCATABLE, INTENT(IN) :: IVSET(:)
  IF (ALLOCATED(IVSET)) THEN
    YLFV%IVSET = C_LOC(IVSET(1))
    YLFV%IVSET_SIZE = SIZE(IVSET)
  ELSE
    YLFV%IVSET = C_NULL_PTR
    YLFV%IVSET_SIZE = 0
  ENDIF
END SUBROUTINE

SUBROUTINE MAKE_FIELD_VIEW_SPEC(YLFV, YLF, FIELD_TYPE, LDACC, LDRDONLY)
  TYPE(FIELD_VIEW), INTENT(INOUT) :: YLFV
  TYPE(FIELD_SPEC), INTENT(IN) :: YLF
  INTEGER :: FIELD_TYPE
  LOGICAL, INTENT(IN) :: LDACC
  LOGICAL, INTENT(IN) :: LDRDONLY
  SELECT TYPE (FIELD => YLF%PTR)
    CLASS IS (FIELD_1RB)
      CALL SET_DATA_RDWR_1RB(YLFV, FIELD, LDACC, LDRDONLY)
    CLASS IS (FIELD_2RB)
      CALL SET_DATA_RDWR_2RB(YLFV, FIELD, LDACC, LDRDONLY)
    CLASS IS (FIELD_3RB)
      CALL SET_DATA_RDWR_3RB(YLFV, FIELD, LDACC, LDRDONLY)
    CLASS IS (FIELD_4RB)
      CALL SET_DATA_RDWR_4RB(YLFV, FIELD, LDACC, LDRDONLY)
    CLASS DEFAULT
      CALL ABOR1("MAKE_FIELD_VIEW FAILURE: CLASS UNKNOWN")
  END SELECT
  CALL SET_NAME(YLFV, YLF%NAME)
  CALL SET_FIELD_TYPE(YLFV, FIELD_TYPE)
  CALL SET_IVSET(YLFV, YLF%IVSET)

END SUBROUTINE

SUBROUTINE MAKE_FIELD_VIEW_GRID(YLFV, YLF, FIELD_TYPE, LDACC, LDRDONLY)
  TYPE(FIELD_VIEW), INTENT(INOUT) :: YLFV
  TYPE(FIELD_GRID), INTENT(IN) :: YLF
  INTEGER :: FIELD_TYPE
  LOGICAL, INTENT(IN) :: LDACC
  LOGICAL, INTENT(IN) :: LDRDONLY

  SELECT TYPE (FIELD => YLF%PTR)
    CLASS IS (FIELD_1RB)
      CALL SET_DATA_RDWR_1RB(YLFV, FIELD, LDACC, LDRDONLY)
    CLASS IS (FIELD_2RB)
      CALL SET_DATA_RDWR_2RB(YLFV, FIELD, LDACC, LDRDONLY)
    CLASS IS (FIELD_3RB)
      CALL SET_DATA_RDWR_3RB(YLFV, FIELD, LDACC, LDRDONLY)
    CLASS IS (FIELD_4RB)
      CALL SET_DATA_RDWR_4RB(YLFV, FIELD, LDACC, LDRDONLY)
    CLASS DEFAULT
      CALL ABOR1("MAKE_FIELD_VIEW FAILURE: CLASS UNKNOWN")
  END SELECT
  CALL SET_NAME(YLFV, YLF%NAME)
  CALL SET_FIELD_TYPE(YLFV, FIELD_TYPE)

END SUBROUTINE


END MODULE ECTRANS_FIELD_API_MOD

