! (C) Copyright 2001- ECMWF.
! (C) Copyright 2001- Meteo-France.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.

MODULE ECTRANS_FIELD_VIEW_MOD

USE EC_PARKIND, ONLY : JPIM, JPRM, JPRD
USE ABORT_TRANS_MOD, ONLY: ABORT_TRANS
USE, INTRINSIC :: ISO_C_BINDING, ONLY: C_PTR, C_INT, C_F_POINTER
IMPLICIT NONE

PRIVATE

PUBLIC :: FIELD_VIEW, FIELD_VIEW_GET_DATA_PTR, GET_NBLK, GET_NPROMA, GET_NFLD, GET_NSPEC2

PUBLIC :: &                     ! [INDEXING_TYPE] F: fields or levels,    D: degrees-of-freedom : nproma, blocks, nspec2, etc. (i.e. non-field dimensions)
    & INDEXING_TYPE_UNKNOWN, &  !     A single field for following types is referenced as
    & INDEXING_TYPE_DFFD, &     !       ARRAY(:, JLEV, JVAR, :)
    & INDEXING_TYPE_DFD, &      !       ARRAY(:, JFLD, :)
    & INDEXING_TYPE_DF, &       !       ARRAY(:, JFLD)
    & INDEXING_TYPE_FD, &       !       ARRAY(JFLD, :)
    & INDEXING_TYPE_D           !       ARRAY(:)
PUBLIC :: &
    & MEMORY_TYPE_UNKNOWN, &
    & MEMORY_TYPE_HOST, &
    & MEMORY_TYPE_DEVICE
PUBLIC :: &
    & FIELD_TYPE_UNKNOWN, &
    & FIELD_TYPE_VOR, &
    & FIELD_TYPE_DIV, &
    & FIELD_TYPE_U, &
    & FIELD_TYPE_V, &
    & FIELD_TYPE_S, &
    & FIELD_TYPE_EW, &
    & FIELD_TYPE_NS, &
    & FIELD_TYPE_SP, &
    & FIELD_TYPE_GP, &
    & FIELD_TYPE_GP_U_EW, &
    & FIELD_TYPE_GP_V_EW, &
    & FIELD_TYPE_GP_S_EW, &
    & FIELD_TYPE_GP_S_NS, &
    & FIELD_TYPE_SP_VOR, &
    & FIELD_TYPE_SP_DIV, &
    & FIELD_TYPE_GP_S, &
    & FIELD_TYPE_SP_S, &
    & FIELD_TYPE_GP_U, &
    & FIELD_TYPE_GP_V, &
    & FIELD_TYPE_TEST

INTEGER(C_INT), PARAMETER :: MAX_RANK = 4

! FIELD_TYPE
INTEGER(C_INT), PARAMETER :: &
    & FIELD_TYPE_UNKNOWN   = INT(B'00000000000000000000000000000000', C_INT), &
    & FIELD_TYPE_VOR       = INT(B'00000000000000000000000000000001', C_INT), &
    & FIELD_TYPE_DIV       = INT(B'00000000000000000000000000000010', C_INT), &
    & FIELD_TYPE_U         = INT(B'00000000000000000000000000000100', C_INT), &
    & FIELD_TYPE_V         = INT(B'00000000000000000000000000001000', C_INT), &
    & FIELD_TYPE_S         = INT(B'00000000000000000000000000010000', C_INT), &
    & FIELD_TYPE_EW        = INT(B'00000000000000000000000000100000', C_INT), &
    & FIELD_TYPE_NS        = INT(B'00000000000000000000000001000000', C_INT), &
    & FIELD_TYPE_SP        = INT(B'00000000000000000000000010000000', C_INT), &
    & FIELD_TYPE_GP        = INT(B'00000000000000000000000100000000', C_INT), &
    & FIELD_TYPE_GP_U_EW   = IOR(IOR(FIELD_TYPE_GP, FIELD_TYPE_U), FIELD_TYPE_EW), &
    & FIELD_TYPE_GP_V_EW   = IOR(IOR(FIELD_TYPE_GP, FIELD_TYPE_V), FIELD_TYPE_EW), &
    & FIELD_TYPE_GP_S_EW   = IOR(IOR(FIELD_TYPE_GP, FIELD_TYPE_S), FIELD_TYPE_EW), &
    & FIELD_TYPE_GP_S_NS   = IOR(IOR(FIELD_TYPE_GP, FIELD_TYPE_S), FIELD_TYPE_NS), &
    & FIELD_TYPE_SP_VOR    = IOR(FIELD_TYPE_SP, FIELD_TYPE_VOR), &
    & FIELD_TYPE_SP_DIV    = IOR(FIELD_TYPE_SP, FIELD_TYPE_DIV), &
    & FIELD_TYPE_GP_S      = IOR(FIELD_TYPE_GP, FIELD_TYPE_S), &
    & FIELD_TYPE_SP_S      = IOR(FIELD_TYPE_SP, FIELD_TYPE_S), &
    & FIELD_TYPE_GP_U      = IOR(FIELD_TYPE_GP, FIELD_TYPE_U), &
    & FIELD_TYPE_GP_V      = IOR(FIELD_TYPE_GP, FIELD_TYPE_V)


! INDEXING_TYPE
!  F: fields or levels
!  D: degrees-of-freedom : nproma, blocks, nspec2, etc. (i.e. non-field dimensions)
INTEGER(C_INT), PARAMETER :: &
    & INDEXING_TYPE_UNKNOWN = INT(Z'00000000', C_INT), &
    & INDEXING_TYPE_DFFD    = INT(Z'DFFD0000', C_INT), &
    & INDEXING_TYPE_DFD     = INT(Z'DFD00000', C_INT), &
    & INDEXING_TYPE_DF      = INT(Z'DF000000', C_INT), &
    & INDEXING_TYPE_FD      = INT(Z'FD000000', C_INT), &
    & INDEXING_TYPE_D       = INT(Z'D0000000', C_INT)

! MEMORY_TYPE
INTEGER(C_INT), PARAMETER ::   &
    & MEMORY_TYPE_UNKNOWN = 0, &
    & MEMORY_TYPE_HOST    = 1, &
    & MEMORY_TYPE_DEVICE  = 2

TYPE, BIND(C) :: FIELD_VIEW

  ! ARRAY
  TYPE(C_PTR)    :: DATA
  INTEGER(C_INT) :: KIND
  INTEGER(C_INT) :: RANK
  INTEGER(C_INT) :: EXTENTS(MAX_RANK) ! NOTE: FORTRAN ORDERING
  INTEGER(C_INT) :: STRIDES(MAX_RANK) ! NOTE: FORTRAN ORDERING

  ! IVSET
  TYPE(C_PTR)    :: IVSET
  INTEGER(C_INT) :: IVSET_SIZE

  ! NAME
  TYPE(C_PTR)    :: NAME
  INTEGER(C_INT) :: NAME_SIZE

  ! FIELD TYPE
  INTEGER(C_INT) :: FIELD_TYPE

  ! INDEXING TYPE
  INTEGER(C_INT) :: INDEXING_TYPE     ! NOTE: FORTRAN ORDERING

  ! MEMORY TYPE
  INTEGER(C_INT) :: MEMORY_TYPE

END TYPE


INTERFACE FIELD_VIEW_GET_DATA_PTR
  MODULE PROCEDURE :: GET_DATA_PTR_1RM, GET_DATA_PTR_2RM, GET_DATA_PTR_3RM, GET_DATA_PTR_4RM
  MODULE PROCEDURE :: GET_DATA_PTR_1RD, GET_DATA_PTR_2RD, GET_DATA_PTR_3RD, GET_DATA_PTR_4RD
END INTERFACE

INTERFACE GET_NFLD
  MODULE PROCEDURE :: GET_NFLD_1, GET_NFLD_3
END INTERFACE

INTERFACE GET_NPROMA
  MODULE PROCEDURE :: GET_NPROMA_1, GET_NPROMA_2, GET_NPROMA_3
END INTERFACE

INTERFACE GET_NBLK
  MODULE PROCEDURE :: GET_NBLK_1, GET_NBLK_2, GET_NBLK_3
END INTERFACE

INTERFACE GET_NSPEC2
  MODULE PROCEDURE :: GET_NSPEC2_1, GET_NSPEC2_2, GET_NSPEC2_3
END INTERFACE

INTERFACE FIELD_TYPE_TEST
  MODULE PROCEDURE :: FIELD_TYPE_TEST_1, FIELD_TYPE_TEST_2, FIELD_TYPE_TEST_3
END INTERFACE

CONTAINS

FUNCTION FIELD_TYPE_TEST_1(FIELD_TYPE, TEST_MASK) RESULT(IS_SET)
  INTEGER(C_INT), INTENT(IN) :: FIELD_TYPE
  INTEGER(C_INT), INTENT(IN) :: TEST_MASK
  LOGICAL :: IS_SET
  IS_SET = (IAND(FIELD_TYPE, TEST_MASK) == TEST_MASK)
END FUNCTION

FUNCTION FIELD_TYPE_TEST_2(FIELD_TYPE, TEST_MASK1, TEST_MASK2) RESULT(IS_SET)
  INTEGER(C_INT), INTENT(IN) :: FIELD_TYPE
  INTEGER(C_INT), INTENT(IN) :: TEST_MASK1, TEST_MASK2
  LOGICAL :: IS_SET
  INTEGER(C_INT) :: COMBINED_MASK
  COMBINED_MASK = IOR(TEST_MASK1, TEST_MASK2)
  IS_SET = (IAND(FIELD_TYPE, COMBINED_MASK) == COMBINED_MASK)
END FUNCTION

FUNCTION FIELD_TYPE_TEST_3(FIELD_TYPE, TEST_MASK1, TEST_MASK2, TEST_MASK3) RESULT(IS_SET)
  INTEGER(C_INT), INTENT(IN) :: FIELD_TYPE
  INTEGER(C_INT), INTENT(IN) :: TEST_MASK1, TEST_MASK2, TEST_MASK3
  LOGICAL :: IS_SET
  INTEGER(C_INT) :: COMBINED_MASK
  COMBINED_MASK = IOR(TEST_MASK1, IOR(TEST_MASK2, TEST_MASK3))
  IS_SET = (IAND(FIELD_TYPE, COMBINED_MASK) == COMBINED_MASK)
END FUNCTION


SUBROUTINE COPY_NAME(YLFV, NAME)
  CHARACTER(LEN=*) :: NAME
  TYPE(FIELD_VIEW), INTENT(IN) :: YLFV
  CHARACTER(LEN=1), POINTER :: NAME_FPTR(:)
  INTEGER :: I
  CALL C_F_POINTER(YLFV%NAME, NAME_FPTR, [YLFV%NAME_SIZE])
  IF (LEN(NAME) < YLFV%NAME_SIZE) THEN
    CALL ABORT_TRANS("COPY_NAME FAILURE: NAME length is smaller than NAME_SIZE")
  ENDIF
  DO I = 1, YLFV%NAME_SIZE
    NAME(I:I) = NAME_FPTR(I)
  ENDDO
  DO I = YLFV%NAME_SIZE + 1, LEN(NAME)
    NAME(I:I) = " "
  ENDDO
END SUBROUTINE

SUBROUTINE GET_NAME_PTR(YLFV, NAME)
  TYPE(FIELD_VIEW), INTENT(IN) :: YLFV
  CHARACTER(LEN=:), POINTER :: NAME
  CHARACTER(LEN=YLFV%NAME_SIZE), POINTER :: F_STR
  CALL C_F_POINTER(YLFV%NAME, F_STR)
  NAME => F_STR
END SUBROUTINE

SUBROUTINE GET_DATA_PTR_1RM(YLFV, PTR)
  TYPE(FIELD_VIEW), INTENT(IN) :: YLFV
  REAL(JPRM), POINTER :: PTR(:)
  IF (YLFV%RANK /= 1) THEN
    CALL ABORT_TRANS("GET_DATA_PTR_1RM FAILURE: RANK MUST BE 1")
  ENDIF
  CALL C_F_POINTER(YLFV%DATA, PTR, YLFV%EXTENTS(1:YLFV%RANK))
END SUBROUTINE

SUBROUTINE GET_DATA_PTR_2RM(YLFV, PTR)
  TYPE(FIELD_VIEW), INTENT(IN) :: YLFV
  REAL(JPRM),     POINTER :: PTR(:,:)
  IF (YLFV%RANK /= 2) THEN
    CALL ABOR1("GET_DATA_PTR_2RM FAILURE: RANK MUST BE 2")
  ENDIF
  CALL C_F_POINTER(YLFV%DATA, PTR, YLFV%EXTENTS(1:YLFV%RANK))
END SUBROUTINE

SUBROUTINE GET_DATA_PTR_3RM(YLFV, PTR)
  TYPE(FIELD_VIEW), INTENT(IN) :: YLFV
  REAL(JPRM),     POINTER :: PTR(:,:,:)
  IF (YLFV%RANK /= 3) THEN
    CALL ABORT_TRANS("GET_DATA_PTR_3RM FAILURE: RANK MUST BE 3")
  ENDIF
  CALL C_F_POINTER(YLFV%DATA, PTR, YLFV%EXTENTS(1:YLFV%RANK))
END SUBROUTINE

SUBROUTINE GET_DATA_PTR_4RM(YLFV, PTR)
  TYPE(FIELD_VIEW), INTENT(IN) :: YLFV
  REAL(JPRM),     POINTER :: PTR(:,:,:,:)
  IF (YLFV%RANK /= 4) THEN
    CALL ABORT_TRANS("GET_DATA_PTR_4RM FAILURE: RANK MUST BE 4")
  ENDIF
  CALL C_F_POINTER(YLFV%DATA, PTR, YLFV%EXTENTS(1:YLFV%RANK))
END SUBROUTINE

SUBROUTINE GET_DATA_PTR_1RD(YLFV, PTR)
  TYPE(FIELD_VIEW), INTENT(IN) :: YLFV
  REAL(JPRD), POINTER :: PTR(:)
  IF (YLFV%RANK /= 1) THEN
    CALL ABORT_TRANS("GET_DATA_PTR_1RD FAILURE: RANK MUST BE 1")
  ENDIF
  CALL C_F_POINTER(YLFV%DATA, PTR, YLFV%EXTENTS(1:YLFV%RANK))
END SUBROUTINE

SUBROUTINE GET_DATA_PTR_2RD(YLFV, PTR)
  TYPE(FIELD_VIEW), INTENT(IN) :: YLFV
  REAL(JPRD),     POINTER :: PTR(:,:)
  IF (YLFV%RANK /= 2) THEN
    CALL ABORT_TRANS("GET_DATA_PTR_2RD FAILURE: RANK MUST BE 2")
  ENDIF
  CALL C_F_POINTER(YLFV%DATA, PTR, YLFV%EXTENTS(1:YLFV%RANK))
END SUBROUTINE

SUBROUTINE GET_DATA_PTR_3RD(YLFV, PTR)
  TYPE(FIELD_VIEW), INTENT(IN) :: YLFV
  REAL(JPRD),     POINTER :: PTR(:,:,:)
  IF (YLFV%RANK /= 3) THEN
    CALL ABORT_TRANS("GET_DATA_PTR_3RD FAILURE: RANK MUST BE 3")
  ENDIF
  CALL C_F_POINTER(YLFV%DATA, PTR, YLFV%EXTENTS(1:YLFV%RANK))
END SUBROUTINE

SUBROUTINE GET_DATA_PTR_4RD(YLFV, PTR)
  TYPE(FIELD_VIEW), INTENT(IN) :: YLFV
  REAL(JPRD),     POINTER :: PTR(:,:,:,:)
  IF (YLFV%RANK /= 4) THEN
    CALL ABORT_TRANS("GET_DATA_PTR_4RD FAILURE: RANK MUST BE 4")
  ENDIF
  CALL C_F_POINTER(YLFV%DATA, PTR, YLFV%EXTENTS(1:YLFV%RANK))
END SUBROUTINE

SUBROUTINE GET_IVSET(YLFV, IVSET)
  TYPE(FIELD_VIEW), INTENT(IN) :: YLFV
  INTEGER(C_INT) :: IVSET
  INTEGER(C_INT), POINTER :: IVSET_FPTR(:)
  IF (YLFV%IVSET_SIZE /= 1) THEN
    CALL ABORT_TRANS("GET_IVSET FAILURE: IVSET_SIZE MUST BE 1")
  ENDIF
  CALL C_F_POINTER(YLFV%IVSET, IVSET_FPTR, [YLFV%IVSET_SIZE])
  IVSET = IVSET_FPTR(1)
END SUBROUTINE


SUBROUTINE PROCESS_NPROMA(LIST, NPROMA)
  TYPE(FIELD_VIEW), INTENT(IN) :: LIST(:)
  INTEGER(C_INT), INTENT(INOUT) :: NPROMA
  INTEGER :: I
  DO I = 1, SIZE(LIST)
    IF (LIST(I)%RANK == 1) THEN
      IF (NPROMA == 0) THEN
        NPROMA = 1
      ELSE IF (NPROMA /= 1) THEN
        CALL ABORT_TRANS("GET_NPROMA FAILURE: Inconsistent NPROMA values across fields")
      ENDIF
    ELSE
      IF (NPROMA == 0) THEN
        NPROMA = LIST(I)%EXTENTS(1)
      ELSE IF (NPROMA /= LIST(I)%EXTENTS(1)) THEN
        CALL ABORT_TRANS("GET_NPROMA FAILURE: Inconsistent NPROMA values across fields")
      ENDIF
    ENDIF
  ENDDO
END SUBROUTINE

FUNCTION GET_NPROMA_1(LIST) RESULT(NPROMA)
  TYPE(FIELD_VIEW), INTENT(IN) :: LIST(:)
  INTEGER(C_INT) :: NPROMA
  NPROMA = 0
  CALL PROCESS_NPROMA(LIST, NPROMA)
END FUNCTION

FUNCTION GET_NPROMA_2(LIST1, LIST2) RESULT(NPROMA)
  TYPE(FIELD_VIEW), INTENT(IN) :: LIST1(:), LIST2(:)
  INTEGER(C_INT) :: NPROMA
  NPROMA = 0
  CALL PROCESS_NPROMA(LIST1, NPROMA)
  CALL PROCESS_NPROMA(LIST2, NPROMA)
END FUNCTION 

FUNCTION GET_NPROMA_3(LIST1, LIST2, LIST3) RESULT(NPROMA)
  TYPE(FIELD_VIEW), INTENT(IN) :: LIST1(:), LIST2(:), LIST3(:)
  INTEGER(C_INT) :: NPROMA
  NPROMA = 0
  CALL PROCESS_NPROMA(LIST1, NPROMA)
  CALL PROCESS_NPROMA(LIST2, NPROMA)
  CALL PROCESS_NPROMA(LIST3, NPROMA)
END FUNCTION 

SUBROUTINE PROCESS_NBLK(LIST, NBLK)
  TYPE(FIELD_VIEW), INTENT(IN) :: LIST(:)
  INTEGER(C_INT), INTENT(INOUT) :: NBLK
  INTEGER :: I
  DO I = 1, SIZE(LIST)
    IF (LIST(I)%RANK == 1) THEN
      IF (NBLK == 0) THEN
        NBLK = 1
      ELSE IF (NBLK /= 1) THEN
        CALL ABORT_TRANS("GET_NBLK FAILURE: Inconsistent NBLK values across fields")
      ENDIF
    ELSE
      IF (NBLK == 0) THEN
        NBLK = LIST(I)%EXTENTS(LIST(I)%RANK)
      ELSE IF (NBLK /= LIST(I)%EXTENTS(LIST(I)%RANK)) THEN
        CALL ABORT_TRANS("GET_NBLK FAILURE: Inconsistent NBLK values across fields")
      ENDIF
    ENDIF
  ENDDO
END SUBROUTINE

FUNCTION GET_NBLK_1(LIST) RESULT(NBLK)
  TYPE(FIELD_VIEW), INTENT(IN) :: LIST(:)
  INTEGER(C_INT) :: NBLK
  INTEGER :: I
  NBLK = 0
  CALL PROCESS_NBLK(LIST, NBLK)
END FUNCTION

FUNCTION GET_NBLK_2(LIST1, LIST2) RESULT(NBLK)
  TYPE(FIELD_VIEW), INTENT(IN) :: LIST1(:), LIST2(:)
  INTEGER(C_INT) :: NBLK
  NBLK = 0
  CALL PROCESS_NBLK(LIST1, NBLK)
  CALL PROCESS_NBLK(LIST2, NBLK)
END FUNCTION 

FUNCTION GET_NBLK_3(LIST1, LIST2, LIST3) RESULT(NBLK)
  TYPE(FIELD_VIEW), INTENT(IN) :: LIST1(:), LIST2(:), LIST3(:)
  INTEGER(C_INT) :: NBLK
  NBLK = 0
  CALL PROCESS_NBLK(LIST1, NBLK)
  CALL PROCESS_NBLK(LIST2, NBLK)
  CALL PROCESS_NBLK(LIST3, NBLK)
END FUNCTION 

SUBROUTINE PROCESS_NFLD(LIST, NFLD)
  TYPE(FIELD_VIEW), INTENT(IN) :: LIST(:)
  INTEGER(C_INT), INTENT(INOUT) :: NFLD
  INTEGER :: I
  DO I = 1, SIZE(LIST)
    IF (LIST(I)%RANK <= 2) THEN
      NFLD = NFLD + 1
    ELSE IF (LIST(I)%RANK == 3) THEN
      NFLD = NFLD + LIST(I)%EXTENTS(2)
    ELSE IF (LIST(I)%RANK == 4) THEN
      NFLD = NFLD + LIST(I)%EXTENTS(2) * LIST(I)%EXTENTS(3)
    ELSE
      CALL ABORT_TRANS("GET_NFLD FAILURE: RANK MUST BE <= 4")
    ENDIF
  ENDDO
END SUBROUTINE

FUNCTION GET_NFLD_1(LIST) RESULT(NFLD)
  TYPE(FIELD_VIEW), INTENT(IN) :: LIST(:)
  INTEGER(C_INT) :: NFLD
  NFLD = 0
  CALL PROCESS_NFLD(LIST, NFLD)
END FUNCTION

FUNCTION GET_NFLD_2(LIST1, LIST2) RESULT(NFLD)
  TYPE(FIELD_VIEW), INTENT(IN) :: LIST1(:), LIST2(:)
  INTEGER(C_INT) :: NFLD
  NFLD = 0
  CALL PROCESS_NFLD(LIST1, NFLD)
  CALL PROCESS_NFLD(LIST2, NFLD)
END FUNCTION

FUNCTION GET_NFLD_3(LIST1, LIST2, LIST3) RESULT(NFLD)
  TYPE(FIELD_VIEW), INTENT(IN) :: LIST1(:), LIST2(:), LIST3(:)
  INTEGER(C_INT) :: NFLD
  NFLD = 0
  CALL PROCESS_NFLD(LIST1, NFLD)
  CALL PROCESS_NFLD(LIST2, NFLD)
  CALL PROCESS_NFLD(LIST3, NFLD)
END FUNCTION


SUBROUTINE PROCESS_NSPEC2(LIST, NSPEC2)
  TYPE(FIELD_VIEW), INTENT(IN) :: LIST(:)
  INTEGER(C_INT), INTENT(INOUT) :: NSPEC2
  INTEGER :: I
  DO I = 1, SIZE(LIST)
    IF (LIST(I)%RANK == 1) THEN
      IF (NSPEC2 == 0) THEN
        NSPEC2 = LIST(I)%EXTENTS(1)
      ELSE IF (NSPEC2 /= LIST(I)%EXTENTS(1)) THEN
        CALL ABORT_TRANS("GET_NSPEC2 FAILURE: Inconsistent NSPEC2 values across fields")
      ENDIF
    ELSE IF (LIST(I)%RANK == 2) THEN
      IF (NSPEC2 == 0) THEN
        NSPEC2 = LIST(I)%EXTENTS(2)
      ELSE IF (NSPEC2 /= LIST(I)%EXTENTS(2)) THEN
        CALL ABORT_TRANS("GET_NSPEC2 FAILURE: Inconsistent NSPEC2 values across fields")
      ENDIF
    ELSE
      CALL ABORT_TRANS("GET_NSPEC2 FAILURE: RANK MUST BE <= 2")
    ENDIF
  ENDDO
END SUBROUTINE

FUNCTION GET_NSPEC2_1(LIST) RESULT(NSPEC2)
  TYPE(FIELD_VIEW), INTENT(IN) :: LIST(:)
  INTEGER(C_INT) :: NSPEC2
  NSPEC2 = 0
  CALL PROCESS_NSPEC2(LIST, NSPEC2)
END FUNCTION

FUNCTION GET_NSPEC2_2(LIST1, LIST2) RESULT(NSPEC2)
  TYPE(FIELD_VIEW), INTENT(IN) :: LIST1(:), LIST2(:)
  INTEGER(C_INT) :: NSPEC2
  NSPEC2 = 0
  CALL PROCESS_NSPEC2(LIST1, NSPEC2)
  CALL PROCESS_NSPEC2(LIST2, NSPEC2)
END FUNCTION

FUNCTION GET_NSPEC2_3(LIST1, LIST2, LIST3) RESULT(NSPEC2)
  TYPE(FIELD_VIEW), INTENT(IN) :: LIST1(:), LIST2(:), LIST3(:)
  INTEGER(C_INT) :: NSPEC2
  NSPEC2 = 0
  CALL PROCESS_NSPEC2(LIST1, NSPEC2)
  CALL PROCESS_NSPEC2(LIST2, NSPEC2)
  CALL PROCESS_NSPEC2(LIST3, NSPEC2)
END FUNCTION


END MODULE ECTRANS_FIELD_VIEW_MOD

