! (C) Copyright 2001- ECMWF.
! (C) Copyright 2001- Meteo-France.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.

MODULE ECTRANS_FIELD_VIEW_MOD

USE PARKIND1, ONLY : JPIM, JPRB

USE, INTRINSIC :: ISO_C_BINDING, ONLY: C_PTR, C_INT, C_F_POINTER
IMPLICIT NONE

PRIVATE

PUBLIC :: FIELD_VIEW, FIELD_VIEW_GET_DATA_PTR, GET_NBLK, GET_NPROMA, GET_NFLD, GET_NSPEC2, GET_NSPEC2_3, COPY_NAME, GET_IVSET

INTEGER, PARAMETER :: MAX_RANK = 5

TYPE FIELD_VIEW

  ! ARRAY
  TYPE(C_PTR)    :: DATA
  INTEGER(C_INT) :: KIND_SIZE
  INTEGER(C_INT) :: RANK
  INTEGER(C_INT) :: EXTENTS(MAX_RANK)
  INTEGER(C_INT) :: STRIDES(MAX_RANK)

  ! IVSET
  TYPE(C_PTR)    :: IVSET
  INTEGER(C_INT) :: IVSET_SIZE

  ! NAME
  TYPE(C_PTR)    :: NAME
  INTEGER(C_INT) :: NAME_SIZE

  ! FIELD TYPE
  INTEGER(C_INT) :: FIELD_TYPE

  ! INDEXING
  INTEGER(C_INT) :: INDEXING

END TYPE

INTERFACE FIELD_VIEW_GET_DATA_PTR
  MODULE PROCEDURE :: GET_DATA_PTR_1RB, GET_DATA_PTR_2RB, GET_DATA_PTR_3RB, GET_DATA_PTR_4RB
END INTERFACE

INTERFACE GET_NFLD
  MODULE PROCEDURE :: GET_NFLD_1, GET_NFLD_3
END INTERFACE

INTERFACE GET_NPROMA
  MODULE PROCEDURE :: GET_NPROMA_1, GET_NPROMA_2, GET_NPROMA_3
END INTERFACE

INTERFACE GET_NBLK
  MODULE PROCEDURE :: GET_NBLK_1, GET_NBLK_2, GET_NBLK_3
END INTERFACE

INTERFACE GET_NSPEC2
  MODULE PROCEDURE :: GET_NSPEC2_1, GET_NSPEC2_2, GET_NSPEC2_3
END INTERFACE

CONTAINS

SUBROUTINE COPY_NAME(YLFV, NAME)
  CHARACTER(LEN=*) :: NAME
  TYPE(FIELD_VIEW), INTENT(IN) :: YLFV
  CHARACTER(LEN=1), POINTER :: NAME_FPTR(:)
  INTEGER :: I
  CALL C_F_POINTER(YLFV%NAME, NAME_FPTR, [YLFV%NAME_SIZE])
  IF (LEN(NAME) < YLFV%NAME_SIZE) THEN
    CALL ABOR1("COPY_NAME FAILURE: NAME length is smaller than NAME_SIZE")
  ENDIF
  DO I = 1, YLFV%NAME_SIZE
    NAME(I:I) = NAME_FPTR(I)
  ENDDO
  DO I = YLFV%NAME_SIZE + 1, LEN(NAME)
    NAME(I:I) = " "
  ENDDO
END SUBROUTINE

SUBROUTINE GET_DATA_PTR_1RB(YLFV, PTR)
  TYPE(FIELD_VIEW), INTENT(IN) :: YLFV
  REAL(JPRB), POINTER :: PTR(:)
  IF (YLFV%RANK /= 1) THEN
    CALL ABOR1("GET_DATA_PTR_1RB FAILURE: RANK MUST BE 1")
  ENDIF
  IF (YLFV%STRIDES(1) == 1) THEN
    CALL C_F_POINTER(YLFV%DATA, PTR, YLFV%EXTENTS(1:1))
  ELSE
    BLOCK
      REAL(JPRB), POINTER :: PTR_2D(:,:)
      INTEGER(C_INT) :: EXTENTS(2)
      EXTENTS(1) = YLFV%STRIDES(1)
      EXTENTS(2) = YLFV%EXTENTS(1)
      CALL C_F_POINTER(YLFV%DATA, PTR_2D, EXTENTS(1:2))
      PTR => PTR_2D(1, 1:YLFV%EXTENTS(1))
    END BLOCK
  ENDIF
END SUBROUTINE

SUBROUTINE GET_DATA_PTR_2RB(YLFV, PTR)
  TYPE(FIELD_VIEW), INTENT(IN) :: YLFV
  REAL(JPRB),     POINTER :: PTR(:,:)
  INTEGER(C_INT) :: EXTENTS(2), JDIM
  IF (YLFV%RANK /= 2) THEN
    CALL ABOR1("GET_DATA_PTR_2RB FAILURE: RANK MUST BE 2")
  ENDIF
  DO JDIM=1,YLFV%RANK-1
    EXTENTS(JDIM) = YLFV%STRIDES(JDIM+1)/YLFV%STRIDES(JDIM)
  ENDDO
  EXTENTS(YLFV%RANK) = YLFV%EXTENTS(YLFV%RANK)
  CALL C_F_POINTER(YLFV%DATA, PTR, EXTENTS)
  PTR => PTR(1:YLFV%EXTENTS(1), 1:YLFV%EXTENTS(2))
END SUBROUTINE

SUBROUTINE GET_DATA_PTR_3RB(YLFV, PTR)
  TYPE(FIELD_VIEW), INTENT(IN) :: YLFV
  REAL(JPRB),     POINTER :: PTR(:,:,:)
  INTEGER(C_INT) :: EXTENTS(3), JDIM
  IF (YLFV%RANK /= 3) THEN
    CALL ABOR1("GET_DATA_PTR_3RB FAILURE: RANK MUST BE 3")
  ENDIF
  DO JDIM=1,YLFV%RANK-1
    EXTENTS(JDIM) = YLFV%STRIDES(JDIM+1)/YLFV%STRIDES(JDIM)
  ENDDO
  EXTENTS(YLFV%RANK) = YLFV%EXTENTS(YLFV%RANK)
  CALL C_F_POINTER(YLFV%DATA, PTR, EXTENTS)
  PTR => PTR(1:YLFV%EXTENTS(1), 1:YLFV%EXTENTS(2), 1:YLFV%EXTENTS(3))
END SUBROUTINE

SUBROUTINE GET_DATA_PTR_4RB(YLFV, PTR)
  TYPE(FIELD_VIEW), INTENT(IN) :: YLFV
  REAL(JPRB),     POINTER :: PTR(:,:,:,:)
  INTEGER(C_INT) :: EXTENTS(4), JDIM
  IF (YLFV%RANK /= 4) THEN
    CALL ABOR1("GET_DATA_PTR_4RB FAILURE: RANK MUST BE 4")
  ENDIF
  DO JDIM=1,YLFV%RANK-1
    EXTENTS(JDIM) = YLFV%STRIDES(JDIM+1)/YLFV%STRIDES(JDIM)
  ENDDO
  EXTENTS(YLFV%RANK) = YLFV%EXTENTS(YLFV%RANK)
  CALL C_F_POINTER(YLFV%DATA, PTR, EXTENTS)
  PTR => PTR(1:YLFV%EXTENTS(1), 1:YLFV%EXTENTS(2), 1:YLFV%EXTENTS(3), 1:YLFV%EXTENTS(4))
END SUBROUTINE

SUBROUTINE GET_IVSET(YLFV, IVSET)
  TYPE(FIELD_VIEW), INTENT(IN) :: YLFV
  INTEGER(KIND=JPIM), POINTER :: IVSET(:)
  CALL C_F_POINTER(YLFV%IVSET, IVSET, [YLFV%IVSET_SIZE])
END SUBROUTINE


FUNCTION GET_NPROMA_1(LIST) RESULT(NPROMA)
  TYPE(FIELD_VIEW), INTENT(IN) :: LIST(:)
  INTEGER(C_INT) :: NPROMA
  INTEGER :: I
  NPROMA = 0
  DO I = 1, SIZE(LIST)
    IF (LIST(I)%RANK == 1) THEN
      NPROMA = MAX(NPROMA, 1)
    ELSE
      NPROMA = MAX(NPROMA, LIST(I)%EXTENTS(1))
    ENDIF
  ENDDO
END FUNCTION

FUNCTION GET_NPROMA_2(LIST1, LIST2) RESULT(NPROMA)
  TYPE(FIELD_VIEW), INTENT(IN) :: LIST1(:), LIST2(:)
  INTEGER(C_INT) :: NPROMA
  NPROMA = 0
  NPROMA = MAX(NPROMA, GET_NPROMA_1(LIST1))
  NPROMA = MAX(NPROMA, GET_NPROMA_1(LIST2))
END FUNCTION 

FUNCTION GET_NPROMA_3(LIST1, LIST2, LIST3) RESULT(NPROMA)
  TYPE(FIELD_VIEW), INTENT(IN) :: LIST1(:), LIST2(:), LIST3(:)
  INTEGER(C_INT) :: NPROMA
  NPROMA = 0
  NPROMA = MAX(NPROMA, GET_NPROMA_1(LIST1))
  NPROMA = MAX(NPROMA, GET_NPROMA_1(LIST2))
  NPROMA = MAX(NPROMA, GET_NPROMA_1(LIST3))
END FUNCTION 

FUNCTION GET_NBLK_1(LIST) RESULT(NBLK)
  TYPE(FIELD_VIEW), INTENT(IN) :: LIST(:)
  INTEGER(C_INT) :: NBLK
  INTEGER :: I
  NBLK = 0
  DO I = 1, SIZE(LIST)
    IF (LIST(I)%RANK == 1) THEN
      NBLK = MAX(NBLK, 1)
    ELSE
      NBLK = MAX(NBLK, LIST(I)%EXTENTS(LIST(I)%RANK))
    ENDIF
  ENDDO
END FUNCTION

FUNCTION GET_NBLK_2(LIST1, LIST2) RESULT(NBLK)
  TYPE(FIELD_VIEW), INTENT(IN) :: LIST1(:), LIST2(:)
  INTEGER(C_INT) :: NBLK
  NBLK = 0
  NBLK = MAX(NBLK, GET_NBLK_1(LIST1))
  NBLK = MAX(NBLK, GET_NBLK_1(LIST2))
END FUNCTION 

FUNCTION GET_NBLK_3(LIST1, LIST2, LIST3) RESULT(NBLK)
  TYPE(FIELD_VIEW), INTENT(IN) :: LIST1(:), LIST2(:), LIST3(:)
  INTEGER(C_INT) :: NBLK
  NBLK = 0
  NBLK = MAX(NBLK, GET_NBLK_1(LIST1))
  NBLK = MAX(NBLK, GET_NBLK_1(LIST2))
  NBLK = MAX(NBLK, GET_NBLK_1(LIST3))
END FUNCTION 

FUNCTION GET_NFLD_1(LIST) RESULT(NFLD)
  TYPE(FIELD_VIEW), INTENT(IN) :: LIST(:)
  INTEGER(C_INT) :: NFLD
  NFLD = 0
  CALL PROCESS_LIST(LIST)
CONTAINS
  SUBROUTINE PROCESS_LIST(LIST)
    TYPE(FIELD_VIEW), INTENT(IN) :: LIST(:)
    INTEGER :: I
    DO I = 1, SIZE(LIST)
      IF (LIST(I)%RANK <= 2) THEN
        NFLD = NFLD + 1
      ELSE IF (LIST(I)%RANK == 3) THEN
        NFLD = NFLD + LIST(I)%EXTENTS(2)
      ELSE IF (LIST(I)%RANK == 4) THEN
        NFLD = NFLD + LIST(I)%EXTENTS(2) * LIST(I)%EXTENTS(3)
      ELSE
        CALL ABOR1("GET_NFLD FAILURE: RANK MUST BE <= 4") 
      ENDIF
    ENDDO
  END SUBROUTINE
END FUNCTION

FUNCTION GET_NFLD_3(LIST1, LIST2, LIST3) RESULT(NFLD)
  TYPE(FIELD_VIEW), INTENT(IN) :: LIST1(:), LIST2(:), LIST3(:)
  INTEGER(C_INT) :: NFLD
  NFLD = 0
  CALL PROCESS_LIST(LIST1)
  CALL PROCESS_LIST(LIST2)
  CALL PROCESS_LIST(LIST3)
CONTAINS
  SUBROUTINE PROCESS_LIST(LIST)
    TYPE(FIELD_VIEW), INTENT(IN) :: LIST(:)
    INTEGER :: I
    DO I = 1, SIZE(LIST)
      IF (LIST(I)%RANK <= 2) THEN
        NFLD = NFLD + 1
      ELSE IF (LIST(I)%RANK == 3) THEN
        NFLD = NFLD + LIST(I)%EXTENTS(2)
      ELSE IF (LIST(I)%RANK == 4) THEN
        NFLD = NFLD + LIST(I)%EXTENTS(2) * LIST(I)%EXTENTS(3)
      ELSE
        CALL ABOR1("GET_NFLD FAILURE: RANK MUST BE <= 4") 
      ENDIF
    ENDDO
  END SUBROUTINE
END FUNCTION


FUNCTION GET_NSPEC2_1(LIST) RESULT(NSPEC2)
  ! Return the maximum spectral dimension (NSPEC2) found in LIST.
  ! Spectral fields follow these shape conventions:
  !   rank 1: (NSPEC)                  -> NSPEC2 = EXTENTS(1)
  !   rank 2: (NLEVS, NSPEC)           -> NSPEC2 = EXTENTS(2)
  !   rank 3: (NLEVS, NSPEC, NFIELDS)  -> NSPEC2 = EXTENTS(2)
  TYPE(FIELD_VIEW), INTENT(IN) :: LIST(:)
  INTEGER(C_INT) :: NSPEC2
  INTEGER :: I
  NSPEC2 = 0
  DO I = 1, SIZE(LIST)
    IF (LIST(I)%RANK == 1) THEN
      NSPEC2 = MAX(NSPEC2, LIST(I)%EXTENTS(1))
    ELSE IF (LIST(I)%RANK == 2) THEN
      NSPEC2 = MAX(NSPEC2, LIST(I)%EXTENTS(2))
    ELSE IF (LIST(I)%RANK == 3) THEN
      NSPEC2 = MAX(NSPEC2, LIST(I)%EXTENTS(2))
    ELSE
      CALL ABOR1("GET_NSPEC2 FAILURE: RANK MUST BE <= 3")
    ENDIF
  ENDDO
END FUNCTION

FUNCTION GET_NSPEC2_2(LIST1, LIST2) RESULT(NSPEC2)
  TYPE(FIELD_VIEW), INTENT(IN) :: LIST1(:), LIST2(:)
  INTEGER(C_INT) :: NSPEC2
  INTEGER :: I
  NSPEC2 = 0
  NSPEC2 = MAX(NSPEC2, GET_NSPEC2_1(LIST1))
  NSPEC2 = MAX(NSPEC2, GET_NSPEC2_1(LIST2))
END FUNCTION

FUNCTION GET_NSPEC2_3(LIST1, LIST2, LIST3) RESULT(NSPEC2)
  TYPE(FIELD_VIEW), INTENT(IN) :: LIST1(:), LIST2(:), LIST3(:)
  INTEGER(C_INT) :: NSPEC2
  INTEGER :: I
  NSPEC2 = 0
  NSPEC2 = MAX(NSPEC2, GET_NSPEC2_1(LIST1))
  NSPEC2 = MAX(NSPEC2, GET_NSPEC2_1(LIST2))
  NSPEC2 = MAX(NSPEC2, GET_NSPEC2_1(LIST3))
END FUNCTION


END MODULE ECTRANS_FIELD_VIEW_MOD

