! (C) Copyright 2026- ECMWF.
! (C) Copyright 2026- Meteo-France.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.

PROGRAM TEST_FIELD_VIEW

USE, INTRINSIC :: ISO_C_BINDING, ONLY: C_FLOAT, C_DOUBLE, C_INT, C_ASSOCIATED
USE ECTRANS_FIELD_VIEW_MOD, ONLY: FIELD_VIEW, FIELD_VIEW_INIT, FIELD_VIEW_ACCESS_TYPE, FIELD_VIEW_ACCESS, &
                              & FIELD_VIEW_SET_ACCESS, FIELD_VIEW_ADD_ACCESS, &
                              & FIELD_VIEW_HAS_ACCESS, FIELD_VIEW_CLEAR_ACCESS, &
                              & FIELD_VIEW_SET_DATA_PTR, FIELD_VIEW_GET_DATA_PTR, &
                              & FIELD_VIEW_GET_EXTENT, FIELD_VIEW_GET_STRIDE, &
                              & FIELD_VIEW_GET_DIM_ROLE, FIELD_VIEW_GET_EXTENT_BY_ROLE, &
                              & FIELD_VIEW_DIM_ROLE, FIELD_VIEW_INDEXING, &
                              & FIELD_VIEW_SET_IVSET_PTR, FIELD_VIEW_GET_IVSET_PTR, &
                              & FIELD_VIEW_SET_IVSET_DIM, FIELD_VIEW_GET_IVSET_DIM, &
                              & FIELD_VIEW_SET_NAME, FIELD_VIEW_GET_NAME_PTR

IMPLICIT NONE

CALL TEST_FIELD_VIEW_INIT()
CALL TEST_FIELD_VIEW_ACCESS()
CALL TEST_FIELD_VIEW_DATA_PTR()
CALL TEST_FIELD_VIEW_DIM_ROLE()
CALL TEST_FIELD_VIEW_IVSET()
CALL TEST_FIELD_VIEW_NAME()

CONTAINS

SUBROUTINE TEST_FIELD_VIEW_INIT()
  TYPE(FIELD_VIEW) :: YLFV

  CALL FIELD_VIEW_INIT(YLFV)
  IF (C_ASSOCIATED(YLFV%DATA)) ERROR STOP __LINE__
  IF (YLFV%ACCESS /= FIELD_VIEW_ACCESS%UNKNOWN) ERROR STOP __LINE__
  IF (YLFV%KIND /= 0) ERROR STOP __LINE__
  IF (YLFV%RANK /= 0) ERROR STOP __LINE__
  IF (ANY(YLFV%EXTENTS /= 0)) ERROR STOP __LINE__
  IF (ANY(YLFV%STRIDES /= 0)) ERROR STOP __LINE__
  IF (C_ASSOCIATED(YLFV%IVSET)) ERROR STOP __LINE__
  IF (YLFV%IVSET_SIZE /= 0) ERROR STOP __LINE__
  IF (YLFV%IVSET_DIM /= -1) ERROR STOP __LINE__
  IF (YLFV%IVSET_BASE /= 1) ERROR STOP __LINE__
  IF (C_ASSOCIATED(YLFV%NAME)) ERROR STOP __LINE__
  IF (YLFV%NAME_SIZE /= 0) ERROR STOP __LINE__
  IF (YLFV%INDEXING /= FIELD_VIEW_INDEXING%UNKNOWN) ERROR STOP __LINE__
END SUBROUTINE

SUBROUTINE TEST_FIELD_VIEW_ACCESS()
  TYPE(FIELD_VIEW) :: YLFV
  TYPE(FIELD_VIEW_ACCESS_TYPE) :: ACCESS
  INTEGER(C_INT) :: EXPECTED

  CALL FIELD_VIEW_CLEAR_ACCESS(YLFV)
  IF (YLFV%ACCESS /= FIELD_VIEW_ACCESS%UNKNOWN) ERROR STOP __LINE__
  IF (.NOT. FIELD_VIEW_HAS_ACCESS(YLFV, FIELD_VIEW_ACCESS%UNKNOWN)) ERROR STOP __LINE__

  ACCESS = FIELD_VIEW_ACCESS
  IF (ACCESS%UNKNOWN /= 0) ERROR STOP __LINE__
  IF (IAND(ACCESS%HOST, ACCESS%DEVICE) /= 0) ERROR STOP __LINE__

  CALL FIELD_VIEW_SET_ACCESS(YLFV, ACCESS%HOST)
  IF (.NOT. FIELD_VIEW_HAS_ACCESS(YLFV, ACCESS%HOST)) ERROR STOP __LINE__
  IF (FIELD_VIEW_HAS_ACCESS(YLFV, ACCESS%DEVICE)) ERROR STOP __LINE__

  CALL FIELD_VIEW_ADD_ACCESS(YLFV, ACCESS%READONLY)
  IF (.NOT. FIELD_VIEW_HAS_ACCESS(YLFV, ACCESS%HOST, ACCESS%READONLY)) ERROR STOP __LINE__

  CALL FIELD_VIEW_SET_ACCESS(YLFV, ACCESS%DEVICE, ACCESS%READONLY)
  IF (.NOT. FIELD_VIEW_HAS_ACCESS(YLFV, ACCESS%DEVICE, ACCESS%READONLY)) ERROR STOP __LINE__
  IF (FIELD_VIEW_HAS_ACCESS(YLFV, ACCESS%HOST, ACCESS%READONLY)) ERROR STOP __LINE__

  CALL FIELD_VIEW_ADD_ACCESS(YLFV, ACCESS%HOST, ACCESS%DEVICE, ACCESS%READONLY)
  IF (.NOT. FIELD_VIEW_HAS_ACCESS(YLFV, ACCESS%HOST, ACCESS%DEVICE, ACCESS%READONLY)) ERROR STOP __LINE__

  EXPECTED = IOR(ACCESS%HOST, IOR(ACCESS%DEVICE, ACCESS%READONLY))
  IF (YLFV%ACCESS /= EXPECTED) ERROR STOP __LINE__
  IF (.NOT. FIELD_VIEW_HAS_ACCESS(YLFV, EXPECTED)) ERROR STOP __LINE__

  CALL FIELD_VIEW_SET_ACCESS(YLFV, ACCESS%READONLY)
  IF (YLFV%ACCESS /= ACCESS%READONLY) ERROR STOP __LINE__
  CALL FIELD_VIEW_ADD_ACCESS(YLFV, ACCESS%HOST, ACCESS%DEVICE)
  IF (YLFV%ACCESS /= EXPECTED) ERROR STOP __LINE__

  CALL FIELD_VIEW_SET_ACCESS(YLFV, ACCESS%DEVICE, ACCESS%READONLY, ACCESS%UNKNOWN)
  IF (YLFV%ACCESS /= IOR(ACCESS%DEVICE, ACCESS%READONLY)) ERROR STOP __LINE__

  CALL FIELD_VIEW_CLEAR_ACCESS(YLFV)
  IF (YLFV%ACCESS /= ACCESS%UNKNOWN) ERROR STOP __LINE__
  IF (FIELD_VIEW_HAS_ACCESS(YLFV, ACCESS%HOST)) ERROR STOP __LINE__
  IF (FIELD_VIEW_HAS_ACCESS(YLFV, ACCESS%DEVICE)) ERROR STOP __LINE__
  IF (FIELD_VIEW_HAS_ACCESS(YLFV, ACCESS%READONLY)) ERROR STOP __LINE__
END SUBROUTINE

SUBROUTINE TEST_FIELD_VIEW_DATA_PTR()
  TYPE(FIELD_VIEW) :: YLFV
  REAL(C_FLOAT), TARGET :: DATA_SP(2,3)
  REAL(C_FLOAT), POINTER :: PTR_SP(:,:), RESULT_SP(:,:)
  REAL(C_DOUBLE), TARGET :: DATA_DP(2,3,4)
  REAL(C_DOUBLE), POINTER :: PTR_DP(:,:,:), RESULT_DP(:,:,:)

  DATA_SP = RESHAPE([1._C_FLOAT, 2._C_FLOAT, 3._C_FLOAT, 4._C_FLOAT, 5._C_FLOAT, 6._C_FLOAT], SHAPE(DATA_SP))
  PTR_SP => DATA_SP
  CALL FIELD_VIEW_SET_DATA_PTR(YLFV, PTR_SP)
  IF (YLFV%RANK /= 2) ERROR STOP __LINE__
  IF (YLFV%KIND /= C_FLOAT) ERROR STOP __LINE__
  IF (ANY(YLFV%EXTENTS(1:2) /= [3, 2])) ERROR STOP __LINE__
  IF (FIELD_VIEW_GET_EXTENT(YLFV, 1) /= 2) ERROR STOP __LINE__
  IF (FIELD_VIEW_GET_EXTENT(YLFV, 2) /= 3) ERROR STOP __LINE__
  IF (FIELD_VIEW_GET_STRIDE(YLFV, 1) /= 1) ERROR STOP __LINE__
  IF (FIELD_VIEW_GET_STRIDE(YLFV, 2) /= 2) ERROR STOP __LINE__
  CALL FIELD_VIEW_GET_DATA_PTR(YLFV, RESULT_SP)
  IF (.NOT. ASSOCIATED(RESULT_SP)) ERROR STOP __LINE__
  IF (ANY(SHAPE(RESULT_SP) /= SHAPE(DATA_SP))) ERROR STOP __LINE__
  IF (ANY(RESULT_SP /= DATA_SP)) ERROR STOP __LINE__
  RESULT_SP(2,3) = 42._C_FLOAT
  IF (DATA_SP(2,3) /= 42._C_FLOAT) ERROR STOP __LINE__

  DATA_DP = 7._C_DOUBLE
  PTR_DP => DATA_DP
  CALL FIELD_VIEW_SET_DATA_PTR(YLFV, PTR_DP)
  IF (YLFV%RANK /= 3) ERROR STOP __LINE__
  IF (YLFV%KIND /= C_DOUBLE) ERROR STOP __LINE__
  IF (ANY(YLFV%EXTENTS(1:3) /= [4, 3, 2])) ERROR STOP __LINE__
  IF (FIELD_VIEW_GET_STRIDE(YLFV, 3) /= 6) ERROR STOP __LINE__
  CALL FIELD_VIEW_GET_DATA_PTR(YLFV, RESULT_DP)
  IF (.NOT. ASSOCIATED(RESULT_DP)) ERROR STOP __LINE__
  IF (ANY(SHAPE(RESULT_DP) /= SHAPE(DATA_DP))) ERROR STOP __LINE__
  IF (ANY(RESULT_DP /= DATA_DP)) ERROR STOP __LINE__
END SUBROUTINE

SUBROUTINE TEST_FIELD_VIEW_DIM_ROLE()
  TYPE(FIELD_VIEW) :: YLFV

  YLFV%RANK = 3
  YLFV%INDEXING = FIELD_VIEW_INDEXING%NPROMA_LEVEL_BLOCK
  IF (FIELD_VIEW_GET_DIM_ROLE(YLFV, 1) /= FIELD_VIEW_DIM_ROLE%NPROMA) ERROR STOP __LINE__
  IF (FIELD_VIEW_GET_DIM_ROLE(YLFV, 2) /= FIELD_VIEW_DIM_ROLE%LEVEL)  ERROR STOP __LINE__
  IF (FIELD_VIEW_GET_DIM_ROLE(YLFV, 3) /= FIELD_VIEW_DIM_ROLE%BLOCK)  ERROR STOP __LINE__
  YLFV%EXTENTS = [4, 3, 2, -1] ! C-order
  IF (FIELD_VIEW_GET_EXTENT_BY_ROLE(YLFV, FIELD_VIEW_DIM_ROLE%NPROMA) /= 2) ERROR STOP __LINE__
  IF (FIELD_VIEW_GET_EXTENT_BY_ROLE(YLFV, FIELD_VIEW_DIM_ROLE%LEVEL)  /= 3) ERROR STOP __LINE__
  IF (FIELD_VIEW_GET_EXTENT_BY_ROLE(YLFV, FIELD_VIEW_DIM_ROLE%BLOCK)  /= 4) ERROR STOP __LINE__
  IF (FIELD_VIEW_GET_EXTENT_BY_ROLE(YLFV, FIELD_VIEW_DIM_ROLE%FIELD)  /= 0) ERROR STOP __LINE__
END SUBROUTINE

SUBROUTINE TEST_FIELD_VIEW_IVSET()
  TYPE(FIELD_VIEW) :: YLFV
  INTEGER(C_INT), TARGET :: IVSET(3) = [1_C_INT, 2_C_INT, 1_C_INT]
  INTEGER(C_INT), POINTER :: IVSET_PTR(:)
  INTEGER :: IVSET_DIM

  YLFV%RANK = 2
  CALL FIELD_VIEW_SET_IVSET_PTR(YLFV, IVSET)
  IF (.NOT. C_ASSOCIATED(YLFV%IVSET)) ERROR STOP __LINE__
  IF (YLFV%IVSET_SIZE /= SIZE(IVSET)) ERROR STOP __LINE__
  IF (YLFV%IVSET_BASE /= 1) ERROR STOP __LINE__
  CALL FIELD_VIEW_SET_IVSET_DIM(YLFV, 2)
  CALL FIELD_VIEW_GET_IVSET_DIM(YLFV, IVSET_DIM)
  IF (IVSET_DIM /= 2) ERROR STOP __LINE__
  IF (YLFV%IVSET_BASE /= 1) ERROR STOP __LINE__
  CALL FIELD_VIEW_GET_IVSET_PTR(YLFV, IVSET_PTR)
  IF (.NOT. ASSOCIATED(IVSET_PTR)) ERROR STOP __LINE__
  IF (ANY(IVSET_PTR /= IVSET)) ERROR STOP __LINE__

  CALL FIELD_VIEW_SET_IVSET_PTR(YLFV, IVSET_BASE=0_C_INT)
  IF (C_ASSOCIATED(YLFV%IVSET)) ERROR STOP __LINE__
  IF (YLFV%IVSET_SIZE /= 0) ERROR STOP __LINE__
  IF (YLFV%IVSET_BASE /= 0) ERROR STOP __LINE__
  CALL FIELD_VIEW_GET_IVSET_PTR(YLFV, IVSET_PTR)
  IF (ASSOCIATED(IVSET_PTR)) ERROR STOP __LINE__

  CALL FIELD_VIEW_SET_IVSET_PTR(YLFV)
  IF (C_ASSOCIATED(YLFV%IVSET)) ERROR STOP __LINE__
  IF (YLFV%IVSET_SIZE /= 0) ERROR STOP __LINE__
  IF (YLFV%IVSET_BASE /= 1) ERROR STOP __LINE__
END SUBROUTINE

SUBROUTINE TEST_FIELD_VIEW_NAME()
  TYPE(FIELD_VIEW) :: YLFV
  CHARACTER(LEN=16), TARGET :: NAME = "temperature"
  CHARACTER(LEN=:), POINTER :: NAME_PTR

  CALL FIELD_VIEW_INIT(YLFV)
  CALL FIELD_VIEW_SET_NAME(YLFV, NAME)
  IF (YLFV%NAME_SIZE /= LEN_TRIM(NAME)) ERROR STOP __LINE__
  CALL FIELD_VIEW_GET_NAME_PTR(YLFV, NAME_PTR)
  IF (.NOT. ASSOCIATED(NAME_PTR)) ERROR STOP __LINE__
  IF (LEN(NAME_PTR) /= LEN_TRIM(NAME)) ERROR STOP __LINE__
  IF (NAME_PTR /= TRIM(NAME)) ERROR STOP __LINE__
END SUBROUTINE

END PROGRAM TEST_FIELD_VIEW
