      SUBROUTINE EUCLID (N,X,Y,PS)
!AUTOPROMOTE
      USE PARKIND1, ONLY : JPIM, JPRB
      USE YOMHOOK , ONLY : LHOOK, DR_HOOK
      USE CONTROL_VECTORS_MOD
!
      IMPLICIT NONE
!
      INTEGER(KIND=JPIM) :: N
      REAL(KIND=JPRB) :: PS
      TYPE (CONTROL_VECTOR) :: X
      TYPE (CONTROL_VECTOR) :: Y
!
      REAL(KIND=JPRB) :: ZHOOK_HANDLE
      IF (LHOOK) CALL DR_HOOK('EUCLID',0,ZHOOK_HANDLE)
      PS = DOT_PRODUCT(X,Y)
      IF (LHOOK) CALL DR_HOOK('EUCLID',1,ZHOOK_HANDLE)
      ENDSUBROUTINE EUCLID
