      SUBROUTINE EUCLID_1DV (N,X,Y,PS)
!AUTOPROMOTE
      USE PARKIND1, ONLY : JPIM, JPRB
      USE YOMHOOK , ONLY : LHOOK, DR_HOOK

      IMPLICIT NONE

      INTEGER(KIND=JPIM) :: N
      REAL(KIND=JPRB) :: X(N)
      REAL(KIND=JPRB) :: Y(N)
      REAL(KIND=JPRB) :: PS
!
      INTEGER(KIND=JPIM) :: I
!
      REAL(KIND=JPRB) :: ZHOOK_HANDLE
      IF (LHOOK) CALL DR_HOOK('EUCLID_1DV',0,ZHOOK_HANDLE)
      PS=0.0_JPRB
      DO 10 I=1,N
   10 PS=PS+REAL(X(I),KIND=JPRB)*REAL(Y(I),KIND=JPRB)
      IF (LHOOK) CALL DR_HOOK('EUCLID_1DV',1,ZHOOK_HANDLE)
      ENDSUBROUTINE EUCLID_1DV
