INTERFACE
SUBROUTINE FPBIPERE(KDLUX,KDGUX,KDLON,KDGL,KNUBI,KD1,PGPBI,KDADD,LDZON,&
& LDBOYD,KDBOYD,PLBOYD,PBIPOUT)
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KNUBI
INTEGER(KIND=JPIM),INTENT(IN) :: KD1
INTEGER(KIND=JPIM),INTENT(IN) :: KDLUX
INTEGER(KIND=JPIM),INTENT(IN) :: KDGUX
INTEGER(KIND=JPIM),INTENT(IN) :: KDLON
INTEGER(KIND=JPIM),INTENT(IN) :: KDGL
INTEGER(KIND=JPIM),INTENT(IN) :: KDADD
REAL(KIND=JPRB) ,INTENT(INOUT):: PGPBI(KD1,KNUBI)
LOGICAL, OPTIONAL ,INTENT(IN) :: LDZON
LOGICAL, OPTIONAL ,INTENT(IN) :: LDBOYD
INTEGER(KIND=JPIM), INTENT(IN), OPTIONAL :: KDBOYD(6)
REAL(KIND=JPRB)   , INTENT(IN), OPTIONAL :: PLBOYD
REAL(KIND=JPRB)   ,INTENT(OUT), OPTIONAL :: PBIPOUT(:,:)
END SUBROUTINE FPBIPERE
END INTERFACE
