MODULE TPMALD_GEO

! Module containing data describing plane projection grid.

USE PARKIND1  ,ONLY : JPIM     ,JPRB

IMPLICIT NONE

SAVE

TYPE ALDGEO_TYPE

! GEOGRAPHY 
  
REAL(KIND=JPRB) :: EYWN       ! Y-reso 
REAL(KIND=JPRB) :: EXWN       ! X-reso
END TYPE ALDGEO_TYPE

TYPE(ALDGEO_TYPE),ALLOCATABLE,TARGET :: ALDGEO_RESOL(:)
TYPE(ALDGEO_TYPE),POINTER     :: GALD

END MODULE TPMALD_GEO
