! (C) Copyright 2026- ECMWF.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.

MODULE DIR_TRANS_FIELD_VIEW_TEST_SUITE

USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY: INT32
USE PARKIND1, ONLY: JPIM, JPRB, JPRD
USE MPL_MODULE, ONLY: MPL_INIT, MPL_NPROC, MPL_MYRANK, MPL_ALLREDUCE, MPL_END
USE ECTRANS_FIELD_VIEW_MOD, ONLY: FIELD_VIEW, FIELD_VIEW_INIT, FIELD_VIEW_SET_DATA_PTR, &
  & FIELD_VIEW_SET_ACCESS, FIELD_VIEW_SET_NAME, FIELD_VIEW_INDEXING, FIELD_VIEW_ACCESS

IMPLICIT NONE

#include "setup_trans0.h"
#include "setup_trans.h"
#include "trans_inq.h"
#include "dist_grid.h"
#include "dir_trans_field_view.h"
#include "trans_end.h"

INTEGER(KIND=JPIM), PARAMETER :: JPTRUNCATION = 79
INTEGER(KIND=JPIM), PARAMETER :: JPNGDL = 2 * (JPTRUNCATION + 1)
REAL(KIND=JPRB), PARAMETER :: PPTOLERANCE = 100.0_JPRB * EPSILON(1.0_JPRB)
INTEGER(KIND=JPIM), PARAMETER :: JPPROMA = 16
REAL(KIND=JPRD), PARAMETER :: PPEARTH_RADIUS = 6371229.0_JPRD
INTEGER(KIND=INT32), PARAMETER :: IRESOL_1 = 1_INT32
LOGICAL, PARAMETER :: INTENT_IN = .TRUE.
LOGICAL, PARAMETER :: INTENT_OUT = .FALSE.

CHARACTER(LEN=32), TARGET, SAVE :: GRID_SCALAR_NAME = "grid scalar"
CHARACTER(LEN=32), TARGET, SAVE :: GRID_U_NAME = "grid u"
CHARACTER(LEN=32), TARGET, SAVE :: GRID_V_NAME = "grid v"
CHARACTER(LEN=32), TARGET, SAVE :: SPEC_SCALAR_NAME = "spectral scalar"
CHARACTER(LEN=32), TARGET, SAVE :: SPEC_VOR_NAME = "spectral vorticity"
CHARACTER(LEN=32), TARGET, SAVE :: SPEC_DIV_NAME = "spectral divergence"

TYPE(FIELD_VIEW), SAVE :: EMPTY_FIELD_VIEW_LIST(0)

LOGICAL :: LUSE_MPI

INTERFACE MAKE_FIELD_VIEW
  MODULE PROCEDURE :: MAKE_FIELD_VIEW_2, MAKE_FIELD_VIEW_3, MAKE_FIELD_VIEW_4
END INTERFACE

CONTAINS

ELEMENTAL LOGICAL FUNCTION APPROX_EQ(PA, PB, PTOL) RESULT(KRET)
  REAL(KIND=JPRB), INTENT(IN) :: PA
  REAL(KIND=JPRB), INTENT(IN) :: PB
  REAL(KIND=JPRB), INTENT(IN), OPTIONAL :: PTOL

  IF (PRESENT(PTOL)) THEN
    KRET = ABS(PA - PB) < PTOL
  ELSE
    KRET = ABS(PA - PB) < PPTOLERANCE
  END IF
END FUNCTION APPROX_EQ

FUNCTION GET_INPUT_FIELD(KMY_PROC, KGPTOTG, KGPBLKS, KFIELDS) RESULT(PGP)
  INTEGER(KIND=JPIM), INTENT(IN) :: KMY_PROC
  INTEGER(KIND=JPIM), INTENT(IN) :: KGPTOTG
  INTEGER(KIND=JPIM), INTENT(IN) :: KGPBLKS
  INTEGER(KIND=JPIM), INTENT(IN) :: KFIELDS

  REAL(KIND=JPRB), ALLOCATABLE :: ZGPG(:,:), PGP(:,:,:)
  INTEGER(KIND=JPIM) :: I

  IF (KMY_PROC == 1) THEN
    ALLOCATE(ZGPG(KGPTOTG,KFIELDS))
    ZGPG(:,:) = 1.0_JPRB
  ENDIF

  ALLOCATE(PGP(JPPROMA,KFIELDS,KGPBLKS))

  IF (KMY_PROC == 1) THEN
    CALL DIST_GRID(PGPG=ZGPG, KFDISTG=KFIELDS, KFROM=[(1, I = 1, KFIELDS)], PGP=PGP, KPROMA=JPPROMA)
  ELSE
    CALL DIST_GRID(KFDISTG=KFIELDS, KFROM=[(1, I = 1, KFIELDS)], PGP=PGP, KPROMA=JPPROMA)
  ENDIF

  IF (KMY_PROC == 1) DEALLOCATE(ZGPG)
END FUNCTION GET_INPUT_FIELD

FUNCTION ROTATIONAL_WIND(KGPBLKS, K_REGIONS_NS, K_REGIONS_EW) RESULT(PGP)
  INTEGER(KIND=JPIM), INTENT(IN) :: KGPBLKS
  INTEGER(KIND=JPIM), INTENT(IN) :: K_REGIONS_NS
  INTEGER(KIND=JPIM), INTENT(IN) :: K_REGIONS_EW

  REAL(KIND=JPRB), ALLOCATABLE :: PGP(:,:,:)
  INTEGER(KIND=JPIM) :: IPTRFLOFF, IMY_REGION_NS, IMY_REGION_EW
  INTEGER(KIND=JPIM), DIMENSION(K_REGIONS_NS) :: IFRSTLAT, ILSTLAT
  REAL(KIND=JPRD) :: ZMU(JPNGDL)
  INTEGER(KIND=JPIM), DIMENSION(JPNGDL + K_REGIONS_NS - 1, K_REGIONS_EW) :: NSTA, NONL
  INTEGER(KIND=JPIM) :: ILAT, IFIRSTLAT, ILASTLAT, IBL, JROF, JGLAT, ISTLON, IENDLON, JLON
  REAL(KIND=JPRB) :: ZLAT

  CALL TRANS_INQ(KPTRFLOFF=IPTRFLOFF, KMY_REGION_NS=IMY_REGION_NS, KFRSTLAT=IFRSTLAT, &
    &            KLSTLAT=ILSTLAT, PMU=ZMU, KMY_REGION_EW=IMY_REGION_EW, KSTA=NSTA, KONL=NONL)
  ILAT = IPTRFLOFF
  IFIRSTLAT = IFRSTLAT(IMY_REGION_NS)
  ILASTLAT = ILSTLAT(IMY_REGION_NS)

  ALLOCATE(PGP(JPPROMA, 2, KGPBLKS))

  IBL = 1
  JROF = 1
  DO JGLAT = IFIRSTLAT, ILASTLAT
    ZLAT = ASIN(ZMU(JGLAT))
    ILAT = ILAT + 1
    ISTLON = NSTA(ILAT, IMY_REGION_EW)
    IENDLON = ISTLON - 1 + NONL(ILAT, IMY_REGION_EW)
    DO JLON = ISTLON, IENDLON
      PGP(JROF, 1, IBL) = COS(ZLAT)
      PGP(JROF, 2, IBL) = 0.0_JPRB
      JROF = JROF + 1
      IF (JROF > JPPROMA) THEN
        JROF = 1
        IBL = IBL + 1
      ENDIF
    ENDDO
  ENDDO
END FUNCTION ROTATIONAL_WIND

LOGICAL FUNCTION HAVE_M0_MODE()
  INTEGER :: NUM_MY_ZON_WNS
  INTEGER, ALLOCATABLE :: MY_ZON_WNS(:)

  CALL TRANS_INQ(KNUMP=NUM_MY_ZON_WNS)
  ALLOCATE(MY_ZON_WNS(NUM_MY_ZON_WNS))
  CALL TRANS_INQ(KMYMS=MY_ZON_WNS)
  HAVE_M0_MODE = ANY(MY_ZON_WNS == 0)
END FUNCTION HAVE_M0_MODE

SUBROUTINE SETUP_TEST(KSPEC2, KGPTOTG, KGPTOT, KGPBLKS, KMY_PROC, K_REGIONS_NS, K_REGIONS_EW)
  USE UTIL, ONLY: DETECT_MPIRUN

  INTEGER(KIND=JPIM), INTENT(OUT) :: KSPEC2, KGPTOTG, KGPTOT, KGPBLKS
  INTEGER(KIND=JPIM), INTENT(OUT) :: KMY_PROC, K_REGIONS_NS, K_REGIONS_EW
  INTEGER(KIND=JPIM) :: ILOEN(JPNGDL)
  INTEGER(KIND=JPIM) :: I, IPROC

  LUSE_MPI = DETECT_MPIRUN()
  IF (LUSE_MPI) THEN
    CALL MPL_INIT
    IPROC = MPL_NPROC()
    KMY_PROC = MPL_MYRANK()
  ELSE
    IPROC = 1
    KMY_PROC = 1
  ENDIF

  CALL SETUP_TRANS0(LDMPOFF=.NOT. LUSE_MPI, KPRGPNS=IPROC, KPRGPEW=1, KPRTRW=IPROC, &
    &               K_REGIONS_NS=K_REGIONS_NS, K_REGIONS_EW=K_REGIONS_EW, PRAD=PPEARTH_RADIUS)

  DO I = 1, JPTRUNCATION + 1
    ILOEN(I) = 20 + 4 * I
    ILOEN(JPNGDL - I + 1) = ILOEN(I)
  END DO

  CALL SETUP_TRANS(KSMAX=JPTRUNCATION, KDGL=JPNGDL, KLOEN=ILOEN)
  CALL TRANS_INQ(KSPEC2=KSPEC2, KGPTOTG=KGPTOTG, KGPTOT=KGPTOT)
  KGPBLKS = (KGPTOT - 1) / JPPROMA + 1
END SUBROUTINE SETUP_TEST

SUBROUTINE CLEANUP_TEST
  CALL TRANS_END
  IF (LUSE_MPI) CALL MPL_END(LDMEMINFO=.FALSE.)
END SUBROUTINE CLEANUP_TEST

SUBROUTINE SET_FIELD_VIEW_METADATA(YLFV, INDEXING, NAME, READONLY)
  TYPE(FIELD_VIEW), INTENT(INOUT) :: YLFV
  INTEGER, INTENT(IN) :: INDEXING
  CHARACTER(LEN=*), TARGET, INTENT(IN) :: NAME
  LOGICAL, INTENT(IN) :: READONLY

  YLFV%INDEXING = INDEXING
  CALL FIELD_VIEW_SET_NAME(YLFV, NAME)
  IF (READONLY) THEN
    CALL FIELD_VIEW_SET_ACCESS(YLFV, FIELD_VIEW_ACCESS%HOST, FIELD_VIEW_ACCESS%READONLY)
  ELSE
    CALL FIELD_VIEW_SET_ACCESS(YLFV, FIELD_VIEW_ACCESS%HOST)
  ENDIF
END SUBROUTINE SET_FIELD_VIEW_METADATA

FUNCTION MAKE_FIELD_VIEW_2(DATA, INDEXING, NAME, READONLY) RESULT(YLFV)
  REAL(KIND=JPRB), TARGET, INTENT(INOUT) :: DATA(:,:)
  INTEGER, INTENT(IN) :: INDEXING
  CHARACTER(LEN=*), TARGET, INTENT(IN) :: NAME
  LOGICAL, INTENT(IN) :: READONLY
  TYPE(FIELD_VIEW) :: YLFV
  REAL(KIND=JPRB), POINTER :: PTR(:,:)

  CALL FIELD_VIEW_INIT(YLFV)
  PTR => DATA
  CALL FIELD_VIEW_SET_DATA_PTR(YLFV, PTR)
  CALL SET_FIELD_VIEW_METADATA(YLFV, INDEXING, NAME, READONLY)
END FUNCTION MAKE_FIELD_VIEW_2

FUNCTION MAKE_FIELD_VIEW_3(DATA, INDEXING, NAME, READONLY) RESULT(YLFV)
  REAL(KIND=JPRB), TARGET, INTENT(INOUT) :: DATA(:,:,:)
  INTEGER, INTENT(IN) :: INDEXING
  CHARACTER(LEN=*), TARGET, INTENT(IN) :: NAME
  LOGICAL, INTENT(IN) :: READONLY
  TYPE(FIELD_VIEW) :: YLFV
  REAL(KIND=JPRB), POINTER :: PTR(:,:,:)

  CALL FIELD_VIEW_INIT(YLFV)
  PTR => DATA
  CALL FIELD_VIEW_SET_DATA_PTR(YLFV, PTR)
  CALL SET_FIELD_VIEW_METADATA(YLFV, INDEXING, NAME, READONLY)
END FUNCTION MAKE_FIELD_VIEW_3

FUNCTION MAKE_FIELD_VIEW_4(DATA, INDEXING, NAME, READONLY) RESULT(YLFV)
  REAL(KIND=JPRB), TARGET, INTENT(INOUT) :: DATA(:,:,:,:)
  INTEGER, INTENT(IN) :: INDEXING
  CHARACTER(LEN=*), TARGET, INTENT(IN) :: NAME
  LOGICAL, INTENT(IN) :: READONLY
  TYPE(FIELD_VIEW) :: YLFV
  REAL(KIND=JPRB), POINTER :: PTR(:,:,:,:)

  CALL FIELD_VIEW_INIT(YLFV)
  PTR => DATA
  CALL FIELD_VIEW_SET_DATA_PTR(YLFV, PTR)
  CALL SET_FIELD_VIEW_METADATA(YLFV, INDEXING, NAME, READONLY)
END FUNCTION MAKE_FIELD_VIEW_4

INTEGER FUNCTION ECTRANS_TEST_TRANS_API_DIR_TRANS_FV_CALL_MODE_1_SCALAR_1() RESULT(KRET) &
  & BIND(C, NAME="ectrans_test_trans_api_dir_trans_field_view_call_mode_1_scalar_1")
  REAL(KIND=JPRB), ALLOCATABLE, TARGET :: ZGP(:,:,:), ZSPSCALAR(:,:)
  INTEGER(KIND=JPIM) :: ISPEC2, IGPTOTG, IGPTOT, IMY_PROC, IGPBLKS, I_REGIONS_NS, I_REGIONS_EW

  CALL SETUP_TEST(ISPEC2, IGPTOTG, IGPTOT, IGPBLKS, IMY_PROC, I_REGIONS_NS, I_REGIONS_EW)
  ZGP = GET_INPUT_FIELD(IMY_PROC, IGPTOTG, IGPBLKS, 1)
  ALLOCATE(ZSPSCALAR(1,ISPEC2))

  CALL DIR_TRANS_FIELD_VIEW( &
    & KRESOL=IRESOL_1, &
    & YDGPSCALAR=[MAKE_FIELD_VIEW(ZGP(:,1,:), FIELD_VIEW_INDEXING%NPROMA_BLOCK, GRID_SCALAR_NAME, INTENT_IN)], &
    & YDGPU=EMPTY_FIELD_VIEW_LIST, &
    & YDGPV=EMPTY_FIELD_VIEW_LIST, &
    & YDSPSCALAR=[MAKE_FIELD_VIEW(ZSPSCALAR, FIELD_VIEW_INDEXING%LEVEL_SPEC2, SPEC_SCALAR_NAME, INTENT_OUT)], &
    & YDSPVOR=EMPTY_FIELD_VIEW_LIST, &
    & YDSPDIV=EMPTY_FIELD_VIEW_LIST)

  IF (HAVE_M0_MODE()) THEN
    KRET = MERGE(0, 1, APPROX_EQ(ZSPSCALAR(1,1), 1.0_JPRB) .AND. &
      &         ALL(APPROX_EQ(ZSPSCALAR(1,2:), 0.0_JPRB)))
  ELSE
    KRET = MERGE(0, 1, ALL(APPROX_EQ(ZSPSCALAR, 0.0_JPRB)))
  ENDIF

  IF (LUSE_MPI) CALL MPL_ALLREDUCE(KRET, CDOPER="MAX")

  DEALLOCATE(ZSPSCALAR, ZGP)
  CALL CLEANUP_TEST
END FUNCTION ECTRANS_TEST_TRANS_API_DIR_TRANS_FV_CALL_MODE_1_SCALAR_1

INTEGER FUNCTION ECTRANS_TEST_TRANS_API_DIR_TRANS_FV_CALL_MODE_1_WIND_1() RESULT(KRET) &
  & BIND(C, NAME="ectrans_test_trans_api_dir_trans_field_view_call_mode_1_wind_1")
  REAL(KIND=JPRB), ALLOCATABLE, TARGET :: ZGP(:,:,:), ZSPVOR(:,:), ZSPDIV(:,:)
  INTEGER(KIND=JPIM) :: ISPEC2, IGPTOTG, IGPTOT, IMY_PROC, IGPBLKS, I_REGIONS_NS, I_REGIONS_EW
  REAL(KIND=JPRB) :: ZCORRECT_VORTICITY_VALUE

  CALL SETUP_TEST(ISPEC2, IGPTOTG, IGPTOT, IGPBLKS, IMY_PROC, I_REGIONS_NS, I_REGIONS_EW)
  ZGP = ROTATIONAL_WIND(IGPBLKS, I_REGIONS_NS, I_REGIONS_EW)
  ALLOCATE(ZSPVOR(1,ISPEC2), ZSPDIV(1,ISPEC2))

  CALL DIR_TRANS_FIELD_VIEW( &
    & KRESOL=IRESOL_1, &
    & YDGPSCALAR=EMPTY_FIELD_VIEW_LIST, &
    & YDGPU=[MAKE_FIELD_VIEW(ZGP(:,1,:), FIELD_VIEW_INDEXING%NPROMA_BLOCK, GRID_U_NAME, INTENT_IN)], &
    & YDGPV=[MAKE_FIELD_VIEW(ZGP(:,2,:), FIELD_VIEW_INDEXING%NPROMA_BLOCK, GRID_V_NAME, INTENT_IN)], &
    & YDSPSCALAR=EMPTY_FIELD_VIEW_LIST, &
    & YDSPVOR=[MAKE_FIELD_VIEW(ZSPVOR, FIELD_VIEW_INDEXING%LEVEL_SPEC2, SPEC_VOR_NAME, INTENT_OUT)], &
    & YDSPDIV=[MAKE_FIELD_VIEW(ZSPDIV, FIELD_VIEW_INDEXING%LEVEL_SPEC2, SPEC_DIV_NAME, INTENT_OUT)])

  IF (HAVE_M0_MODE()) THEN
    ZCORRECT_VORTICITY_VALUE = 2.0_JPRB * SQRT(1.0_JPRB / 3.0_JPRB) / PPEARTH_RADIUS
    KRET = 0
    IF (ANY(.NOT. APPROX_EQ(ZSPDIV, 0.0_JPRB))) KRET = 1
    IF (ANY(.NOT. APPROX_EQ(ZSPVOR(1,1:2), 0.0_JPRB))) KRET = 1
    IF (.NOT. APPROX_EQ(ZSPVOR(1,3), ZCORRECT_VORTICITY_VALUE)) KRET = 1
  ELSE
    KRET = MERGE(0, 1, ALL(APPROX_EQ(ZSPVOR, 0.0_JPRB) .AND. ALL(APPROX_EQ(ZSPDIV, 0.0_JPRB))))
  ENDIF

  IF (LUSE_MPI) CALL MPL_ALLREDUCE(KRET, CDOPER="MAX")

  DEALLOCATE(ZSPDIV, ZSPVOR, ZGP)
  CALL CLEANUP_TEST
END FUNCTION ECTRANS_TEST_TRANS_API_DIR_TRANS_FV_CALL_MODE_1_WIND_1

INTEGER FUNCTION ECTRANS_TEST_TRANS_API_DIR_TRANS_FV_CALL_MODE_1_WIND_1_SCALAR_1() RESULT(KRET) &
  & BIND(C, NAME="ectrans_test_trans_api_dir_trans_field_view_call_mode_1_wind_1_scalar_1")
  REAL(KIND=JPRB), ALLOCATABLE, TARGET :: ZGP(:,:,:), ZSPVOR(:,:), ZSPDIV(:,:), ZSPSCALAR(:,:)
  INTEGER(KIND=JPIM) :: ISPEC2, IGPTOTG, IGPTOT, IMY_PROC, IGPBLKS, I_REGIONS_NS, I_REGIONS_EW
  REAL(KIND=JPRB) :: ZCORRECT_VORTICITY_VALUE

  CALL SETUP_TEST(ISPEC2, IGPTOTG, IGPTOT, IGPBLKS, IMY_PROC, I_REGIONS_NS, I_REGIONS_EW)
  ALLOCATE(ZGP(JPPROMA, 3, IGPBLKS))
  ALLOCATE(ZSPVOR(1,ISPEC2), ZSPDIV(1,ISPEC2), ZSPSCALAR(1,ISPEC2))
  ZGP(:,1:2,:) = ROTATIONAL_WIND(IGPBLKS, I_REGIONS_NS, I_REGIONS_EW)
  ZGP(:,3:3,:) = GET_INPUT_FIELD(IMY_PROC, IGPTOTG, IGPBLKS, 1)

  CALL DIR_TRANS_FIELD_VIEW( &
    & KRESOL=IRESOL_1, &
    & YDGPSCALAR=[MAKE_FIELD_VIEW(ZGP(:,3,:), FIELD_VIEW_INDEXING%NPROMA_BLOCK, GRID_SCALAR_NAME, INTENT_IN)], &
    & YDGPU=[MAKE_FIELD_VIEW(ZGP(:,1,:), FIELD_VIEW_INDEXING%NPROMA_BLOCK, GRID_U_NAME, INTENT_IN)], &
    & YDGPV=[MAKE_FIELD_VIEW(ZGP(:,2,:), FIELD_VIEW_INDEXING%NPROMA_BLOCK, GRID_V_NAME, INTENT_IN)], &
    & YDSPSCALAR=[MAKE_FIELD_VIEW(ZSPSCALAR, FIELD_VIEW_INDEXING%LEVEL_SPEC2, SPEC_SCALAR_NAME, INTENT_OUT)], &
    & YDSPVOR=[MAKE_FIELD_VIEW(ZSPVOR, FIELD_VIEW_INDEXING%LEVEL_SPEC2, SPEC_VOR_NAME, INTENT_OUT)], &
    & YDSPDIV=[MAKE_FIELD_VIEW(ZSPDIV, FIELD_VIEW_INDEXING%LEVEL_SPEC2, SPEC_DIV_NAME, INTENT_OUT)])

  IF (HAVE_M0_MODE()) THEN
    ZCORRECT_VORTICITY_VALUE = 2.0_JPRB * SQRT(1.0_JPRB / 3.0_JPRB) / PPEARTH_RADIUS
    KRET = 0
    IF (.NOT. ALL(APPROX_EQ(ZSPSCALAR(1,2:), 0.0_JPRB))) KRET = 1
    IF (.NOT. APPROX_EQ(ZSPSCALAR(1,1), 1.0_JPRB)) KRET = 1
    IF (ANY(.NOT. APPROX_EQ(ZSPDIV, 0.0_JPRB))) KRET = 1
    IF (ANY(.NOT. APPROX_EQ(ZSPVOR(1,1:2), 0.0_JPRB))) KRET = 1
    IF (.NOT. APPROX_EQ(ZSPVOR(1,3), ZCORRECT_VORTICITY_VALUE)) KRET = 1
  ELSE
    IF (ALL(APPROX_EQ(ZSPVOR, 0.0_JPRB)) .AND. ALL(APPROX_EQ(ZSPDIV, 0.0_JPRB)) .AND. &
      & ALL(APPROX_EQ(ZSPSCALAR, 0.0_JPRB))) THEN
      KRET = 0
    ELSE
      KRET = 1
    END IF
  ENDIF

  IF (LUSE_MPI) CALL MPL_ALLREDUCE(KRET, CDOPER="MAX")

  DEALLOCATE(ZSPSCALAR, ZSPDIV, ZSPVOR, ZGP)
  CALL CLEANUP_TEST
END FUNCTION ECTRANS_TEST_TRANS_API_DIR_TRANS_FV_CALL_MODE_1_WIND_1_SCALAR_1

INTEGER FUNCTION ECTRANS_TEST_TRANS_API_DIR_TRANS_FV_CALL_MODE_2_PGP3A_1() RESULT(KRET) &
  & BIND(C, NAME="ectrans_test_trans_api_dir_trans_field_view_call_mode_2_pgp3a_1")
  REAL(KIND=JPRB), ALLOCATABLE, TARGET :: ZGP3A(:,:,:,:), ZSPSC3A(:,:,:)
  INTEGER(KIND=JPIM) :: ISPEC2, IGPTOTG, IGPTOT, IMY_PROC, IGPBLKS, I_REGIONS_NS, I_REGIONS_EW

  CALL SETUP_TEST(ISPEC2, IGPTOTG, IGPTOT, IGPBLKS, IMY_PROC, I_REGIONS_NS, I_REGIONS_EW)
  ALLOCATE(ZGP3A(JPPROMA,1,1,IGPBLKS))
  ZGP3A(:,1,:,:) = GET_INPUT_FIELD(IMY_PROC, IGPTOTG, IGPBLKS, 1)
  ALLOCATE(ZSPSC3A(1,ISPEC2,1))

  CALL DIR_TRANS_FIELD_VIEW( &
    & KRESOL=IRESOL_1, &
    & YDGPSCALAR=[MAKE_FIELD_VIEW(ZGP3A, FIELD_VIEW_INDEXING%NPROMA_LEVEL_FIELD_BLOCK, GRID_SCALAR_NAME, INTENT_IN)], &
    & YDGPU=EMPTY_FIELD_VIEW_LIST, &
    & YDGPV=EMPTY_FIELD_VIEW_LIST, &
    & YDSPSCALAR=[MAKE_FIELD_VIEW(ZSPSC3A, FIELD_VIEW_INDEXING%LEVEL_SPEC2_FIELD, SPEC_SCALAR_NAME, INTENT_OUT)], &
    & YDSPVOR=EMPTY_FIELD_VIEW_LIST, &
    & YDSPDIV=EMPTY_FIELD_VIEW_LIST)

  IF (HAVE_M0_MODE()) THEN
    KRET = MERGE(0, 1, APPROX_EQ(ZSPSC3A(1,1,1), 1.0_JPRB) .AND. &
      &         ALL(APPROX_EQ(ZSPSC3A(1,2:,1), 0.0_JPRB)))
  ELSE
    KRET = MERGE(0, 1, ALL(APPROX_EQ(ZSPSC3A, 0.0_JPRB)))
  ENDIF

  IF (LUSE_MPI) CALL MPL_ALLREDUCE(KRET, CDOPER="MAX")

  DEALLOCATE(ZSPSC3A, ZGP3A)
  CALL CLEANUP_TEST
END FUNCTION ECTRANS_TEST_TRANS_API_DIR_TRANS_FV_CALL_MODE_2_PGP3A_1

INTEGER FUNCTION ECTRANS_TEST_TRANS_API_DIR_TRANS_FV_CALL_MODE_2_PGP3B_1() RESULT(KRET) &
  & BIND(C, NAME="ectrans_test_trans_api_dir_trans_field_view_call_mode_2_pgp3b_1")
  REAL(KIND=JPRB), ALLOCATABLE, TARGET :: ZGP3B(:,:,:,:), ZSPSC3B(:,:,:)
  INTEGER(KIND=JPIM) :: ISPEC2, IGPTOTG, IGPTOT, IMY_PROC, IGPBLKS, I_REGIONS_NS, I_REGIONS_EW

  CALL SETUP_TEST(ISPEC2, IGPTOTG, IGPTOT, IGPBLKS, IMY_PROC, I_REGIONS_NS, I_REGIONS_EW)
  ALLOCATE(ZGP3B(JPPROMA,1,1,IGPBLKS))
  ZGP3B(:,1,:,:) = GET_INPUT_FIELD(IMY_PROC, IGPTOTG, IGPBLKS, 1)
  ALLOCATE(ZSPSC3B(1,ISPEC2,1))

  CALL DIR_TRANS_FIELD_VIEW( &
    & KRESOL=IRESOL_1, &
    & YDGPSCALAR=[MAKE_FIELD_VIEW(ZGP3B, FIELD_VIEW_INDEXING%NPROMA_LEVEL_FIELD_BLOCK, GRID_SCALAR_NAME, INTENT_IN)], &
    & YDGPU=EMPTY_FIELD_VIEW_LIST, &
    & YDGPV=EMPTY_FIELD_VIEW_LIST, &
    & YDSPSCALAR=[MAKE_FIELD_VIEW(ZSPSC3B, FIELD_VIEW_INDEXING%LEVEL_SPEC2_FIELD, SPEC_SCALAR_NAME, INTENT_OUT)], &
    & YDSPVOR=EMPTY_FIELD_VIEW_LIST, &
    & YDSPDIV=EMPTY_FIELD_VIEW_LIST)

  IF (HAVE_M0_MODE()) THEN
    KRET = MERGE(0, 1, APPROX_EQ(ZSPSC3B(1,1,1), 1.0_JPRB) .AND. &
      &         ALL(APPROX_EQ(ZSPSC3B(1,2:,1), 0.0_JPRB)))
  ELSE
    KRET = MERGE(0, 1, ALL(APPROX_EQ(ZSPSC3B, 0.0_JPRB)))
  ENDIF

  IF (LUSE_MPI) CALL MPL_ALLREDUCE(KRET, CDOPER="MAX")

  DEALLOCATE(ZSPSC3B, ZGP3B)
  CALL CLEANUP_TEST
END FUNCTION ECTRANS_TEST_TRANS_API_DIR_TRANS_FV_CALL_MODE_2_PGP3B_1

INTEGER FUNCTION ECTRANS_TEST_TRANS_API_DIR_TRANS_FV_CALL_MODE_2_WIND_1() RESULT(KRET) &
  & BIND(C, NAME="ectrans_test_trans_api_dir_trans_field_view_call_mode_2_wind_1")
  REAL(KIND=JPRB), ALLOCATABLE, TARGET :: ZGPUV(:,:,:,:), ZSPVOR(:,:), ZSPDIV(:,:)
  INTEGER(KIND=JPIM) :: ISPEC2, IGPTOTG, IGPTOT, IMY_PROC, IGPBLKS, I_REGIONS_NS, I_REGIONS_EW
  REAL(KIND=JPRB) :: ZCORRECT_VORTICITY_VALUE

  CALL SETUP_TEST(ISPEC2, IGPTOTG, IGPTOT, IGPBLKS, IMY_PROC, I_REGIONS_NS, I_REGIONS_EW)
  ALLOCATE(ZGPUV(JPPROMA,1,2,IGPBLKS))
  ZGPUV(:,1,:,:) = ROTATIONAL_WIND(IGPBLKS, I_REGIONS_NS, I_REGIONS_EW)
  ALLOCATE(ZSPVOR(1,ISPEC2), ZSPDIV(1,ISPEC2))

  CALL DIR_TRANS_FIELD_VIEW( &
    & KRESOL=IRESOL_1, &
    & YDGPSCALAR=EMPTY_FIELD_VIEW_LIST, &
    & YDGPU=[MAKE_FIELD_VIEW(ZGPUV(:,:,1,:), FIELD_VIEW_INDEXING%NPROMA_LEVEL_BLOCK, GRID_U_NAME, INTENT_IN)], &
    & YDGPV=[MAKE_FIELD_VIEW(ZGPUV(:,:,2,:), FIELD_VIEW_INDEXING%NPROMA_LEVEL_BLOCK, GRID_V_NAME, INTENT_IN)], &
    & YDSPSCALAR=EMPTY_FIELD_VIEW_LIST, &
    & YDSPVOR=[MAKE_FIELD_VIEW(ZSPVOR, FIELD_VIEW_INDEXING%LEVEL_SPEC2, SPEC_VOR_NAME, INTENT_OUT)], &
    & YDSPDIV=[MAKE_FIELD_VIEW(ZSPDIV, FIELD_VIEW_INDEXING%LEVEL_SPEC2, SPEC_DIV_NAME, INTENT_OUT)])

  IF (HAVE_M0_MODE()) THEN
    ZCORRECT_VORTICITY_VALUE = 2.0_JPRB * SQRT(1.0_JPRB / 3.0_JPRB) / PPEARTH_RADIUS
    KRET = 0
    IF (ANY(.NOT. APPROX_EQ(ZSPDIV, 0.0_JPRB))) KRET = 1
    IF (ANY(.NOT. APPROX_EQ(ZSPVOR(1,1:2), 0.0_JPRB))) KRET = 1
    IF (.NOT. APPROX_EQ(ZSPVOR(1,3), ZCORRECT_VORTICITY_VALUE)) KRET = 1
  ELSE
    KRET = MERGE(0, 1, ALL(APPROX_EQ(ZSPVOR, 0.0_JPRB) .AND. ALL(APPROX_EQ(ZSPDIV, 0.0_JPRB))))
  ENDIF

  IF (LUSE_MPI) CALL MPL_ALLREDUCE(KRET, CDOPER="MAX")

  DEALLOCATE(ZSPDIV, ZSPVOR, ZGPUV)
  CALL CLEANUP_TEST
END FUNCTION ECTRANS_TEST_TRANS_API_DIR_TRANS_FV_CALL_MODE_2_WIND_1

END MODULE DIR_TRANS_FIELD_VIEW_TEST_SUITE
