SUBROUTINE ECTRANS_VERSION(KRETURNCODE, CD_VERSION_STRING)
! ** PURPOSE
!    Return the version string of ecTrans
!
! ** DUMMY ARGUMENTS
!    CD_VERSION_STRING: version string
!
! ** AUTHOR
!    18 March 2025, S. Hatfield
!
! I. Dummy arguments declaration
USE ECTRANS_VERSION_MOD, ONLY: ECTRANS_VERSION_STR
IMPLICIT NONE
INTEGER(KIND=8), INTENT(OUT) :: KRETURNCODE
CHARACTER(LEN=14), INTENT(OUT) :: CD_VERSION_STRING
CD_VERSION_STRING = ECTRANS_VERSION_STR()
!
END SUBROUTINE ECTRANS_VERSION
