SUBROUTINE TRANS_INQ_DIST4PY(KRETURNCODE, KRESOL, KDGL, &
                      & KGPTOT, KSPEC, KSPEC2, KGPTOTG, KSPEC2G, KSMAX, &
                      & PMU, PGW)
! ** PURPOSE
!    Extract geometry from the (distributed) transform package for a given
!    resolution: this task's LOCAL sizes (KGPTOT, KSPEC, KSPEC2), the GLOBAL sizes
!    (KGPTOTG, KSPEC2G), the truncation (KSMAX), and the Gaussian latitudes
!    PMU=sin(latitude) and Gaussian weights PGW (both global, length KDGL).
!
! ** ARGUMENTS
!    KRESOL : resolution tag (from SETUP_TRANS_4PY)
!    KDGL   : number of Gaussian latitudes (sizes PMU/PGW)
USE ISO_FORTRAN_ENV, ONLY: INT64
USE PARKIND1, ONLY: JPIM, JPRB, JPRD
IMPLICIT NONE
INTEGER(KIND=INT64), INTENT(OUT) :: KRETURNCODE
INTEGER(KIND=INT64), INTENT(IN)  :: KRESOL, KDGL
INTEGER(KIND=INT64), INTENT(OUT) :: KGPTOT, KSPEC, KSPEC2, KGPTOTG, KSPEC2G, KSMAX
REAL(KIND=JPRB), DIMENSION(KDGL), INTENT(OUT) :: PMU, PGW
INTEGER(KIND=JPIM) :: IGPTOT, ISPEC, ISPEC2, IGPTOTG, ISPEC2G, ISMAX
REAL(KIND=JPRD) :: ZMU(KDGL)
#include "trans_inq.h"
KRETURNCODE = 0
ZMU(:) = 0._JPRD
CALL TRANS_INQ(KRESOL=INT(KRESOL,JPIM), KGPTOT=IGPTOT, KSPEC=ISPEC, KSPEC2=ISPEC2, &
 & KGPTOTG=IGPTOTG, KSPEC2G=ISPEC2G, KSMAX=ISMAX, PMU=ZMU, PGW=PGW)
KGPTOT  = IGPTOT
KSPEC   = ISPEC
KSPEC2  = ISPEC2
KGPTOTG = IGPTOTG
KSPEC2G = ISPEC2G
KSMAX   = ISMAX
PMU(:) = ZMU(:)
END SUBROUTINE TRANS_INQ_DIST4PY
