! Distributed spectral transforms on LOCAL arrays (the resolution must have been set
! up with LDSPLIT=.TRUE.). Spectral local arrays are (KSPEC2, KFLD) in ecTrans model
! order; grid local arrays are (KGPTOT, KFLD) as a single NPROMA block. Single precision.

SUBROUTINE INV_TRANS_SCALAR_DIST4PY(KRETURNCODE, KSPEC2, KGPTOT, KFLD, PSPEC, PGP)
! Inverse transform of scalar fields: local spectral -> local grid-point.
USE ISO_FORTRAN_ENV, ONLY: INT64
USE PARKIND1, ONLY: JPIM, JPRB
IMPLICIT NONE
INTEGER(KIND=INT64), INTENT(OUT) :: KRETURNCODE
INTEGER(KIND=INT64), INTENT(IN)  :: KSPEC2, KGPTOT, KFLD
REAL(KIND=JPRB), DIMENSION(KSPEC2, KFLD), INTENT(IN)  :: PSPEC
REAL(KIND=JPRB), DIMENSION(KGPTOT, KFLD), INTENT(OUT) :: PGP
REAL(KIND=JPRB) :: ZSP(KFLD, KSPEC2)
REAL(KIND=JPRB) :: ZGP(KGPTOT, KFLD, 1)
INTEGER(KIND=JPIM) :: JL
#include "inv_trans.h"
KRETURNCODE = 0
DO JL = 1, KFLD
  ZSP(JL, :) = PSPEC(:, JL)
ENDDO
CALL INV_TRANS(PSPSCALAR=ZSP, PGP=ZGP, KPROMA=INT(KGPTOT,JPIM))
PGP(:, :) = ZGP(:, :, 1)
END SUBROUTINE INV_TRANS_SCALAR_DIST4PY


SUBROUTINE INV_TRANS_SCALAR_DERS_DIST4PY(KRETURNCODE, KSPEC2, KGPTOT, KFLD, PSPEC, PGP, PGPNS, PGPEW)
! Inverse transform of scalar fields WITH horizontal derivatives (LDSCDERS=.TRUE.):
! local spectral -> local grid value PGP, N-S derivative PGPNS, E-W derivative PGPEW.
! With LDSCDERS the PGP output holds 3*KFLD fields: [values, N-S derivs, E-W derivs].
USE ISO_FORTRAN_ENV, ONLY: INT64
USE PARKIND1, ONLY: JPIM, JPRB
IMPLICIT NONE
INTEGER(KIND=INT64), INTENT(OUT) :: KRETURNCODE
INTEGER(KIND=INT64), INTENT(IN)  :: KSPEC2, KGPTOT, KFLD
REAL(KIND=JPRB), DIMENSION(KSPEC2, KFLD), INTENT(IN)  :: PSPEC
REAL(KIND=JPRB), DIMENSION(KGPTOT, KFLD), INTENT(OUT) :: PGP, PGPNS, PGPEW
REAL(KIND=JPRB) :: ZSP(KFLD, KSPEC2)
REAL(KIND=JPRB) :: ZGP(KGPTOT, 3*KFLD, 1)
INTEGER(KIND=JPIM) :: JL
#include "inv_trans.h"
KRETURNCODE = 0
DO JL = 1, KFLD
  ZSP(JL, :) = PSPEC(:, JL)
ENDDO
CALL INV_TRANS(PSPSCALAR=ZSP, PGP=ZGP, LDSCDERS=.TRUE., KPROMA=INT(KGPTOT,JPIM))
! field order (see inv_trans.h): values | N-S derivatives | E-W derivatives
PGP  (:, :) = ZGP(:, 1:KFLD,            1)
PGPNS(:, :) = ZGP(:, KFLD+1:2*KFLD,     1)
PGPEW(:, :) = ZGP(:, 2*KFLD+1:3*KFLD,   1)
END SUBROUTINE INV_TRANS_SCALAR_DERS_DIST4PY


SUBROUTINE DIR_TRANS_SCALAR_DIST4PY(KRETURNCODE, KSPEC2, KGPTOT, KFLD, PGP, PSPEC)
! Direct transform of scalar fields: local grid-point -> local spectral.
USE ISO_FORTRAN_ENV, ONLY: INT64
USE PARKIND1, ONLY: JPIM, JPRB
IMPLICIT NONE
INTEGER(KIND=INT64), INTENT(OUT) :: KRETURNCODE
INTEGER(KIND=INT64), INTENT(IN)  :: KSPEC2, KGPTOT, KFLD
REAL(KIND=JPRB), DIMENSION(KGPTOT, KFLD), INTENT(IN)  :: PGP
REAL(KIND=JPRB), DIMENSION(KSPEC2, KFLD), INTENT(OUT) :: PSPEC
REAL(KIND=JPRB) :: ZSP(KFLD, KSPEC2)
REAL(KIND=JPRB) :: ZGP(KGPTOT, KFLD, 1)
INTEGER(KIND=JPIM) :: JL
#include "dir_trans.h"
KRETURNCODE = 0
ZGP(:, :, 1) = PGP(:, :)
CALL DIR_TRANS(PSPSCALAR=ZSP, PGP=ZGP, KPROMA=INT(KGPTOT,JPIM))
DO JL = 1, KFLD
  PSPEC(:, JL) = ZSP(JL, :)
ENDDO
END SUBROUTINE DIR_TRANS_SCALAR_DIST4PY


SUBROUTINE INV_TRANS_UV_DIST4PY(KRETURNCODE, KSPEC2, KGPTOT, KFLD, PSPVOR, PSPDIV, PGPU, PGPV)
! Inverse transform vorticity/divergence -> u,v winds (local).
USE ISO_FORTRAN_ENV, ONLY: INT64
USE PARKIND1, ONLY: JPIM, JPRB
IMPLICIT NONE
INTEGER(KIND=INT64), INTENT(OUT) :: KRETURNCODE
INTEGER(KIND=INT64), INTENT(IN)  :: KSPEC2, KGPTOT, KFLD
REAL(KIND=JPRB), DIMENSION(KSPEC2, KFLD), INTENT(IN)  :: PSPVOR, PSPDIV
REAL(KIND=JPRB), DIMENSION(KGPTOT, KFLD), INTENT(OUT) :: PGPU, PGPV
REAL(KIND=JPRB) :: ZVOR(KFLD, KSPEC2), ZDIV(KFLD, KSPEC2)
REAL(KIND=JPRB) :: ZGPUV(KGPTOT, KFLD, 2, 1)
INTEGER(KIND=JPIM) :: JL
#include "inv_trans.h"
KRETURNCODE = 0
DO JL = 1, KFLD
  ZVOR(JL, :) = PSPVOR(:, JL)
  ZDIV(JL, :) = PSPDIV(:, JL)
ENDDO
CALL INV_TRANS(PSPVOR=ZVOR, PSPDIV=ZDIV, PGPUV=ZGPUV, KPROMA=INT(KGPTOT,JPIM))
PGPU(:, :) = ZGPUV(:, :, 1, 1)
PGPV(:, :) = ZGPUV(:, :, 2, 1)
END SUBROUTINE INV_TRANS_UV_DIST4PY


SUBROUTINE DIR_TRANS_UV_DIST4PY(KRETURNCODE, KSPEC2, KGPTOT, KFLD, PGPU, PGPV, PSPVOR, PSPDIV)
! Direct transform u,v winds -> vorticity/divergence (local).
USE ISO_FORTRAN_ENV, ONLY: INT64
USE PARKIND1, ONLY: JPIM, JPRB
IMPLICIT NONE
INTEGER(KIND=INT64), INTENT(OUT) :: KRETURNCODE
INTEGER(KIND=INT64), INTENT(IN)  :: KSPEC2, KGPTOT, KFLD
REAL(KIND=JPRB), DIMENSION(KGPTOT, KFLD), INTENT(IN)  :: PGPU, PGPV
REAL(KIND=JPRB), DIMENSION(KSPEC2, KFLD), INTENT(OUT) :: PSPVOR, PSPDIV
REAL(KIND=JPRB) :: ZVOR(KFLD, KSPEC2), ZDIV(KFLD, KSPEC2)
REAL(KIND=JPRB) :: ZGPUV(KGPTOT, KFLD, 2, 1)
INTEGER(KIND=JPIM) :: JL
#include "dir_trans.h"
KRETURNCODE = 0
ZGPUV(:, :, 1, 1) = PGPU(:, :)
ZGPUV(:, :, 2, 1) = PGPV(:, :)
CALL DIR_TRANS(PSPVOR=ZVOR, PSPDIV=ZDIV, PGPUV=ZGPUV, KPROMA=INT(KGPTOT,JPIM))
DO JL = 1, KFLD
  PSPVOR(:, JL) = ZVOR(JL, :)
  PSPDIV(:, JL) = ZDIV(JL, :)
ENDDO
END SUBROUTINE DIR_TRANS_UV_DIST4PY
