MODULE EFTINV_MOD
CONTAINS
SUBROUTINE EFTINV(ALLOCATOR,PREEL,KF_FS)

USE PARKIND1  ,ONLY : JPIM, JPRB, JPIB
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK, JPHOOK

USE TPM_GEN, ONLY : NCUR_RESOL
USE TPM_DISTR       ,ONLY : D
USE TPM_DIM         ,ONLY : R
USE TPMALD_DIM      ,ONLY : RALD
USE TPMALD_FFT      ,ONLY : TALD

USE TPM_HICFFT      ,ONLY : EXECUTE_INV_FFT

USE ABORT_TRANS_MOD ,ONLY : ABORT_TRANS

USE ISO_C_BINDING
USE BUFFERED_ALLOCATOR_MOD

!

IMPLICIT NONE

TYPE(BUFFERED_ALLOCATOR), INTENT(IN) :: ALLOCATOR
INTEGER(KIND=JPIM), INTENT(IN)  :: KF_FS
REAL(KIND=JPRB),    INTENT(INOUT)  :: PREEL(:)   ! (IRLEN+2)*KF_FS*NDGL_FS

INTEGER(KIND=JPIM) :: JLOT, IRLEN, JJ
! INTEGER(KIND=JPIB) :: OFFSETS(2)
! INTEGER(KIND=JPIM) :: LOENS(1)
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

!     ------------------------------------------------------------------

!*       1.       PERFORM LEGENDRE TRANFORM.
!                 --------------------------

IF (LHOOK) CALL DR_HOOK('EFTINV_MOD:EFTINV',0,ZHOOK_HANDLE)

IRLEN=R%NDLON+R%NNOEXTZG

! LOENS(1)=IRLEN
JLOT=SIZE(PREEL)/(IRLEN+2)
! DO JJ=1,SIZE(OFFSETS)
  ! OFFSETS(JJ)=(JJ-1)*(IRLEN+2)
! ENDDO

IF (JLOT==0) THEN
  IF (LHOOK) CALL DR_HOOK('EFTINV_MOD:EFTINV',1,ZHOOK_HANDLE)
  RETURN
ENDIF

#ifdef gnarls

! fake fft: only take mean value, on cpu
!$acc data present(preel)
!$acc update host(preel)
DO JJ=1,JLOT
  preel((JJ-1)*(irlen+2)+2:jj*(irlen+2)-2)=preel((JJ-1)*(irlen+2)+1)
ENDDO
!$acc update device(preel)
!$acc end data

#else

!$ACC DATA PRESENT(PREEL,RALD%NLOENS_LON,RALD%NOFFSETS_LON)
CALL EXECUTE_INV_FFT(PREEL(:),PREEL(:),NCUR_RESOL,JLOT, &
    & LOENS=RALD%NLOENS_LON, &
    & OFFSETS=RALD%NOFFSETS_LON,ALLOC=ALLOCATOR%PTR)
!$ACC END DATA

#endif

IF (LHOOK) CALL DR_HOOK('EFTINV_MOD:EFTINV',1,ZHOOK_HANDLE)

END SUBROUTINE EFTINV
END MODULE EFTINV_MOD