MODULE TPMALD_DIM

! Module for dimensions.

USE PARKIND1  ,ONLY : JPIM     ,JPRB, JPIB

IMPLICIT NONE

SAVE

TYPE ALDDIM_TYPE

! COLLOCATION GRID DIMENSIONS
  
INTEGER(KIND=JPIM) :: NDGLSUR       ! Number of rows of latitudes+...
INTEGER(KIND=JPIM) :: NMSMAX        ! Zonal truncation
INTEGER(KIND=JPIM) :: NDGUX         ! Number of rows in zone C+I
INTEGER(KIND=JPIM) :: NLOENS_LON(1)
INTEGER(KIND=JPIB) :: NOFFSETS_LON(2)
INTEGER(KIND=JPIM) :: NLOENS_LAT(1)
INTEGER(KIND=JPIB) :: NOFFSETS_LAT(2)

END TYPE ALDDIM_TYPE

TYPE(ALDDIM_TYPE),ALLOCATABLE,TARGET :: ALDDIM_RESOL(:)
TYPE(ALDDIM_TYPE),POINTER     :: RALD

END MODULE TPMALD_DIM
