MODULE TPMALD_DIM

! Module for dimensions.

USE PARKIND1  ,ONLY : JPIM     ,JPRB

IMPLICIT NONE

SAVE

TYPE ALDDIM_TYPE

! COLLOCATION GRID DIMENSIONS
  
INTEGER(KIND=JPIM) :: NDGLSUR       ! Number of rows of latitudes+...
INTEGER(KIND=JPIM) :: NMSMAX        ! Zonal truncation
INTEGER(KIND=JPIM) :: NDGUX         ! Number of rows in zone C+I
END TYPE ALDDIM_TYPE

TYPE(ALDDIM_TYPE),ALLOCATABLE,TARGET :: ALDDIM_RESOL(:)
TYPE(ALDDIM_TYPE),POINTER     :: RALD

END MODULE TPMALD_DIM
