! (C) Copyright 2001- ECMWF.
! (C) Copyright 2001- Meteo-France.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.

MODULE ECTRANS_FIELD_VIEW_MOD

! Must stay precision independent (i.e. do not use parkind or JPRB)

USE, INTRINSIC :: ISO_C_BINDING, ONLY: C_PTR, C_INT, C_F_POINTER, C_FLOAT, C_DOUBLE
USE ABORT_TRANS_MOD, ONLY : ABORT_TRANS

IMPLICIT NONE

PRIVATE

PUBLIC :: FIELD_VIEW, FIELD_VIEW_GET_DATA_PTR, FIELD_VIEW_GET_IVSET_PTR, FIELD_VIEW_GET_NAME_PTR

INTEGER, PARAMETER :: MAX_RANK = 4

TYPE, BIND(C) :: FIELD_VIEW

  ! ARRAY
  TYPE(C_PTR)    :: DATA
  INTEGER(C_INT) :: KIND
  INTEGER(C_INT) :: RANK
  INTEGER(C_INT) :: EXTENTS(MAX_RANK)
  INTEGER(C_INT) :: STRIDES(MAX_RANK)

  ! IVSET
  TYPE(C_PTR)    :: IVSET
  INTEGER(C_INT) :: IVSET_SIZE

  ! NAME
  TYPE(C_PTR)    :: NAME
  INTEGER(C_INT) :: NAME_SIZE

  ! FIELD TYPE
  INTEGER(C_INT) :: FIELD_TYPE

  ! INDEXING
  INTEGER(C_INT) :: INDEXING

END TYPE

INTERFACE FIELD_VIEW_GET_DATA_PTR
  MODULE PROCEDURE :: GET_DATA_PTR_1RM, GET_DATA_PTR_2RM, GET_DATA_PTR_3RM, GET_DATA_PTR_4RM
  MODULE PROCEDURE :: GET_DATA_PTR_1RD, GET_DATA_PTR_2RD, GET_DATA_PTR_3RD, GET_DATA_PTR_4RD
END INTERFACE

CONTAINS

SUBROUTINE FIELD_VIEW_GET_NAME_PTR(YLFV, NAME)
  TYPE(FIELD_VIEW), INTENT(IN) :: YLFV
  CHARACTER(LEN=:), POINTER, INTENT(INOUT) :: NAME
  CHARACTER(LEN=YLFV%NAME_SIZE), POINTER :: F_STR
  CALL C_F_POINTER(YLFV%NAME, F_STR)
  NAME => F_STR
END SUBROUTINE

SUBROUTINE ASSERT_EXPECTED_RANK_AND_KIND(LABEL, YLFV, EXPECTED_RANK, EXPECTED_KIND)
  IMPLICIT NONE
  CHARACTER(LEN=*), INTENT(IN) :: LABEL
  TYPE(FIELD_VIEW), INTENT(IN) :: YLFV
  INTEGER(C_INT), INTENT(IN) :: EXPECTED_RANK
  INTEGER(C_INT), INTENT(IN) :: EXPECTED_KIND
  IF (YLFV%RANK /= EXPECTED_RANK) THEN
    BLOCK
      CHARACTER(LEN=:), POINTER :: NAME
      CALL FIELD_VIEW_GET_NAME_PTR(YLFV, NAME)
      CALL ABORT_TRANS(TRIM(LABEL)//" FAILURE: FIELD "//TRIM(NAME)//" RANK MUST BE "//&
        & TRIM(TO_STR(EXPECTED_RANK))//" BUT IS "//TRIM(TO_STR(YLFV%RANK)))
    END BLOCK
  ENDIF
  IF (YLFV%KIND /= EXPECTED_KIND) THEN
    BLOCK
      CHARACTER(LEN=:), POINTER :: NAME
      CALL FIELD_VIEW_GET_NAME_PTR(YLFV, NAME)
      CALL ABORT_TRANS(TRIM(LABEL)//" FAILURE: FIELD "//TRIM(NAME)//" KIND MUST BE "//&
        & TRIM(TO_STR(EXPECTED_KIND))//" BUT IS "//TRIM(TO_STR(YLFV%KIND)))
    END BLOCK
  ENDIF
  CONTAINS
  FUNCTION TO_STR(I) RESULT(STR)
    INTEGER, INTENT(IN) :: I
    CHARACTER(LEN=32) :: STR
    WRITE(STR, '(I0)') I
  END FUNCTION TO_STR
END SUBROUTINE

SUBROUTINE GET_DATA_PTR_1RM(YLFV, PTR)
  IMPLICIT NONE
  TYPE(FIELD_VIEW), INTENT(IN) :: YLFV
  REAL(C_FLOAT), POINTER :: PTR(:)
  INTEGER(C_INT), PARAMETER :: RANK = 1
  CALL ASSERT_EXPECTED_RANK_AND_KIND("GET_DATA_PTR_1RM", YLFV, RANK, C_FLOAT)
  IF (YLFV%STRIDES(1) == 1) THEN
    CALL C_F_POINTER(YLFV%DATA, PTR, YLFV%EXTENTS(1:1))
  ELSE
    BLOCK
      REAL(C_FLOAT), POINTER :: PTR_2D(:,:)
      INTEGER(C_INT) :: EXTENTS(2)
      EXTENTS(1) = YLFV%STRIDES(1)
      EXTENTS(2) = YLFV%EXTENTS(1)
      CALL C_F_POINTER(YLFV%DATA, PTR_2D, EXTENTS(1:2))
      PTR => PTR_2D(1, 1:YLFV%EXTENTS(1))
    END BLOCK
  ENDIF
END SUBROUTINE

SUBROUTINE GET_DATA_PTR_1RD(YLFV, PTR)
  IMPLICIT NONE
  TYPE(FIELD_VIEW), INTENT(IN) :: YLFV
  REAL(C_DOUBLE), POINTER, INTENT(INOUT) :: PTR(:)
  INTEGER(C_INT), PARAMETER :: RANK = 1
  CALL ASSERT_EXPECTED_RANK_AND_KIND("GET_DATA_PTR_1RD", YLFV, RANK, C_DOUBLE)
  IF (YLFV%STRIDES(1) == 1) THEN
    CALL C_F_POINTER(YLFV%DATA, PTR, YLFV%EXTENTS(1:1))
  ELSE
    BLOCK
      REAL(C_DOUBLE), POINTER :: PTR_2D(:,:)
      INTEGER(C_INT) :: EXTENTS(2)
      EXTENTS(1) = YLFV%STRIDES(1)
      EXTENTS(2) = YLFV%EXTENTS(1)
      CALL C_F_POINTER(YLFV%DATA, PTR_2D, EXTENTS(1:2))
      PTR => PTR_2D(1, 1:YLFV%EXTENTS(1))
    END BLOCK
  ENDIF
END SUBROUTINE

SUBROUTINE GET_DATA_PTR_2RM(YLFV, PTR)
  IMPLICIT NONE
  TYPE(FIELD_VIEW), INTENT(IN) :: YLFV
  REAL(C_FLOAT), POINTER, INTENT(INOUT) :: PTR(:,:)
  INTEGER(C_INT), PARAMETER :: RANK = 2
  INTEGER(C_INT) :: EXTENTS(RANK), JDIM
  CALL ASSERT_EXPECTED_RANK_AND_KIND("GET_DATA_PTR_2RM", YLFV, RANK, C_FLOAT)
  DO JDIM=1,RANK
    EXTENTS(JDIM) = YLFV%STRIDES(JDIM+1)/YLFV%STRIDES(JDIM)
  ENDDO
  EXTENTS(RANK) = YLFV%EXTENTS(RANK)
  CALL C_F_POINTER(YLFV%DATA, PTR, EXTENTS)
  PTR => PTR(1:YLFV%EXTENTS(1), 1:YLFV%EXTENTS(2))
END SUBROUTINE

SUBROUTINE GET_DATA_PTR_2RD(YLFV, PTR)
  IMPLICIT NONE
  TYPE(FIELD_VIEW), INTENT(IN) :: YLFV
  REAL(C_DOUBLE), POINTER, INTENT(INOUT) :: PTR(:,:)
  INTEGER(C_INT), PARAMETER :: RANK = 2
  INTEGER(C_INT) :: EXTENTS(RANK), JDIM
  CALL ASSERT_EXPECTED_RANK_AND_KIND("GET_DATA_PTR_2RD", YLFV, RANK, C_DOUBLE)
  DO JDIM=1,RANK
    EXTENTS(JDIM) = YLFV%STRIDES(JDIM+1)/YLFV%STRIDES(JDIM)
  ENDDO
  EXTENTS(RANK) = YLFV%EXTENTS(RANK)
  CALL C_F_POINTER(YLFV%DATA, PTR, EXTENTS)
  PTR => PTR(1:YLFV%EXTENTS(1), 1:YLFV%EXTENTS(2))
END SUBROUTINE

SUBROUTINE GET_DATA_PTR_3RM(YLFV, PTR)
  IMPLICIT NONE
  TYPE(FIELD_VIEW), INTENT(IN) :: YLFV
  REAL(C_FLOAT), POINTER, INTENT(INOUT) :: PTR(:,:,:)
  INTEGER(C_INT), PARAMETER :: RANK = 3
  INTEGER(C_INT) :: EXTENTS(3), JDIM
  CALL ASSERT_EXPECTED_RANK_AND_KIND("GET_DATA_PTR_3RM", YLFV, RANK, C_FLOAT)
  DO JDIM=1,RANK
    EXTENTS(JDIM) = YLFV%STRIDES(JDIM+1)/YLFV%STRIDES(JDIM)
  ENDDO
  EXTENTS(RANK) = YLFV%EXTENTS(RANK)
  CALL C_F_POINTER(YLFV%DATA, PTR, EXTENTS)
  PTR => PTR(1:YLFV%EXTENTS(1), 1:YLFV%EXTENTS(2), 1:YLFV%EXTENTS(3))
END SUBROUTINE

SUBROUTINE GET_DATA_PTR_3RD(YLFV, PTR)
  IMPLICIT NONE
  TYPE(FIELD_VIEW), INTENT(IN) :: YLFV
  REAL(C_DOUBLE), POINTER, INTENT(INOUT) :: PTR(:,:,:)
  INTEGER(C_INT), PARAMETER :: RANK = 3
  INTEGER(C_INT) :: EXTENTS(RANK), JDIM
  CALL ASSERT_EXPECTED_RANK_AND_KIND("GET_DATA_PTR_3RD", YLFV, RANK, C_DOUBLE)
  DO JDIM=1,RANK-1
    EXTENTS(JDIM) = YLFV%STRIDES(JDIM+1)/YLFV%STRIDES(JDIM)
  ENDDO
  EXTENTS(RANK) = YLFV%EXTENTS(RANK)
  CALL C_F_POINTER(YLFV%DATA, PTR, EXTENTS)
  PTR => PTR(1:YLFV%EXTENTS(1), 1:YLFV%EXTENTS(2), 1:YLFV%EXTENTS(3))
END SUBROUTINE

SUBROUTINE GET_DATA_PTR_4RM(YLFV, PTR)
  IMPLICIT NONE
  TYPE(FIELD_VIEW), INTENT(IN) :: YLFV
  REAL(C_FLOAT), POINTER, INTENT(INOUT) :: PTR(:,:,:,:)
  INTEGER(C_INT), PARAMETER :: RANK = 4
  INTEGER(C_INT) :: EXTENTS(RANK), JDIM
  CALL ASSERT_EXPECTED_RANK_AND_KIND("GET_DATA_PTR_4RM", YLFV, RANK, C_FLOAT)
  DO JDIM=1,RANK-1
    EXTENTS(JDIM) = YLFV%STRIDES(JDIM+1)/YLFV%STRIDES(JDIM)
  ENDDO
  EXTENTS(RANK) = YLFV%EXTENTS(RANK)
  CALL C_F_POINTER(YLFV%DATA, PTR, EXTENTS)
  PTR => PTR(1:YLFV%EXTENTS(1), 1:YLFV%EXTENTS(2), 1:YLFV%EXTENTS(3), 1:YLFV%EXTENTS(4))
END SUBROUTINE

SUBROUTINE GET_DATA_PTR_4RD(YLFV, PTR)
  IMPLICIT NONE
  TYPE(FIELD_VIEW), INTENT(IN) :: YLFV
  REAL(C_DOUBLE), POINTER, INTENT(INOUT) :: PTR(:,:,:,:)
  INTEGER(C_INT), PARAMETER :: RANK = 4
  INTEGER(C_INT) :: EXTENTS(RANK), JDIM
  CALL ASSERT_EXPECTED_RANK_AND_KIND("GET_DATA_PTR_4RD", YLFV, RANK, C_DOUBLE)
  DO JDIM=1,RANK-1
    EXTENTS(JDIM) = YLFV%STRIDES(JDIM+1)/YLFV%STRIDES(JDIM)
  ENDDO
  EXTENTS(RANK) = YLFV%EXTENTS(RANK)
  CALL C_F_POINTER(YLFV%DATA, PTR, EXTENTS)
  PTR => PTR(1:YLFV%EXTENTS(1), 1:YLFV%EXTENTS(2), 1:YLFV%EXTENTS(3), 1:YLFV%EXTENTS(4))
END SUBROUTINE

SUBROUTINE FIELD_VIEW_GET_IVSET_PTR(YLFV, IVSET)
  TYPE(FIELD_VIEW), INTENT(IN) :: YLFV
  INTEGER(KIND=C_INT), POINTER, INTENT(INOUT) :: IVSET(:)
  CALL C_F_POINTER(YLFV%IVSET, IVSET, [YLFV%IVSET_SIZE])
END SUBROUTINE

END MODULE ECTRANS_FIELD_VIEW_MOD

