! (C) Copyright 2025- ECMWF.
! (C) Copyright 2025- Meteo-France.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.
!

MODULE TRGL_VIEW_MOD

USE PARKIND1, ONLY : JPIM
USE TRGL_MOD, ONLY : TRGL_BUFFERS, TRGL_VARS
USE ECTRANS_FIELD_VIEW_INTERNAL_UTIL_MOD, ONLY : GRID_VIEW
IMPLICIT NONE

CONTAINS

SUBROUTINE TGRL_COPY_ZCOMBUF_VIEW(YDBUFS, YLVARS, INRS, ZCOMBUF, YDGP)

  USE PARKIND1  ,ONLY : JPIM, JPRB
  USE TPM_TRANS       ,ONLY : NGPBLKS
  USE ECTRANS_FIELD_VIEW_INTERNAL_UTIL_MOD, ONLY : GRID_VIEW
  
  TYPE(TRGL_BUFFERS),  INTENT(INOUT) :: YDBUFS
  TYPE(TRGL_VARS), INTENT(INOUT) :: YLVARS
  INTEGER(KIND=JPIM), INTENT(IN) :: INRS
  REAL(KIND=JPRB), POINTER, CONTIGUOUS, INTENT(INOUT) :: ZCOMBUF(:,:)  
  TYPE(GRID_VIEW) :: YDGP(:)

  !Local variables
  INTEGER(KIND=JPIM) :: I_FLD_START,I_FLD_END
  INTEGER(KIND=JPIM) :: IFIRST, ILAST
  INTEGER(KIND=JPIM) :: JJ,JI,JK,IFLDT, JBLK, IPOS

  ASSOCIATE(IFLDA=>YDBUFS%IFLDA,IPOSPLUS=>YDBUFS%IPOSPLUS, &
    &JPOS=>YDBUFS%IJPOS, ISETW=>YDBUFS%ISETW,KGPTRSEND =>YDBUFS%IGPTRSEND)
    
  IPOS=IPOSPLUS(INRS)
  I_FLD_START = ZCOMBUF(-1,INRS)
  I_FLD_END   = ZCOMBUF(0,INRS)

  !$OMP PARALLEL DO SCHEDULE(STATIC) PRIVATE(IFLDT,IFIRST,ILAST,JK,JJ,JI,JBLK)
  DO JJ=I_FLD_START,I_FLD_END
    IFLDT=IFLDA(JJ,INRS)
    DO JBLK=1,NGPBLKS
      IFIRST = KGPTRSEND(1,JBLK,ISETW(INRS))
      IF(IFIRST > 0) THEN
        ILAST = KGPTRSEND(2,JBLK,ISETW(INRS))
          DO JK=IFIRST,ILAST
            JI=(JJ-I_FLD_START)*IPOS+JPOS(JBLK,INRS)+JK-IFIRST+1
            IF (YDBUFS%LLTRGTOL) THEN
              ZCOMBUF(JI,INRS) = YDGP (IFLDT)%P (JK,JBLK)
            ELSE
              YDGP (IFLDT)%P (JK,JBLK) = ZCOMBUF(JI,INRS)           
            ENDIF
          ENDDO      
      ENDIF
    ENDDO
  ENDDO
  !$OMP END PARALLEL DO

  END ASSOCIATE
END SUBROUTINE TGRL_COPY_ZCOMBUF_VIEW

SUBROUTINE TGRL_COPY_PGLAT_VIEW(PGLAT, YDBUFS, YLVARS, YDGP)

  USE PARKIND1  ,ONLY : JPIM, JPRB, JPIB
  USE TPM_DISTR       ,ONLY : MYSETW, MYPROC
  USE TPM_GEN         ,ONLY : NOUT
  USE ABORT_TRANS_MOD ,ONLY : ABORT_TRANS
  USE TPM_TRANS       ,ONLY : NGPBLKS
  USE ECTRANS_FIELD_VIEW_INTERNAL_UTIL_MOD, ONLY : GRID_VIEW

  IMPLICIT NONE
  REAL(KIND=JPRB),OPTIONAL   :: PGLAT(:,:)
  TYPE(TRGL_BUFFERS),  INTENT(INOUT) :: YDBUFS
  TYPE(TRGL_VARS), INTENT(INOUT) :: YLVARS
  TYPE(GRID_VIEW)    :: YDGP(:)


    !Local variables
  INTEGER(KIND=JPIM) :: IFIRST, ILAST, IFLD, IPOS, JBLK, JK
  INTEGER(KIND=JPIB) :: JFLD64

  ASSOCIATE(IFLDOFF=>YLVARS%IFLDOFF, IGPTROFF=>YLVARS%IGPTROFF, &    
    &       KINDEX=>YDBUFS%IINDEX, &
    &       KNDOFF=>YDBUFS%INDOFF, KGPTRSEND =>YDBUFS%IGPTRSEND, IFLDS=>YDBUFS%IFLDS)

#ifdef __NEC__
  ! Loops inversion is still better on Aurora machines, according to CHMI. REK.
  !$OMP PARALLEL DO SCHEDULE(DYNAMIC) PRIVATE(JFLD64,JBLK,JK,IFLD,IPOS,IFIRST,ILAST)
#else
  !$OMP PARALLEL DO SCHEDULE(STATIC) PRIVATE(JFLD64,JBLK,JK,IFLD,IPOS,IFIRST,ILAST)
#endif
  DO JBLK=1,NGPBLKS
    IFIRST = KGPTRSEND(1,JBLK,MYSETW)
    IF(IFIRST > 0) THEN
      ILAST = KGPTRSEND(2,JBLK,MYSETW)
      ! Address PGLAT over 64 bits because its size may exceed 2 GB for big data and
      ! small number of tasks.
      
        DO JFLD64=1,IFLDS
          IFLD = IFLDOFF(JFLD64)
          !DIR$ VECTOR ALWAYS
          DO JK=IFIRST,ILAST
            IPOS = KNDOFF(MYPROC)+IGPTROFF(JBLK)+JK-IFIRST+1
            IF (YDBUFS%LLTRGTOL) THEN
              PGLAT(JFLD64,KINDEX(IPOS)) = YDGP(IFLD)%P(JK, JBLK) 
            ELSE
              YDGP(IFLD)%P(JK, JBLK) = PGLAT(JFLD64,KINDEX(IPOS))
            ENDIF
          ENDDO
        ENDDO
    ENDIF
  ENDDO
  !$OMP END PARALLEL DO

  END ASSOCIATE
END SUBROUTINE TGRL_COPY_PGLAT_VIEW

END MODULE TRGL_VIEW_MOD
