! (C) Copyright 2000- ECMWF.
! (C) Copyright 2000- Meteo-France.
! 
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.
!
SUBROUTINE DIR_TRANS_ISP(PSPVOR,PSPDIV,PSPSCALAR,PSPSC3A,PSPSC3B,PSPSC2,&
& LDLATLON,KPROMA,KVSETUV,KVSETSC,KRESOL,KVSETSC3A,KVSETSC3B,KVSETSC2,&
& PGP,PGPUV,PGP3A,PGP3B,PGP2,PRECBACKEND_FLAG)

USE EC_PARKIND  ,ONLY : JPIM,JPRM 
#ifdef ACCGPU
USE ECTRANS_MOD_VER_SP_GPU, ONLY : DIR_TRANS_VER_SP_GPU
#else
USE ECTRANS_MOD_VER_SP, ONLY : DIR_TRANS_VER_SP 
#endif
REAL(KIND=JPRM)    ,OPTIONAL, INTENT(OUT) :: PSPVOR(:,:)
REAL(KIND=JPRM)    ,OPTIONAL, INTENT(OUT) :: PSPDIV(:,:)
REAL(KIND=JPRM)    ,OPTIONAL, INTENT(OUT) :: PSPSCALAR(:,:)
REAL(KIND=JPRM)    ,OPTIONAL, INTENT(OUT) :: PSPSC3A(:,:,:)
REAL(KIND=JPRM)    ,OPTIONAL, INTENT(OUT) :: PSPSC3B(:,:,:)
REAL(KIND=JPRM)    ,OPTIONAL, INTENT(OUT) :: PSPSC2(:,:)
INTEGER(KIND=JPIM) ,OPTIONAL, INTENT(IN):: KPROMA
INTEGER(KIND=JPIM) ,OPTIONAL, INTENT(IN):: KVSETUV(:)
INTEGER(KIND=JPIM) ,OPTIONAL, INTENT(IN):: KVSETSC(:)
INTEGER(KIND=JPIM) ,OPTIONAL, INTENT(IN):: KVSETSC3A(:)
INTEGER(KIND=JPIM) ,OPTIONAL, INTENT(IN):: KVSETSC3B(:)
INTEGER(KIND=JPIM) ,OPTIONAL, INTENT(IN):: KVSETSC2(:)
INTEGER(KIND=JPIM) ,OPTIONAL, INTENT(IN):: KRESOL
LOGICAL   ,OPTIONAL, INTENT(IN)  :: LDLATLON
REAL(KIND=JPRM),OPTIONAL,INTENT(IN)     :: PGP(:,:,:)
REAL(KIND=JPRM),OPTIONAL,INTENT(IN)     :: PGPUV(:,:,:,:)
REAL(KIND=JPRM),OPTIONAL,INTENT(IN)     :: PGP3A(:,:,:,:)
REAL(KIND=JPRM),OPTIONAL,INTENT(IN)     :: PGP3B(:,:,:,:)
REAL(KIND=JPRM),OPTIONAL,INTENT(IN)     :: PGP2(:,:,:)
REAL(KIND=JPRM),INTENT(IN)     :: PRECBACKEND_FLAG
#ifdef ACCGPU
CALL DIR_TRANS_VER_SP_GPU &
#else
CALL DIR_TRANS_VER_SP &
#endif
(PSPVOR,PSPDIV,PSPSCALAR,PSPSC3A,PSPSC3B,PSPSC2,&
& LDLATLON,KPROMA,KVSETUV,KVSETSC,KRESOL,KVSETSC3A,KVSETSC3B,KVSETSC2,&
& PGP,PGPUV,PGP3A,PGP3B,PGP2)
END SUBROUTINE DIR_TRANS_ISP

SUBROUTINE DIR_TRANS_IDP(PSPVOR,PSPDIV,PSPSCALAR,PSPSC3A,PSPSC3B,PSPSC2,&
& LDLATLON,KPROMA,KVSETUV,KVSETSC,KRESOL,KVSETSC3A,KVSETSC3B,KVSETSC2,&
& PGP,PGPUV,PGP3A,PGP3B,PGP2,PRECBACKEND_FLAG)

USE EC_PARKIND  ,ONLY : JPIM,JPRD 
#ifdef ACCGPU
USE ECTRANS_MOD_VER_DP_GPU, ONLY : DIR_TRANS_VER_DP_GPU
#else
USE ECTRANS_MOD_VER_DP, ONLY : DIR_TRANS_VER_DP
#endif
REAL(KIND=JPRD)    ,OPTIONAL, INTENT(OUT) :: PSPVOR(:,:)
REAL(KIND=JPRD)    ,OPTIONAL, INTENT(OUT) :: PSPDIV(:,:)
REAL(KIND=JPRD)    ,OPTIONAL, INTENT(OUT) :: PSPSCALAR(:,:)
REAL(KIND=JPRD)    ,OPTIONAL, INTENT(OUT) :: PSPSC3A(:,:,:)
REAL(KIND=JPRD)    ,OPTIONAL, INTENT(OUT) :: PSPSC3B(:,:,:)
REAL(KIND=JPRD)    ,OPTIONAL, INTENT(OUT) :: PSPSC2(:,:)
INTEGER(KIND=JPIM) ,OPTIONAL, INTENT(IN):: KPROMA
INTEGER(KIND=JPIM) ,OPTIONAL, INTENT(IN):: KVSETUV(:)
INTEGER(KIND=JPIM) ,OPTIONAL, INTENT(IN):: KVSETSC(:)
INTEGER(KIND=JPIM) ,OPTIONAL, INTENT(IN):: KVSETSC3A(:)
INTEGER(KIND=JPIM) ,OPTIONAL, INTENT(IN):: KVSETSC3B(:)
INTEGER(KIND=JPIM) ,OPTIONAL, INTENT(IN):: KVSETSC2(:)
INTEGER(KIND=JPIM) ,OPTIONAL, INTENT(IN):: KRESOL
LOGICAL   ,OPTIONAL, INTENT(IN)  :: LDLATLON
REAL(KIND=JPRD),OPTIONAL,INTENT(IN)     :: PGP(:,:,:)
REAL(KIND=JPRD),OPTIONAL,INTENT(IN)     :: PGPUV(:,:,:,:)
REAL(KIND=JPRD),OPTIONAL,INTENT(IN)     :: PGP3A(:,:,:,:)
REAL(KIND=JPRD),OPTIONAL,INTENT(IN)     :: PGP3B(:,:,:,:)
REAL(KIND=JPRD),OPTIONAL,INTENT(IN)     :: PGP2(:,:,:)
REAL(KIND=JPRD),INTENT(IN)     :: PRECBACKEND_FLAG
#ifdef ACCGPU
CALL DIR_TRANS_VER_DP_GPU &
#else
CALL DIR_TRANS_VER_DP &
#endif
(PSPVOR,PSPDIV,PSPSCALAR,PSPSC3A,PSPSC3B,PSPSC2,&
& LDLATLON,KPROMA,KVSETUV,KVSETSC,KRESOL,KVSETSC3A,KVSETSC3B,KVSETSC2,&
& PGP,PGPUV,PGP3A,PGP3B,PGP2)
END SUBROUTINE DIR_TRANS_IDP
