MODULE CUDA_GEMM_BATCHED_MOD
  USE PARKIND1, ONLY: JPRD, JPRM, JPIM
  USE CUBLAS, ONLY: CUBLAS_OP_N, CUBLAS_OP_T
  USE ISO_C_BINDING

  IMPLICIT NONE

  PRIVATE
  PUBLIC CUBLAS_OP_N, CUBLAS_OP_T
  PUBLIC CUDA_GEMM_BATCHED

  INTERFACE CUDA_GEMM_BATCHED
    MODULE PROCEDURE CUDA_DGEMM_BATCHED_OVERLOAD
    MODULE PROCEDURE CUDA_SGEMM_BATCHED_OVERLOAD
    MODULE PROCEDURE CUDA_DGEMM_GROUPED_OVERLOAD
    MODULE PROCEDURE CUDA_SGEMM_GROUPED_OVERLOAD
  END INTERFACE CUDA_GEMM_BATCHED

  INTERFACE
    SUBROUTINE CUDA_SGEMM_BATCHED(&
        & CTA, CTB,               &
        & M, N, K,                &
        & ALPHA,                  &
        & A, LDA, TDA,            &
        & B, LDB, TDB,            &
        & BETA,                   &
        & C, LDC, TDC,            &
        & BATCHCOUNT              &
    &) BIND(C, NAME='cublas_sgemm_wrapper')
        USE ISO_C_BINDING
        INTEGER(C_INT), VALUE :: CTA, CTB, M, N, K, LDA, LDB, LDC, TDA, TDB, TDC, BATCHCOUNT
        REAL(C_FLOAT), VALUE  :: ALPHA,BETA
        REAL(C_FLOAT)         :: A(*), B(*), C(*)
    END SUBROUTINE CUDA_SGEMM_BATCHED
    SUBROUTINE CUDA_DGEMM_GROUPED(&
        & CTA, CTB,               &
        & M, N, K,                &
        & ALPHA,                  &
        & A, LDA, TDA,            &
        & B, LDB, TDB,            &
        & BETA,                   &
        & C, LDC, TDC,            &
        & BATCHCOUNT              &
    &) BIND(C, NAME='blas_dgemm_wrapper_grouped')
        USE ISO_C_BINDING
        INTEGER(C_INT), VALUE :: CTA, CTB, M, N(:), K(:), LDA, LDB, LDC, TDA, TDB, TDC, BATCHCOUNT
        REAL(C_DOUBLE), VALUE  :: ALPHA,BETA
        REAL(C_DOUBLE)         :: A(*), B(*), C(*)
    END SUBROUTINE CUDA_DGEMM_GROUPED
    SUBROUTINE CUDA_SGEMM_GROUPED(&
        & CTA, CTB,               &
        & M, N, K,                &
        & ALPHA,                  &
        & A, LDA, TDA,            &
        & B, LDB, TDB,            &
        & BETA,                   &
        & C, LDC, TDC,            &
        & BATCHCOUNT              &
    &) BIND(C, NAME='blas_sgemm_wrapper_grouped')
        USE ISO_C_BINDING
        INTEGER(C_INT), VALUE :: CTA, CTB, M, N(:), K(:), LDA, LDB, LDC, TDA, TDB, TDC, BATCHCOUNT
        REAL(C_FLOAT), VALUE  :: ALPHA,BETA
        REAL(C_FLOAT)         :: A(*), B(*), C(*)
    END SUBROUTINE CUDA_SGEMM_GROUPED
    SUBROUTINE CUDA_DGEMM_BATCHED(&
        & CTA, CTB,               &
        & M, N, K,                &
        & ALPHA,                  &
        & A, LDA, TDA,            &
        & B, LDB, TDB,            &
        & BETA,                   &
        & C, LDC, TDC,            &
        & BATCHCOUNT              &
    &) BIND(C, NAME='cublas_dgemm_wrapper')
        USE ISO_C_BINDING
        INTEGER(C_INT), VALUE :: CTA, CTB, M, N, K, LDA, LDB, LDC, TDA, TDB, TDC, BATCHCOUNT
        REAL(C_DOUBLE), VALUE :: ALPHA,BETA
        REAL(C_DOUBLE)        :: A(*), B(*), C(*)
    END SUBROUTINE CUDA_DGEMM_BATCHED
  END INTERFACE

CONTAINS

SUBROUTINE CUDA_DGEMM_BATCHED_OVERLOAD( &
      & TRANSA, TRANSB, &
      & M, N, K, &
      & ALPHA, &
      & AARRAY, LDA, STRIDEA, &
      & BARRAY, LDB, STRIDEB, &
      & BETA, &
      & CARRAY, LDC, STRIDEC, &
      & BATCHCOUNT)
    INTEGER(KIND=C_INT), INTENT(IN) :: TRANSA
    INTEGER(KIND=C_INT), INTENT(IN) :: TRANSB
    INTEGER(KIND=JPIM) :: M
    INTEGER(KIND=JPIM) :: N
    INTEGER(KIND=JPIM) :: K
    REAL(KIND=JPRD) :: ALPHA
    REAL(KIND=JPRD), DIMENSION(*) :: AARRAY
    INTEGER(KIND=JPIM) :: LDA
    INTEGER(KIND=JPIM) :: STRIDEA
    REAL(KIND=JPRD), DIMENSION(*) :: BARRAY
    INTEGER(KIND=JPIM) :: LDB
    INTEGER(KIND=JPIM) :: STRIDEB
    REAL(KIND=JPRD) :: BETA
    REAL(KIND=JPRD), DIMENSION(*) :: CARRAY
    INTEGER(KIND=JPIM) :: LDC
    INTEGER(KIND=JPIM) :: STRIDEC
    INTEGER(KIND=JPIM) :: BATCHCOUNT

    !$ACC HOST_DATA USE_DEVICE(AARRAY,BARRAY,CARRAY)
    CALL CUDA_DGEMM_BATCHED( &
      & TRANSA, TRANSB, &
      & M, N, K, &
      & ALPHA, &
      & AARRAY, LDA, STRIDEA, &
      & BARRAY, LDB, STRIDEB, &
      & BETA, &
      & CARRAY, LDC, STRIDEC, &
      & BATCHCOUNT)
    !$ACC END HOST_DATA
  END SUBROUTINE CUDA_DGEMM_BATCHED_OVERLOAD

  SUBROUTINE CUDA_SGEMM_BATCHED_OVERLOAD( &
      & TRANSA, TRANSB, &
      & M, N, K, &
      & ALPHA, &
      & AARRAY, LDA, STRIDEA, &
      & BARRAY, LDB, STRIDEB, &
      & BETA, &
      & CARRAY, LDC, STRIDEC, &
      & BATCHCOUNT)
    INTEGER(KIND=C_INT), INTENT(IN) :: TRANSA
    INTEGER(KIND=C_INT), INTENT(IN) :: TRANSB
    INTEGER(KIND=JPIM) :: M
    INTEGER(KIND=JPIM) :: N
    INTEGER(KIND=JPIM) :: K
    REAL(KIND=JPRM) :: ALPHA
    REAL(KIND=JPRM), DIMENSION(*) :: AARRAY
    INTEGER(KIND=JPIM) :: LDA
    INTEGER(KIND=JPIM) :: STRIDEA
    REAL(KIND=JPRM), DIMENSION(*) :: BARRAY
    INTEGER(KIND=JPIM) :: LDB
    INTEGER(KIND=JPIM) :: STRIDEB
    REAL(KIND=JPRM) :: BETA
    REAL(KIND=JPRM), DIMENSION(*) :: CARRAY
    INTEGER(KIND=JPIM) :: LDC
    INTEGER(KIND=JPIM) :: STRIDEC
    INTEGER(KIND=JPIM) :: BATCHCOUNT

    !$ACC HOST_DATA USE_DEVICE(AARRAY,BARRAY,CARRAY)
    CALL CUDA_SGEMM_BATCHED( &
      & TRANSA, TRANSB, &
      & M, N, K, &
      & ALPHA, &
      & AARRAY, LDA, STRIDEA, &
      & BARRAY, LDB, STRIDEB, &
      & BETA, &
      & CARRAY, LDC, STRIDEC, &
      & BATCHCOUNT)
    !$ACC END HOST_DATA
  END SUBROUTINE CUDA_SGEMM_BATCHED_OVERLOAD

  SUBROUTINE CUDA_DGEMM_GROUPED_OVERLOAD( &
      & TRANSA, TRANSB, &
      & M, N, K, &
      & ALPHA, &
      & AARRAY, LDA, STRIDEA, &
      & BARRAY, LDB, STRIDEB, &
      & BETA, &
      & CARRAY, LDC, STRIDEC, &
      & BATCHCOUNT)
    INTEGER(KIND=C_INT), INTENT(IN) :: TRANSA
    INTEGER(KIND=C_INT), INTENT(IN) :: TRANSB
    INTEGER(KIND=JPIM) :: M
    INTEGER(KIND=JPIM) :: N(:)
    INTEGER(KIND=JPIM) :: K(:)
    REAL(KIND=JPRD) :: ALPHA
    REAL(KIND=JPRD), DIMENSION(*) :: AARRAY
    INTEGER(KIND=JPIM) :: LDA
    INTEGER(KIND=JPIM) :: STRIDEA
    REAL(KIND=JPRD), DIMENSION(*) :: BARRAY
    INTEGER(KIND=JPIM) :: LDB
    INTEGER(KIND=JPIM) :: STRIDEB
    REAL(KIND=JPRD) :: BETA
    REAL(KIND=JPRD), DIMENSION(*) :: CARRAY
    INTEGER(KIND=JPIM) :: LDC
    INTEGER(KIND=JPIM) :: STRIDEC
    INTEGER(KIND=JPIM) :: BATCHCOUNT

    !$ACC HOST_DATA USE_DEVICE(AARRAY,BARRAY,CARRAY)
    CALL CUDA_DGEMM_GROUPED( &
      & TRANSA, TRANSB, &
      & M, N, K, &
      & ALPHA, &
      & AARRAY, LDA, STRIDEA, &
      & BARRAY, LDB, STRIDEB, &
      & BETA, &
      & CARRAY, LDC, STRIDEC, &
      & BATCHCOUNT)
    !$ACC END HOST_DATA
  END SUBROUTINE CUDA_DGEMM_GROUPED_OVERLOAD

  SUBROUTINE CUDA_SGEMM_GROUPED_OVERLOAD( &
      & TRANSA, TRANSB, &
      & M, N, K, &
      & ALPHA, &
      & AARRAY, LDA, STRIDEA, &
      & BARRAY, LDB, STRIDEB, &
      & BETA, &
      & CARRAY, LDC, STRIDEC, &
      & BATCHCOUNT)
    INTEGER(KIND=C_INT), INTENT(IN) :: TRANSA
    INTEGER(KIND=C_INT), INTENT(IN) :: TRANSB
    INTEGER(KIND=JPIM) :: M
    INTEGER(KIND=JPIM) :: N(:)
    INTEGER(KIND=JPIM) :: K(:)
    REAL(KIND=JPRM) :: ALPHA
    REAL(KIND=JPRM), DIMENSION(*) :: AARRAY
    INTEGER(KIND=JPIM) :: LDA
    INTEGER(KIND=JPIM) :: STRIDEA
    REAL(KIND=JPRM), DIMENSION(*) :: BARRAY
    INTEGER(KIND=JPIM) :: LDB
    INTEGER(KIND=JPIM) :: STRIDEB
    REAL(KIND=JPRM) :: BETA
    REAL(KIND=JPRM), DIMENSION(*) :: CARRAY
    INTEGER(KIND=JPIM) :: LDC
    INTEGER(KIND=JPIM) :: STRIDEC
    INTEGER(KIND=JPIM) :: BATCHCOUNT

    !$ACC HOST_DATA USE_DEVICE(AARRAY,BARRAY,CARRAY)
    CALL CUDA_SGEMM_GROUPED( &
      & TRANSA, TRANSB, &
      & M, N, K, &
      & ALPHA, &
      & AARRAY, LDA, STRIDEA, &
      & BARRAY, LDB, STRIDEB, &
      & BETA, &
      & CARRAY, LDC, STRIDEC, &
      & BATCHCOUNT)
    !$ACC END HOST_DATA
  END SUBROUTINE CUDA_SGEMM_GROUPED_OVERLOAD

END MODULE CUDA_GEMM_BATCHED_MOD
