! (C) Copyright 2000- ECMWF.
! (C) Copyright 2000- Meteo-France.
! 
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.
!

MODULE TPM_FLT

USE PARKIND_ECTRANS, ONLY: JPIM, JPRBT, JPRD
USE BUTTERFLY_ALG_MOD, ONLY: BUTTERFLY_STRUCT, BUTTERFLY_STRUCT_FLAT
USE SEEFMM_MIX,      ONLY: FMM_TYPE
IMPLICIT NONE

SAVE

TYPE FLT_TYPE
INTEGER(KIND=JPIM) :: NSPOLEGL
INTEGER(KIND=JPIM) :: NDGNH
REAL(KIND=JPRBT) ,POINTER :: RPNMS(:,:) ! Legendre polynomials
REAL(KIND=JPRBT) ,POINTER :: RPNMA(:,:) ! Legendre polynomials
REAL(KIND=JPRD) ,POINTER :: RPNMDS(:,:) ! Legendre polynomials
REAL(KIND=JPRD) ,POINTER :: RPNMDA(:,:) ! Legendre polynomials
REAL(KIND=JPRBT) ,POINTER :: RPNMWI(:,:) ! special weights
REAL(KIND=JPRBT) ,POINTER :: RPNMWO(:,:) ! special weights
INTEGER(KIND=JPIM) :: ISLD ! starting latitude dual

! Butterfly
TYPE(BUTTERFLY_STRUCT) :: YBUT_STRUCT_S, YBUT_STRUCT_A

END TYPE FLT_TYPE

TYPE FLT_TYPE_WRAP
TYPE(FLT_TYPE),ALLOCATABLE :: FA(:)
LOGICAL :: LDLL
LOGICAL :: LSHIFTLL
LOGICAL :: LUSEFLT
LOGICAL :: LUSE_BELUSOV
LOGICAL :: LKEEPRPNM
LOGICAL :: LSOUTHPNM ! .TRUE. to compute Legendre polynomials on southern hemisphere
INTEGER(KIND=JPIM) :: IMLOC
INTEGER(KIND=JPIM) :: ITHRESHOLD
INTEGER(KIND=JPIM) :: NDGNHD ! dual set dimension
INTEGER(KIND=JPIM) :: NDLON  ! dual number of longitudes
INTEGER(KIND=JPIM) :: NDGL   ! dual number of latitudes
TYPE(FMM_TYPE),POINTER :: FMM_INTI ! FMM interpolation

END TYPE FLT_TYPE_WRAP

TYPE(FLT_TYPE_WRAP),ALLOCATABLE,TARGET :: FLT_RESOL(:)
TYPE(FLT_TYPE_WRAP),POINTER     :: S

CONTAINS

SUBROUTINE FLATTEN_BUTTERFLY_STRUCT(YD_FLT, CD_MODE, YD_BUT_FLAT)
! Convert the given butterfly struct (either antisymmetric (CD_MODE="ANTI") or symmetric
! (CD_MODE="SYMM")) into a flattened representation which can be easily copied to GPU.

TYPE(FLT_TYPE), INTENT(IN), TARGET :: YD_FLT(:)
CHARACTER(LEN=4), INTENT(IN) :: CD_MODE
TYPE(BUTTERFLY_STRUCT_FLAT), INTENT(OUT) :: YD_BUT_FLAT

INTEGER(KIND=JPIM) :: NUM_MODES
INTEGER(KIND=JPIM) :: I, J, I_TOTAL, I_TOTAL_NODES
INTEGER(KIND=JPIM) :: JJ, JK, L, IDX, NBASE, IJ_L
TYPE(BUTTERFLY_STRUCT), POINTER :: YL_BUT_STRUCT

NUM_MODES = SIZE(YD_FLT)

ALLOCATE(YD_BUT_FLAT%N_ORDER(NUM_MODES))
ALLOCATE(YD_BUT_FLAT%N_LEVELS(NUM_MODES))
ALLOCATE(YD_BUT_FLAT%IBETALEN_MAX(NUM_MODES))
ALLOCATE(YD_BUT_FLAT%SLEV_OFFSET(NUM_MODES+1))

DO I = 1, NUM_MODES
  IF (CD_MODE == "ANTI") THEN
    YL_BUT_STRUCT => YD_FLT(I)%YBUT_STRUCT_A
  ELSE
    YL_BUT_STRUCT => YD_FLT(I)%YBUT_STRUCT_S
  ENDIF
  YD_BUT_FLAT%N_ORDER(I) = YL_BUT_STRUCT%N_ORDER
  YD_BUT_FLAT%N_LEVELS(I) = YL_BUT_STRUCT%N_LEVELS
  YD_BUT_FLAT%IBETALEN_MAX(I) = YL_BUT_STRUCT%IBETALEN_MAX
ENDDO

YD_BUT_FLAT%SLEV_OFFSET(1) = 0
DO I = 1, NUM_MODES
  YD_BUT_FLAT%SLEV_OFFSET(I+1) = YD_BUT_FLAT%SLEV_OFFSET(I) &
    & + YD_BUT_FLAT%N_LEVELS(I) + 1
ENDDO
I_TOTAL = YD_BUT_FLAT%SLEV_OFFSET(NUM_MODES+1)
ALLOCATE(YD_BUT_FLAT%SLEV_IJ(I_TOTAL))
ALLOCATE(YD_BUT_FLAT%SLEV_IK(I_TOTAL))
ALLOCATE(YD_BUT_FLAT%SLEV_IBETALEN(I_TOTAL))

DO I = 1, NUM_MODES
  IF (CD_MODE == "ANTI") THEN
    YL_BUT_STRUCT => YD_FLT(I)%YBUT_STRUCT_A
  ELSE
    YL_BUT_STRUCT => YD_FLT(I)%YBUT_STRUCT_S
  ENDIF
  DO J = 0, YL_BUT_STRUCT%N_LEVELS
    YD_BUT_FLAT%SLEV_IJ(YD_BUT_FLAT%SLEV_OFFSET(I)+J+1) = YL_BUT_STRUCT%SLEV(J)%IJ
    YD_BUT_FLAT%SLEV_IK(YD_BUT_FLAT%SLEV_OFFSET(I)+J+1) = YL_BUT_STRUCT%SLEV(J)%IK
    YD_BUT_FLAT%SLEV_IBETALEN(YD_BUT_FLAT%SLEV_OFFSET(I)+J+1) = YL_BUT_STRUCT%SLEV(J)%IBETALEN
  ENDDO
ENDDO

! Per-level node offsets: prefix sum over all level slots, IJ*IK nodes per slot
ALLOCATE(YD_BUT_FLAT%SLEV_NODE_OFFSET(I_TOTAL+1))
YD_BUT_FLAT%SLEV_NODE_OFFSET(1) = 0
DO L = 1, I_TOTAL
  YD_BUT_FLAT%SLEV_NODE_OFFSET(L+1) = YD_BUT_FLAT%SLEV_NODE_OFFSET(L) &
    & + YD_BUT_FLAT%SLEV_IJ(L) * YD_BUT_FLAT%SLEV_IK(L)
ENDDO
I_TOTAL_NODES = YD_BUT_FLAT%SLEV_NODE_OFFSET(I_TOTAL+1)
ALLOCATE(YD_BUT_FLAT%SLEV_NODE_IFCOL(I_TOTAL_NODES))
ALLOCATE(YD_BUT_FLAT%SLEV_NODE_ILCOL(I_TOTAL_NODES))
ALLOCATE(YD_BUT_FLAT%SLEV_NODE_IFROW(I_TOTAL_NODES))
ALLOCATE(YD_BUT_FLAT%SLEV_NODE_ILROW(I_TOTAL_NODES))
ALLOCATE(YD_BUT_FLAT%SLEV_NODE_ICOLS(I_TOTAL_NODES))
ALLOCATE(YD_BUT_FLAT%SLEV_NODE_IROWS(I_TOTAL_NODES))
ALLOCATE(YD_BUT_FLAT%SLEV_NODE_IRANK(I_TOTAL_NODES))
ALLOCATE(YD_BUT_FLAT%SLEV_NODE_IOFFBETA(I_TOTAL_NODES))

DO I = 1, NUM_MODES
  IF (CD_MODE == "ANTI") THEN
    YL_BUT_STRUCT => YD_FLT(I)%YBUT_STRUCT_A
  ELSE
    YL_BUT_STRUCT => YD_FLT(I)%YBUT_STRUCT_S
  ENDIF
  DO J = 0, YL_BUT_STRUCT%N_LEVELS
    L = YD_BUT_FLAT%SLEV_OFFSET(I) + J + 1
    NBASE = YD_BUT_FLAT%SLEV_NODE_OFFSET(L)
    IJ_L = YL_BUT_STRUCT%SLEV(J)%IJ
    DO JK = 1, YL_BUT_STRUCT%SLEV(J)%IK
      DO JJ = 1, IJ_L
        ! Column-major linearisation of NODE(JJ,JK), matching Fortran storage
        IDX = NBASE + (JK-1)*IJ_L + JJ
        ASSOCIATE(YN => YL_BUT_STRUCT%SLEV(J)%NODE(JJ,JK))
        YD_BUT_FLAT%SLEV_NODE_IFCOL(IDX)    = YN%IFCOL
        YD_BUT_FLAT%SLEV_NODE_ILCOL(IDX)    = YN%ILCOL
        YD_BUT_FLAT%SLEV_NODE_IFROW(IDX)    = YN%IFROW
        YD_BUT_FLAT%SLEV_NODE_ILROW(IDX)    = YN%ILROW
        YD_BUT_FLAT%SLEV_NODE_ICOLS(IDX)    = YN%ICOLS
        YD_BUT_FLAT%SLEV_NODE_IROWS(IDX)    = YN%IROWS
        YD_BUT_FLAT%SLEV_NODE_IRANK(IDX)    = YN%IRANK
        YD_BUT_FLAT%SLEV_NODE_IOFFBETA(IDX) = YN%IOFFBETA
        END ASSOCIATE
      ENDDO
    ENDDO
  ENDDO
ENDDO

END SUBROUTINE FLATTEN_BUTTERFLY_STRUCT

END MODULE TPM_FLT
