! (C) Copyright 2014- ECMWF.
! (C) Copyright 2022- NVIDIA.
! 
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.
!

MODULE TPM_FFTC

!   Author.
!   -------
!     George Mozdzynski
!
!   Modifications.
!   -------------- 
!     Original      October 2014

USE, INTRINSIC :: ISO_C_BINDING

IMPLICIT NONE

SAVE

PRIVATE
PUBLIC EXECUTE_DIR_FFT, EXECUTE_INV_FFT

INTERFACE EXECUTE_DIR_FFT
  SUBROUTINE EXECUTE_DIR_FFT_FLOAT(PREEL_REAL,PREEL_COMPLEX,KFIELD,LOENS,OFFSETS)
    USE PARKIND_ECTRANS ,ONLY : JPIM
    USE ISO_C_BINDING
    IMPLICIT NONE
    REAL(KIND=C_FLOAT), INTENT(IN) :: PREEL_REAL(:)
    REAL(KIND=C_FLOAT), INTENT(OUT) :: PREEL_COMPLEX(:)
    INTEGER(KIND=JPIM),INTENT(IN)  :: KFIELD
    INTEGER(KIND=JPIM),INTENT(IN)  :: LOENS(:), OFFSETS(:)
  END SUBROUTINE
  SUBROUTINE EXECUTE_DIR_FFT_DOUBLE(PREEL_REAL,PREEL_COMPLEX,KFIELD,LOENS,OFFSETS)
    USE PARKIND_ECTRANS ,ONLY : JPIM
    USE ISO_C_BINDING
    IMPLICIT NONE
    REAL(KIND=C_DOUBLE), INTENT(IN) :: PREEL_REAL(:)
    REAL(KIND=C_DOUBLE), INTENT(OUT) :: PREEL_COMPLEX(:)
    INTEGER(KIND=JPIM),INTENT(IN)  :: KFIELD
    INTEGER(KIND=JPIM),INTENT(IN)  :: LOENS(:), OFFSETS(:)
  END SUBROUTINE
END INTERFACE

INTERFACE EXECUTE_INV_FFT
  SUBROUTINE EXECUTE_INV_FFT_FLOAT(PREEL_COMPLEX,PREEL_REAL,KFIELD,LOENS,OFFSETS)
    USE PARKIND_ECTRANS ,ONLY : JPIM
    USE ISO_C_BINDING
    IMPLICIT NONE
    REAL(KIND=C_FLOAT), INTENT(IN) :: PREEL_COMPLEX(:)
    REAL(KIND=C_FLOAT), INTENT(OUT) :: PREEL_REAL(:)
    INTEGER(KIND=JPIM),INTENT(IN)  :: KFIELD
    INTEGER(KIND=JPIM),INTENT(IN)  :: LOENS(:), OFFSETS(:)
  END SUBROUTINE
  SUBROUTINE EXECUTE_INV_FFT_DOUBLE(PREEL_COMPLEX,PREEL_REAL,KFIELD,LOENS,OFFSETS)
    USE PARKIND_ECTRANS ,ONLY : JPIM
    USE ISO_C_BINDING
    IMPLICIT NONE
    REAL(KIND=C_DOUBLE), INTENT(IN) :: PREEL_COMPLEX(:)
    REAL(KIND=C_DOUBLE), INTENT(OUT) :: PREEL_REAL(:)
    INTEGER(KIND=JPIM),INTENT(IN)  :: KFIELD
    INTEGER(KIND=JPIM),INTENT(IN)  :: LOENS(:), OFFSETS(:)
  END SUBROUTINE
END INTERFACE


! ------------------------------------------------------------------
CONTAINS
! ------------------------------------------------------------------

SUBROUTINE EXECUTE_DIR_FFT_FLOAT(PREEL_REAL,PREEL_COMPLEX,KFIELD,LOENS,OFFSETS)
  USE PARKIND_ECTRANS ,ONLY : JPIM

  IMPLICIT NONE

  REAL(KIND=C_FLOAT), INTENT(IN) :: PREEL_REAL(:)
  REAL(KIND=C_FLOAT), INTENT(OUT) :: PREEL_COMPLEX(:)
  INTEGER(KIND=JPIM),INTENT(IN)  :: KFIELD
  INTEGER(KIND=JPIM),INTENT(IN)  :: LOENS(:), OFFSETS(:)
  INTERFACE
    SUBROUTINE EXECUTE_DIR_FFT_FLOAT_C(PREEL_REAL,PREEL_COMPLEX,KFIELD,LOENS,OFFSETS,NFFT) BIND(C, name="execute_dir_fft_float")
      USE ISO_C_BINDING
      REAL(KIND=C_FLOAT), INTENT(IN) :: PREEL_REAL(:)
      REAL(KIND=C_FLOAT), INTENT(OUT) :: PREEL_COMPLEX(:)
      INTEGER(KIND=C_INT),INTENT(IN),VALUE  :: KFIELD
      INTEGER(KIND=C_INT),INTENT(IN)  :: LOENS(:), OFFSETS(:)
      INTEGER(KIND=C_INT),INTENT(IN),VALUE :: NFFT
    END SUBROUTINE
  END INTERFACE

  !$ACC HOST_DATA USE_DEVICE(PREEL_REAL,PREEL_COMPLEX)
  CALL EXECUTE_DIR_FFT_FLOAT_C(PREEL_REAL,PREEL_COMPLEX,KFIELD,LOENS,OFFSETS,SIZE(LOENS))
  !$ACC END HOST_DATA

END SUBROUTINE
SUBROUTINE EXECUTE_DIR_FFT_DOUBLE(PREEL_REAL,PREEL_COMPLEX,KFIELD,LOENS,OFFSETS)
  USE PARKIND_ECTRANS ,ONLY : JPIM

  IMPLICIT NONE

  REAL(KIND=C_DOUBLE), INTENT(IN) :: PREEL_REAL(:)
  REAL(KIND=C_DOUBLE), INTENT(OUT) :: PREEL_COMPLEX(:)
  INTEGER(KIND=JPIM),INTENT(IN)  :: KFIELD
  INTEGER(KIND=JPIM),INTENT(IN)  :: LOENS(:), OFFSETS(:)
  INTERFACE
    SUBROUTINE EXECUTE_DIR_FFT_DOUBLE_C(PREEL_REAL,PREEL_COMPLEX,KFIELD,LOENS,OFFSETS,NFFT) BIND(C, name="execute_dir_fft_double")
      USE ISO_C_BINDING
      REAL(KIND=C_DOUBLE), INTENT(IN) :: PREEL_REAL(:)
      REAL(KIND=C_DOUBLE), INTENT(OUT) :: PREEL_COMPLEX(:)
      INTEGER(KIND=C_INT),INTENT(IN),VALUE  :: KFIELD
      INTEGER(KIND=C_INT),INTENT(IN)  :: LOENS(:), OFFSETS(:)
      INTEGER(KIND=C_INT),INTENT(IN),VALUE :: NFFT
    END SUBROUTINE
  END INTERFACE

  !$ACC HOST_DATA USE_DEVICE(PREEL_REAL,PREEL_COMPLEX)
  CALL EXECUTE_DIR_FFT_DOUBLE_C(PREEL_REAL,PREEL_COMPLEX,KFIELD,LOENS,OFFSETS,SIZE(LOENS))
  !$ACC END HOST_DATA

END SUBROUTINE

SUBROUTINE EXECUTE_INV_FFT_FLOAT(PREEL_COMPLEX,PREEL_REAL,KFIELD,LOENS,OFFSETS)
  USE PARKIND_ECTRANS ,ONLY : JPIM

  IMPLICIT NONE

  REAL(KIND=C_FLOAT), INTENT(IN) :: PREEL_COMPLEX(:)
  REAL(KIND=C_FLOAT), INTENT(OUT) :: PREEL_REAL(:)
  INTEGER(KIND=JPIM),INTENT(IN)  :: KFIELD
  INTEGER(KIND=JPIM),INTENT(IN)  :: LOENS(:), OFFSETS(:)
  INTERFACE
    SUBROUTINE EXECUTE_INV_FFT_FLOAT_C(PREEL_COMPLEX,PREEL_REAL,KFIELD,LOENS,OFFSETS,NFFT) BIND(C, name="execute_inv_fft_float")
      USE ISO_C_BINDING
      REAL(KIND=C_FLOAT), INTENT(IN) :: PREEL_COMPLEX(:)
      REAL(KIND=C_FLOAT), INTENT(OUT) :: PREEL_REAL(:)
      INTEGER(KIND=C_INT),INTENT(IN),VALUE  :: KFIELD
      INTEGER(KIND=C_INT),INTENT(IN)  :: LOENS(:), OFFSETS(:)
      INTEGER(KIND=C_INT),INTENT(IN),VALUE :: NFFT
    END SUBROUTINE
  END INTERFACE

  !$ACC HOST_DATA USE_DEVICE(PREEL_COMPLEX,PREEL_REAL)
  CALL EXECUTE_INV_FFT_FLOAT_C(PREEL_COMPLEX,PREEL_REAL,KFIELD,LOENS,OFFSETS,SIZE(LOENS))
  !$ACC END HOST_DATA
END SUBROUTINE

SUBROUTINE EXECUTE_INV_FFT_DOUBLE(PREEL_COMPLEX,PREEL_REAL,KFIELD,LOENS,OFFSETS)
  USE PARKIND_ECTRANS ,ONLY : JPIM

  IMPLICIT NONE

  REAL(KIND=C_DOUBLE), INTENT(IN) :: PREEL_COMPLEX(:)
  REAL(KIND=C_DOUBLE), INTENT(OUT) :: PREEL_REAL(:)
  INTEGER(KIND=JPIM),INTENT(IN)  :: KFIELD
  INTEGER(KIND=JPIM),INTENT(IN)  :: LOENS(:), OFFSETS(:)
  INTERFACE
    SUBROUTINE EXECUTE_INV_FFT_DOUBLE_C(PREEL_COMPLEX,PREEL_REAL,KFIELD,LOENS,OFFSETS,NFFT) BIND(C, name="execute_inv_fft_double")
      USE ISO_C_BINDING
      REAL(KIND=C_DOUBLE), INTENT(IN) :: PREEL_COMPLEX(:)
      REAL(KIND=C_DOUBLE), INTENT(OUT) :: PREEL_REAL(:)
      INTEGER(KIND=C_INT),INTENT(IN),VALUE  :: KFIELD
      INTEGER(KIND=C_INT),INTENT(IN)  :: LOENS(:), OFFSETS(:)
      INTEGER(KIND=C_INT),INTENT(IN),VALUE :: NFFT
    END SUBROUTINE
  END INTERFACE

  !$ACC HOST_DATA USE_DEVICE(PREEL_COMPLEX,PREEL_REAL)
  CALL EXECUTE_INV_FFT_DOUBLE_C(PREEL_COMPLEX,PREEL_REAL,KFIELD,LOENS,OFFSETS,SIZE(LOENS))
  !$ACC END HOST_DATA
END SUBROUTINE

END MODULE TPM_FFTC
