MODULE TPM_CTL

USE PARKIND1  ,ONLY : JPIM     ,JPRBT
USE, INTRINSIC :: iso_c_binding, ONLY:  C_PTR, C_NULL_PTR
USE SHAREDMEM_MOD ,ONLY : SHAREDMEM
IMPLICIT NONE

SAVE


TYPE CTL_TYPE

LOGICAL :: LREAD_LEGPOL = .FALSE.
LOGICAL :: LWRITE_LEGPOL = .FALSE.
CHARACTER(LEN=256) :: CLEGPOLFNAME='legpol_file'
CHARACTER(LEN=4) :: CIO_TYPE='file'
TYPE(SHAREDMEM) :: STORAGE

END TYPE CTL_TYPE


TYPE(CTL_TYPE),ALLOCATABLE,TARGET :: CTL_RESOL(:)
TYPE(CTL_TYPE),POINTER     :: C


END MODULE TPM_CTL







