! (C) Copyright 2000- ECMWF.
! (C) Copyright 2000- Meteo-France.
! 
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.
!

MODULE TPM_FLT

USE PARKIND_ECTRANS, ONLY: JPIM, JPRBT, JPRD
USE BUTTERFLY_ALG_MOD, ONLY: BUTTERFLY_STRUCT, BUTTERFLY_STRUCT_FLAT
USE SEEFMM_MIX,      ONLY: FMM_TYPE
IMPLICIT NONE

SAVE

TYPE FLT_TYPE
INTEGER(KIND=JPIM) :: NSPOLEGL
INTEGER(KIND=JPIM) :: NDGNH
REAL(KIND=JPRBT) ,POINTER :: RPNMS(:,:) ! Legendre polynomials
REAL(KIND=JPRBT) ,POINTER :: RPNMA(:,:) ! Legendre polynomials
REAL(KIND=JPRD) ,POINTER :: RPNMDS(:,:) ! Legendre polynomials
REAL(KIND=JPRD) ,POINTER :: RPNMDA(:,:) ! Legendre polynomials
REAL(KIND=JPRBT) ,POINTER :: RPNMWI(:,:) ! special weights
REAL(KIND=JPRBT) ,POINTER :: RPNMWO(:,:) ! special weights
INTEGER(KIND=JPIM) :: ISLD ! starting latitude dual

! Butterfly
TYPE(BUTTERFLY_STRUCT) :: YBUT_STRUCT_S, YBUT_STRUCT_A

END TYPE FLT_TYPE

TYPE FLT_TYPE_WRAP
TYPE(FLT_TYPE),ALLOCATABLE :: FA(:)
LOGICAL :: LDLL
LOGICAL :: LSHIFTLL
LOGICAL :: LUSEFLT
LOGICAL :: LUSE_BELUSOV
LOGICAL :: LKEEPRPNM
LOGICAL :: LSOUTHPNM ! .TRUE. to compute Legendre polynomials on southern hemisphere
INTEGER(KIND=JPIM) :: IMLOC
INTEGER(KIND=JPIM) :: ITHRESHOLD
INTEGER(KIND=JPIM) :: NDGNHD ! dual set dimension
INTEGER(KIND=JPIM) :: NDLON  ! dual number of longitudes
INTEGER(KIND=JPIM) :: NDGL   ! dual number of latitudes
TYPE(FMM_TYPE),POINTER :: FMM_INTI ! FMM interpolation

END TYPE FLT_TYPE_WRAP

TYPE(FLT_TYPE_WRAP),ALLOCATABLE,TARGET :: FLT_RESOL(:)
TYPE(FLT_TYPE_WRAP),POINTER     :: S

CONTAINS

SUBROUTINE FLATTEN_BUTTERFLY_STRUCT(YD_FLT, CD_MODE, YD_BUTTERFLY_FLAT)

TYPE(FLT_TYPE), INTENT(IN), TARGET :: YD_FLT(:)
CHARACTER(LEN=4), INTENT(IN) :: CD_MODE
TYPE(BUTTERFLY_STRUCT_FLAT), INTENT(OUT) :: YD_BUTTERFLY_FLAT

INTEGER(KIND=JPIM) :: NUM_MODES
INTEGER(KIND=JPIM) :: I
TYPE(BUTTERFLY_STRUCT), POINTER :: YL_BUT_STRUCT

NUM_MODES = SIZE(YD_FLT)

ALLOCATE(YD_BUTTERFLY_FLAT%N_ORDER(NUM_MODES))
ALLOCATE(YD_BUTTERFLY_FLAT%N_LEVELS(NUM_MODES))
ALLOCATE(YD_BUTTERFLY_FLAT%IBETALEN_MAX(NUM_MODES))

DO I = 1, NUM_MODES
  IF (CD_MODE == "ANTI") THEN
    YL_BUT_STRUCT => YD_FLT(I)%YBUT_STRUCT_A
  ELSE
    YL_BUT_STRUCT => YD_FLT(I)%YBUT_STRUCT_S
  ENDIF
  YD_BUTTERFLY_FLAT%N_ORDER(I) = YL_BUT_STRUCT%N_ORDER
  YD_BUTTERFLY_FLAT%N_LEVELS(I) = YL_BUT_STRUCT%N_LEVELS
  YD_BUTTERFLY_FLAT%IBETALEN_MAX(I) = YL_BUT_STRUCT%IBETALEN_MAX
ENDDO

END SUBROUTINE FLATTEN_BUTTERFLY_STRUCT

END MODULE TPM_FLT
