MODULE ABORT_TRANS_MOD
CONTAINS
SUBROUTINE ABORT_TRANS(CDTEXT)

#include "tsmbkind.h"

USE TPM_GEN  , ONLY : NOUT,NERR
USE TPM_DISTR, ONLY : NPROC,MYPROC
USE MPL_MODULE


IMPLICIT NONE


CHARACTER(LEN=*) :: CDTEXT

!     LOCAL INTEGER SCALARS
INTEGER_M :: ILEN

ILEN=LEN(CDTEXT)
WRITE(NOUT,'(1X,A)') 'ABORT_TRANS CALLED'

IF(ILEN <= 512) THEN
  WRITE(NOUT,'(1X,A)') CDTEXT
  WRITE(NERR,'(1X,A,1X,I3,1X,A)') 'ABORT!! ',MYPROC,CDTEXT
ELSE
  WRITE(NERR,'(1X,A,1X,I3,1X,A)') 'ABORT!! ',MYPROC,&
   &'ABORT_TRANS CALLED WITHOUT TEXT STRING'
ENDIF
CLOSE(NOUT)
IF (NPROC > 1) THEN
  IF(ILEN <= 512) THEN
    CALL MPL_ABORT(CDTEXT)
  ELSE
    CALL MPL_ABORT
  ENDIF
ELSE
#ifdef VPP
  CALL ERRTRA
#endif
#ifdef RS6K
  CALL XL__TRBK
  CALL FLUSH(0)
#endif
ENDIF

#ifdef SX4
CALL MESPUT(CDTEXT,LEN(CDTEXT),1)
CALL EXIT
#else
CALL ABORT
STOP 2
#endif

END SUBROUTINE ABORT_TRANS
END MODULE ABORT_TRANS_MOD
