MODULE FOURIER_OUT_MOD
CONTAINS
SUBROUTINE FOURIER_OUT(PREEL,KFIELDS)

#include "tsmbkind.h"

USE TPM_DISTR
USE TPM_TRANS
USE TPM_GEOMETRY

IMPLICIT NONE

REAL_B,   INTENT(IN) :: PREEL(:,:)
INTEGER_M,INTENT(IN) :: KFIELDS

INTEGER_M :: JGL,JM,JF,IGLG,IPROC,IR,II,ISTA

!     ------------------------------------------------------------------

!$OMP PARALLEL PRIVATE(JGL,ISTADR,ISTGB,ILAT)
!$OMP DO SCHEDULE(STATIC,1)
DO JGL=1,D%NDGL_FS
  IGLG = D%NPTRLS(MYSETW)+JGL-1
  DO JM=0,G%NMEN(IGLG)
    IPROC = D%NPROCM(JM)
    IR    = 2*JM+1+D%NSTAGTF(JGL)
    II    = 2*JM+2+D%NSTAGTF(JGL)
    ISTA  = (D%NSTAGT1B(D%MSTABF(IPROC))+D%NPNTGTB0(JM,JGL))*2*KFIELDS
    DO JF=1,KFIELDS
      FOUBUF_IN(ISTA+2*JF-1) = PREEL(JF,IR)
      FOUBUF_IN(ISTA+2*JF  ) = PREEL(JF,II)
    ENDDO
  ENDDO
ENDDO
!$OMP END DO
!$OMP END PARALLEL

!     ------------------------------------------------------------------

END SUBROUTINE FOURIER_OUT
END MODULE FOURIER_OUT_MOD

