MODULE FSPGL_INT_MOD
CONTAINS
SUBROUTINE FSPGL_INT(KM,KMLOC,FSPGL_PROC)

#include "tsmbkind.h"

USE TPM_DIM
USE TPM_TRANS
USE TPM_GEOMETRY
USE TPM_DISTR

IMPLICIT NONE

INTEGER_M, INTENT(IN) :: KM
INTEGER_M, INTENT(IN) :: KMLOC
EXTERNAL  FSPGL_PROC

REAL_B :: ZFIELD(R%NDGL,2*NF_OUT_LT)


INTEGER_M :: ISL, IGLS, JFLD, JGL ,IPROC, ISTAN, IPROCS, ISTAS

!     ------------------------------------------------------------------

ISL = MAX(R%NDGNH-G%NDGLU(KM)+1,1)
DO JGL=ISL,R%NDGNH
  IPROC = D%NPROCL(JGL)
  ISTAN = (D%NSTAGT0B(IPROC) + D%NPNTGTB1(KMLOC,JGL))*2*NF_OUT_LT
  IGLS = R%NDGL+1-JGL
  IPROCS = D%NPROCL(IGLS)
  ISTAS = (D%NSTAGT0B(IPROCS) + D%NPNTGTB1(KMLOC,IGLS))*2*NF_OUT_LT
  DO JFLD=1,2*NF_OUT_LT
    ZFIELD(JGL ,JFLD) = FOUBUF_IN(ISTAN+JFLD)
    ZFIELD(IGLS,JFLD) = FOUBUF_IN(ISTAS+JFLD)
  ENDDO
ENDDO

CALL FSPGL_PROC(KM,KMLOC,ISL,NF_OUT_LT,ZFIELD)

DO JGL=ISL,R%NDGNH
  IPROC = D%NPROCL(JGL)
  ISTAN = (D%NSTAGT0B(IPROC) + D%NPNTGTB1(KMLOC,JGL))*2*NF_OUT_LT
  IGLS = R%NDGL+1-JGL
  IPROCS = D%NPROCL(IGLS)
  ISTAS = (D%NSTAGT0B(IPROCS) + D%NPNTGTB1(KMLOC,IGLS))*2*NF_OUT_LT
  DO JFLD=1,2*NF_OUT_LT
    FOUBUF_IN(ISTAN+JFLD) = ZFIELD(JGL ,JFLD)
    FOUBUF_IN(ISTAS+JFLD) = ZFIELD(IGLS,JFLD)
  ENDDO
ENDDO

!     ------------------------------------------------------------------

END SUBROUTINE FSPGL_INT
END MODULE FSPGL_INT_MOD

