MODULE FTDIR_CONTROL_MOD
CONTAINS
SUBROUTINE FTDIR_CONTROL(PGP,KVSETUV,KVSETSC)

#include "tsmbkind.h"

USE TPM_GEN
USE TPM_DIM
USE TPM_GEOMETRY
USE TPM_TRANS
USE TPM_DISTR

USE TRGTOL_MOD
USE FOURIER_OUT_MOD
USE FTDIR_MOD

IMPLICIT NONE

REAL_B , INTENT(IN) :: PGP(:,:,:)
INTEGER_M ,OPTIONAL, INTENT(IN) :: KVSETUV(:)
INTEGER_M ,OPTIONAL, INTENT(IN) :: KVSETSC(:)

REAL_B :: ZGTF(NF_FS,D%NLENGTF)

INTEGER_M :: IST
INTEGER_M :: IVSETUV(NF_UV_G)
INTEGER_M :: IVSETSC(NF_SCALARS_G)
INTEGER_M :: IVSET(NF_GP)

!     ------------------------------------------------------------------

IF(PRESENT(KVSETUV)) THEN
  IVSETUV(:) = KVSETUV(:)
ELSE
  IVSETUV(:) = -1
ENDIF
IF(PRESENT(KVSETSC)) THEN
  IVSETSC(:) = KVSETSC(:)
ELSE
  IVSETSC(:) = -1
ENDIF

IST = 1
IF(NF_UV_G > 0) THEN
  IVSET(IST:IST+NF_UV_G-1) = IVSETUV(:)
  IST = IST+NF_UV_G
  IVSET(IST:IST+NF_UV_G-1) = IVSETUV(:)
  IST = IST+NF_UV_G
ENDIF
IF(NF_SCALARS_G > 0) THEN
  IVSET(IST:IST+NF_SCALARS_G-1) = IVSETSC(:)
  IST = IST+NF_SCALARS_G
ENDIF

CALL TRGTOL(ZGTF,PGP,IVSET)

CALL FTDIR(ZGTF,NF_FS)

ALLOCATE(FOUBUF_IN(D%NLENGT0B*2*NF_FS))
CALL FOURIER_OUT(ZGTF,NF_FS)

!     ------------------------------------------------------------------

END SUBROUTINE FTDIR_CONTROL
END MODULE FTDIR_CONTROL_MOD




