MODULE FTINV_MOD
CONTAINS
SUBROUTINE FTINV(PREEL,KFIELDS)

#include "tsmbkind.h"

USE TPM_DISTR
USE TPM_TRANS
USE TPM_GEOMETRY
USE TPM_FFT

IMPLICIT NONE

INTEGER_M,INTENT(IN) :: KFIELDS

REAL_B, INTENT(OUT) :: PREEL(:,:)

INTEGER_M :: JGL,IGLG,IST,ILEN,IJUMP,JJ,JF

!$OMP PARALLEL DO SCHEDULE(STATIC,1) PRIVATE(JGL,IST,ILEN,IJUMP,JJ,PWORK)
DO JGL=1,D%NDGL_FS
  IGLG = D%NPTRLS(MYSETW)+JGL-1
  IST = 2*(G%NMEN(IGLG)+1)+1
  ILEN = G%NLOEN(IGLG)+3-IST
  IJUMP = 1

  DO JJ=1,ILEN
    DO JF=1,KFIELDS
      PREEL(JF,IST+D%NSTAGTF(JGL)+JJ-1) = _ZERO_
    ENDDO
  ENDDO
  
  CALL FFT992(PREEL(1,D%NSTAGTF(JGL)+1),T%TRIGS(1,JGL),&
   &T%NFAX(1,JGL),KFIELDS,IJUMP,G%NLOEN(IGLG),KFIELDS,1)

ENDDO
!$OMP END PARALLEL DO

END SUBROUTINE FTINV
END MODULE FTINV_MOD
