MODULE FTINV_CONTROL_MOD
CONTAINS
SUBROUTINE FTINV_CONTROL(PGP,KVSETUV,KVSETSC)

#include "tsmbkind.h"

USE TPM_GEN
USE TPM_DIM
USE TPM_GEOMETRY
USE TPM_TRANS
USE TPM_DISTR

USE FOURIER_IN_MOD
USE FSC_MOD
USE FTINV_MOD
USE TRLTOG_MOD

IMPLICIT NONE

REAL_B , INTENT(OUT) :: PGP(:,:,:)
INTEGER_M ,OPTIONAL, INTENT(IN) :: KVSETUV(:)
INTEGER_M ,OPTIONAL, INTENT(IN) :: KVSETSC(:)

REAL_B,TARGET :: ZGTF(NF_FS,D%NLENGTF)
REAL_B,POINTER :: ZUV(:,:)
REAL_B,POINTER :: ZSCALAR(:,:)
REAL_B,POINTER :: ZNSDERS(:,:)
REAL_B,POINTER :: ZEWDERS(:,:)
REAL_B,POINTER :: ZUVDERS(:,:)

INTEGER_M :: IST
INTEGER_M :: IVSETUV(NF_UV_G)
INTEGER_M :: IVSETSC(NF_SCALARS_G)
INTEGER_M :: IVSET(NF_GP)


CALL FOURIER_IN(ZGTF,NF_OUT_LT)

IST=1
IF(LVORGP) THEN
  IST = IST+NF_UV
ENDIF
IF(LDIVGP) THEN
  IST = IST+NF_UV
ENDIF
ZUV => ZGTF(IST:IST+2*NF_UV-1,:)
IST = IST+2*NF_UV
ZSCALAR => ZGTF(IST:IST+NF_SCALARS-1,:)
IST = IST+NF_SCALARS
ZNSDERS => ZGTF(IST:IST+NF_SCDERS-1,:)
IST = IST+NF_SCDERS
IF(LUVDER) THEN
  ZUVDERS => ZGTF(IST:IST+2*NF_UV-1,:)
  IST = IST+2*NF_UV
ENDIF
ZEWDERS => ZGTF(IST:IST+NF_SCDERS-1,:)

IF(NF_UV > 0 .OR. NF_SCDERS > 0) THEN
  CALL FSC(ZUV,ZSCALAR,ZNSDERS,ZEWDERS,ZUVDERS)
ENDIF

CALL FTINV(ZGTF,NF_FS)

IF(PRESENT(KVSETUV)) THEN
  IVSETUV(:) = KVSETUV(:)
ELSE
  IVSETUV(:) = -1
ENDIF
IF(PRESENT(KVSETSC)) THEN
  IVSETSC(:) = KVSETSC(:)
ELSE
  IVSETSC(:) = -1
ENDIF

IST = 1
IF(NF_UV_G > 0) THEN
  IF( LVORGP) THEN
    IVSET(IST:IST+NF_UV_G-1) = IVSETUV(:)
    IST = IST+NF_UV_G
  ENDIF
  IF( LDIVGP) THEN
    IVSET(IST:IST+NF_UV_G-1) = IVSETUV(:)
    IST = IST+NF_UV_G
  ENDIF
  IVSET(IST:IST+NF_UV_G-1) = IVSETUV(:)
  IST = IST+NF_UV_G
  IVSET(IST:IST+NF_UV_G-1) = IVSETUV(:)
  IST = IST+NF_UV_G
ENDIF
IF(NF_SCALARS_G > 0) THEN
  IVSET(IST:IST+NF_SCALARS_G-1) = IVSETSC(:)
  IST = IST+NF_SCALARS_G
  IF(NF_SCDERS > 0) THEN
    IVSET(IST:IST+NF_SCALARS_G-1) = IVSETSC(:)
    IST = IST+NF_SCALARS_G
  ENDIF
ENDIF
IF(NF_UV_G > 0 .AND. LUVDER) THEN
  IVSET(IST:IST+NF_UV_G-1) = IVSETUV(:)
  IST = IST+NF_UV_G
  IVSET(IST:IST+NF_UV_G-1) = IVSETUV(:)
  IST = IST+NF_UV_G
ENDIF
IF(NF_SCALARS_G > 0) THEN
  IF(NF_SCDERS > 0) THEN
    IVSET(IST:IST+NF_SCALARS_G-1) = IVSETSC(:)
    IST = IST+NF_SCALARS_G
  ENDIF
ENDIF

CALL TRLTOG(ZGTF,PGP,IVSET)

DEALLOCATE(FOUBUF)


END SUBROUTINE FTINV_CONTROL
END MODULE FTINV_CONTROL_MOD




