MODULE LTINV_CONTROL_MOD
CONTAINS
SUBROUTINE LTINV_CONTROL(PSPVOR,PSPDIV,PSPSCALAR,FSPGL_PROC)

#include "tsmbkind.h"

USE TPM_DIM
USE TPM_TRANS
USE TPM_DISTR

USE LTINV_MOD
USE TRMTOL_MOD

IMPLICIT NONE

REAL_B ,OPTIONAL, INTENT(IN) :: PSPVOR(:,:)
REAL_B ,OPTIONAL, INTENT(IN) :: PSPDIV(:,:)
REAL_B ,OPTIONAL, INTENT(IN) :: PSPSCALAR(:,:)
EXTERNAL  FSPGL_PROC
OPTIONAL  FSPGL_PROC

INTEGER_M :: JM,IM

NLEI2 = 2*NF_FS
ALLOCATE(FOUBUF_IN(D%NLENGT0B*2*NF_FS))

!$OMP PARALLEL DO SCHEDULE(STATIC,1) PRIVATE(JM,IM)
DO JM=1,D%NUMP
  IM = D%MYMS(JM)
  CALL LTINV(IM,JM,PSPVOR,PSPDIV,PSPSCALAR,FSPGL_PROC)
ENDDO
!$OMP END PARALLEL DO

ALLOCATE(FOUBUF(D%NLENGT0B*2*NF_FS))
CALL TRMTOL(FOUBUF_IN,FOUBUF,2*NF_FS)
DEALLOCATE(FOUBUF_IN)

END SUBROUTINE LTINV_CONTROL
END MODULE LTINV_CONTROL_MOD
