MODULE LTINV_CTLAD_MOD
CONTAINS
SUBROUTINE LTINV_CTLAD(PSPVOR,PSPDIV,PSPSCALAR,FSPGL_PROC)

#include "tsmbkind.h"

USE TPM_GEN
USE TPM_DIM
USE TPM_TRANS
USE TPM_DISTR

USE LTINVAD_MOD
USE TRLTOM_MOD

IMPLICIT NONE

REAL_B ,OPTIONAL, INTENT(OUT) :: PSPVOR(:,:)
REAL_B ,OPTIONAL, INTENT(OUT) :: PSPDIV(:,:)
REAL_B ,OPTIONAL, INTENT(OUT) :: PSPSCALAR(:,:)
EXTERNAL  FSPGL_PROC
OPTIONAL  FSPGL_PROC

INTEGER_M :: JM,IM,IBLEN

!     ------------------------------------------------------------------

NLEI2 = 8*NF_UV + 2*NF_SCALARS + 2*NF_SCDERS
IBLEN = D%NLENGT0B*2*NF_OUT_LT
IF(LALLOPERM) THEN
  IF(ALLOCATED(FOUBUF_IN)) THEN
    IF(SIZE(FOUBUF_IN) < IBLEN) THEN
      DEALLOCATE(FOUBUF_IN)
    ENDIF
  ENDIF
ENDIF
IF(.NOT.ALLOCATED(FOUBUF_IN)) ALLOCATE(FOUBUF_IN(IBLEN))
CALL GSTATS(180,0)
CALL TRLTOM(FOUBUF,FOUBUF_IN,2*NF_OUT_LT)
CALL GSTATS(180,1)
IF(.NOT. LALLOPERM) THEN
  DEALLOCATE(FOUBUF)
ENDIF

CALL GSTATS(130,0)
!$OMP PARALLEL DO SCHEDULE(STATIC,1) PRIVATE(JM,IM)
DO JM=1,D%NUMP
  IM = D%MYMS(JM)
  CALL LTINVAD(IM,JM,PSPVOR,PSPDIV,PSPSCALAR,FSPGL_PROC)
ENDDO
!$OMP END PARALLEL DO
CALL GSTATS(130,1)

IF(.NOT. LALLOPERM) THEN
  DEALLOCATE(FOUBUF_IN)
ENDIF

!     ------------------------------------------------------------------

END SUBROUTINE LTINV_CTLAD
END MODULE LTINV_CTLAD_MOD
