MODULE SPNORM_CTL_MOD
CONTAINS
SUBROUTINE SPNORM_CTL(PSPEC,KFLD,KFLD_G,KVSET,KMASTER,PMET,PNORM)

#include "tsmbkind.h"

USE TPM_DIM
USE TPM_DISTR

USE SPNORMD_MOD
USE SPNORMC_MOD

IMPLICIT NONE

REAL_B    ,OPTIONAL, INTENT(IN)  :: PSPEC(:,:)
INTEGER_M ,OPTIONAL, INTENT(IN)  :: KVSET(:)
INTEGER_M ,OPTIONAL, INTENT(IN)  :: KMASTER
REAL_B    ,OPTIONAL, INTENT(IN)  :: PMET(:)
REAL_B    ,OPTIONAL, INTENT(OUT) :: PNORM(:)
INTEGER_M          , INTENT(IN)  :: KFLD,KFLD_G
INTEGER_M :: IVSET(KFLD_G)
REAL_B    :: ZMET(0:R%NSMAX)
REAL_B    :: ZSM(KFLD,D%NUMP)
REAL_B    :: ZGM(KFLD_G,0:R%NSMAX) 

!     ------------------------------------------------------------------

IF(PRESENT(KVSET)) THEN
  IVSET(:) = KVSET(:)
ELSE
  IVSET(:) = MYSETV
ENDIF

IF(PRESENT(PMET)) THEN
  ZMET(:) = PMET(:)
ELSE
  ZMET(:) = _ONE_
ENDIF

CALL SPNORMD(PSPEC,KFLD,ZMET,ZSM)

CALL SPNORMC(ZSM,KFLD_G,IVSET,KMASTER,ZGM)

IF(MYPROC == KMASTER) THEN
  PNORM(1:KFLD_G) = SUM(ZGM,DIM=2)
  PNORM(1:KFLD_G) = SQRT(PNORM(1:KFLD_G))
ENDIF
!     ------------------------------------------------------------------

END SUBROUTINE SPNORM_CTL
END MODULE SPNORM_CTL_MOD
