MODULE SUFFT_MOD
CONTAINS
SUBROUTINE SUFFT

USE PARKIND1  ,ONLY : JPIM     ,JPRB

USE TPM_DIM         ,ONLY : R
USE TPM_GEN         ,ONLY : NOUT, NPRINTLEV
USE TPM_DISTR       ,ONLY : D, MYSETW
USE TPM_GEOMETRY    ,ONLY : G
USE TPM_FFT         ,ONLY : T
#ifdef WITH_FFTW
USE TPM_FFTW        ,ONLY : TW, INIT_PLANS_FFTW
#endif
!

IMPLICIT NONE

INTEGER(KIND=JPIM) :: JGL,IGLG
LOGICAL :: LLP1,LLP2

!     ------------------------------------------------------------------

IF(.NOT.D%LGRIDONLY) THEN

  LLP1 = NPRINTLEV>0
  LLP2 = NPRINTLEV>1
  IF(LLP1) WRITE(NOUT,*) '=== ENTER ROUTINE SUFFT ==='

  IF(T%LFFT992)THEN
    ALLOCATE(T%TRIGS(R%NDLON,D%NDGL_FS))
    IF(LLP2)WRITE(NOUT,9) 'T%TRIGS    ',SIZE(T%TRIGS),SHAPE(T%TRIGS)
    ALLOCATE(T%NFAX(19,D%NDGL_FS))
    IF(LLP2)WRITE(NOUT,9) 'T%NFAX     ',SIZE(T%NFAX),SHAPE(T%NFAX)
  
    DO JGL=1,D%NDGL_FS
      IGLG = D%NPTRLS(MYSETW)+JGL-1
      CALL SET99(T%TRIGS(1,JGL),T%NFAX(1,JGL),G%NLOEN(IGLG))
    ENDDO
! ELSE
!   NULLIFY(T%TRIGS)
!   NULLIFY(T%NFAX)
  ENDIF
 
#ifdef WITH_FFTW
  IF(TW%LFFTW)THEN
    CALL INIT_PLANS_FFTW(R%NDLON)
  ELSE
    NULLIFY(TW%FFTW_PLANS)
!   NULLIFY(TW%N_PLANS)
  ENDIF
#endif

ENDIF

!     ------------------------------------------------------------------

9 FORMAT(1X,'ARRAY ',A10,' ALLOCATED ',8I8)

END SUBROUTINE SUFFT
END MODULE SUFFT_MOD
