MODULE SUMP_TRANS0_MOD
CONTAINS
SUBROUTINE SUMP_TRANS0

! Set up distributed environment for the transform package (part 0)

#include "tsmbkind.h"
USE MPL_MODULE

USE TPM_GEN
USE TPM_DISTR

USE PE2SET_MOD

LOGICAL :: LLP1,LLP2
INTEGER_M :: IPROC

!     ------------------------------------------------------------------

LLP1 = NPRINTLEV>0
LLP2 = NPRINTLEV>1
IF(LLP1) WRITE(NOUT,*) '=== ENTER ROUTINE SUMP_TRANS0 ==='


NPROC = NPRGPNS*NPRGPEW
NPRTRNS = NPRTRW
IF(MOD(NPROC,NPRTRW) /= 0 .OR. NPRTRW > NPROC) THEN
  CALL ABOR1('SUMP_TRANS0: NPROC INCONSISTENT WITH NPRTRW')
ENDIF
NPRTRV = NPROC/NPRTRW  
IF(LLP1) WRITE(NOUT,*)'NPROC =',NPROC,' NPRGPNS=',NPRGPNS,' NPRGPEW=',&
 & NPRGPEW,' NPRTRW=',NPRTRW,' NPRTRV=',NPRTRV

IF(NPROC > 1 ) THEN
  IPROC = MPL_NPROC()
  IF(IPROC /= NPROC) THEN
    WRITE(NOUT,*) 'SUMP_TRANS0: NPROC=',NPROC,' BUT MPL_NPROC RETURNS',&
                   IPROC
    CALL ABOR1('SUMP_TRANS0: NPROC INCONSISTENT WITH MPL_NPROC')
  ENDIF
  MYPROC = MPL_MYRANK()
ELSE
  MYPROC = 1
ENDIF

IF (MYPROC > NPROC) THEN
  CALL ABOR1('SUMP_TRANS0: INCONSISTENCY IN NUMBER OF PROCESSORS USED')
ENDIF
CALL PE2SET(MYPROC,MYSETNS,MYSETEW,MYSETW,MYSETV)
IF(LLP1) WRITE(NOUT,*)'MYPROC=',MYPROC,' MYSETNS=',MYSETNS,&
 & ' MYSETEW=',MYSETEW,' MYSETW=',MYSETW,' MYSETV=',MYSETV  

ALLOCATE(NPRCIDS(NPROC))
IF(LLP2)WRITE(NOUT,9) 'NPRCIDS   ',SIZE(NPRCIDS   ),SHAPE(NPRCIDS   )
DO JJ=1,NPROC
  NPRCIDS(JJ) = JJ
ENDDO

! Message passing tags

MTAGLETR = 18000
MTAGML   = 19000
MTAGLG   = 20000
MTAGPART = 21000
MTAGDISTSP = 22000
MTAGGL   = 23000
MTAGLM   = 24000
MTAGDISTGP = 25000

! Setup labels for timing package (gstats)

CALL GSTATS_LABEL(102,'LTINV_CTL    - INVERSE LEGENDRE TRANSFORM')
CALL GSTATS_LABEL(103,'LTDIR_CTL    - DIRECT LEGENDRE TRANSFORM')
CALL GSTATS_LABEL(106,'FTDIR_CTL    - DIRECT FOURIER TRANSFORM')
CALL GSTATS_LABEL(107,'FTINV_CTL    - INVERSE FOURIER TRANSFORM')
CALL GSTATS_LABEL(130,'LTINV_CTLAD  - ADJ. INVERSE LEGENDRE TRANSFORM')
CALL GSTATS_LABEL(131,'LTDIR_CTLAD  - ADJ. DIRECT LEGENDRE TRANSFORM')
CALL GSTATS_LABEL(132,'FTINV_CTLAD  - ADJ. INVERSE FOURIER TRANSFORM')
CALL GSTATS_LABEL(133,'FTDIR_CTLAD  - ADJ. DIRECT FOURIER TRANSFORM')

CALL GSTATS_LABEL(152,'LTINV_CTL    - M TO L TRANSPOSITION')
CALL GSTATS_LABEL(153,'LTDIR_CTL    - L TO M TRANSPOSITION')
CALL GSTATS_LABEL(157,'FTINV_CTL    - L TO G TRANSPOSITION')
CALL GSTATS_LABEL(158,'FTDIR_CTL    - G TO L TRANSPOSITION')
CALL GSTATS_LABEL(180,'LTINV_CTLAD  - L TO M TRANSPOSITION')
CALL GSTATS_LABEL(181,'LTDIR_CTLAD  - M TO L TRANSPOSITION')
CALL GSTATS_LABEL(182,'FTINV_CTLAD  - G TO L TRANSPOSITION')
CALL GSTATS_LABEL(183,'FTDIR_CTLAD  - L TO G TRANSPOSITION')

!     ------------------------------------------------------------------
9 FORMAT(1X,'ARRAY ',A10,' ALLOCATED ',8I8)
 
END SUBROUTINE SUMP_TRANS0
END MODULE SUMP_TRANS0_MOD
