MODULE TPM_TRANS

! Module to contain variables "local" to a specific call to a transform

#include "tsmbkind.h"

IMPLICIT NONE

SAVE

INTEGER_M :: NF_UV
INTEGER_M :: NF_SCALARS
INTEGER_M :: NF_SCDERS
INTEGER_M :: NF_OUT_LT

LOGICAL   :: LUV
LOGICAL   :: LSCALAR
LOGICAL   :: LVORGP
LOGICAL   :: LDIVGP
LOGICAL   :: LUVDER

INTEGER_M :: NLEI2
INTEGER_M :: NLED2

INTEGER_M :: NF_FS

INTEGER_M :: NF_GP
INTEGER_M :: NF_UV_G
INTEGER_M :: NF_SCALARS_G

REAL_B, ALLOCATABLE :: FOUBUF_IN(:)
REAL_B, ALLOCATABLE :: FOUBUF(:)

INTEGER_M :: NPROMA
INTEGER_M :: NGPBLKS

END MODULE TPM_TRANS
