MODULE TPM_GEOMETRY
#include "tsmbkind.h"

IMPLICIT NONE

SAVE

TYPE GEOM_TYPE
INTEGER_M,POINTER :: NLOEN(:) ! NUMBER OF POINTS ON A PARALLEL
INTEGER_M,POINTER :: NMEN(:)  ! ASSOCIATED CUT-OFF WAVE NUMBER
INTEGER_M,POINTER :: NDGLU(:) ! NUMBER OF HEMISPERIC LATITUDES
!                                   FOR A GIVEN WAVE NUMBER M 

LOGICAL :: LREDUCED_GRID
LOGICAL :: LINEAR_GRID
END TYPE GEOM_TYPE

TYPE(GEOM_TYPE),ALLOCATABLE,TARGET :: GEOM_RESOL(:)
TYPE(GEOM_TYPE),POINTER     :: G

END MODULE TPM_GEOMETRY
