MODULE TPM_FFT
#include "tsmbkind.h"

IMPLICIT NONE

SAVE

TYPE FFT_TYPE
  REAL_B   ,POINTER :: TRIGS(:,:)
  INTEGER_M,POINTER :: NFAX(:,:)
END TYPE FFT_TYPE

TYPE(FFT_TYPE),ALLOCATABLE,TARGET :: FFT_RESOL(:)
TYPE(FFT_TYPE),POINTER     :: T

END MODULE TPM_FFT
