MODULE TPM_CONSTANTS
USE PARKIND1  ,ONLY : JPIM     ,JPRB

IMPLICIT NONE

SAVE

REAL(KIND=JPRB),PARAMETER :: RPLRADI = 1._JPRB ! Small planet factor

REAL(KIND=JPRB) :: RA=6371229._JPRB*RPLRADI   ! Radius of Earth

END MODULE TPM_CONSTANTS
