MODULE TPM_POL

USE PARKIND1  ,ONLY : JPIM     ,JPRB

IMPLICIT NONE

SAVE

REAL(KIND=JPRB),ALLOCATABLE :: DDC(:,:), DDD(:,:), DDE(:,:)
REAL(KIND=JPRB),ALLOCATABLE :: DDA(:), DDI(:), DDH(:)

REAL(KIND=JPRB),ALLOCATABLE :: DFA(:), DFB(:), DFF(:), DFG(:), DFI(:), DFH(:)

CONTAINS
!======================================================================
SUBROUTINE INI_POL(KNSMAX)

INTEGER(KIND=JPIM), INTENT(IN) :: KNSMAX

REAL(KIND=JPRB) :: DA,DC,DD,DE
INTEGER(KIND=JPIM) :: KKN, KKM

INTEGER(KIND=JPIM) :: JN, JM

DC(KKN,KKM)=SQRT( (REAL(2*KKN+1,JPRB)*REAL(KKN+KKM-1,JPRB)&
                   &*REAL(KKN+KKM-3,JPRB))&
                &/ (REAL(2*KKN-3,JPRB)*REAL(KKN+KKM,JPRB)&
                   &*REAL(KKN+KKM-2,JPRB)) )
DD(KKN,KKM)=SQRT( (REAL(2*KKN+1,JPRB)*REAL(KKN+KKM-1,JPRB)&
                   &*REAL(KKN-KKM+1,JPRB))&
                &/ (REAL(2*KKN-1,JPRB)*REAL(KKN+KKM,JPRB)&
                  &*REAL(KKN+KKM-2,JPRB)) )
DE(KKN,KKM)=SQRT( (REAL(2*KKN+1,JPRB)*REAL(KKN-KKM,JPRB))&
                &/ (REAL(2*KKN-1,JPRB)*REAL(KKN+KKM,JPRB)) )
DA(KKN,KKM)=SQRT( (REAL(2*KKN+1,JPRB)*REAL(KKN-KKM,JPRB)&
                   &*REAL(KKN+KKM,JPRB))&
                &/  REAL(2*KKN-1,JPRB) )

ALLOCATE( DDC(0:KNSMAX,0:KNSMAX) )
ALLOCATE( DDD(0:KNSMAX,0:KNSMAX) )
ALLOCATE( DDE(0:KNSMAX,0:KNSMAX) )

ALLOCATE( DDA(0:KNSMAX) )
ALLOCATE( DDI(0:KNSMAX) )
ALLOCATE( DDH(0:KNSMAX) )

ALLOCATE( DFA(0:KNSMAX) )
ALLOCATE( DFB(0:KNSMAX) )
ALLOCATE( DFF(0:KNSMAX) )
ALLOCATE( DFG(0:KNSMAX) )
ALLOCATE( DFI(0:KNSMAX) )
ALLOCATE( DFH(0:KNSMAX) )


DO JN=1,KNSMAX
  DFA(JN) = 1._JPRB/SQRT(REAL(JN*(JN+1),JPRB))
  DFB(JN) = SQRT(REAL(2*JN+1,JPRB)/REAL(JN*(JN+1),JPRB))
  DFF(JN) = REAL(2*JN-1,JPRB)/REAL(JN,JPRB)
  DFG(JN) = REAL(JN-1,JPRB)/REAL(JN,JPRB)
  DFI(JN) = REAL(JN,JPRB)
  DFH(JN) = SQRT(REAL(2*JN+1,JPRB)/REAL(2*JN,JPRB))
ENDDO

DO JN=3,KNSMAX
  DO JM=2,JN-1
    DDC(JM,JN) = DC(JN,JM)
    DDD(JM,JN) = DD(JN,JM)
    DDE(JM,JN) = DE(JN,JM)
  ENDDO
ENDDO

DO JN=1,KNSMAX
  DDA(JN) = 1._JPRB/SQRT(REAL(JN*(JN+1),JPRB))
  DDI(JN) = REAL(JN,JPRB)
  DDH(JN) = SQRT(REAL(2*JN+1,JPRB)/REAL(2*JN,JPRB))
ENDDO

END SUBROUTINE INI_POL

SUBROUTINE END_POL

DEALLOCATE( DDC )
DEALLOCATE( DDD )
DEALLOCATE( DDE )

DEALLOCATE( DDA )
DEALLOCATE( DDI )
DEALLOCATE( DDH )

DEALLOCATE( DFA )
DEALLOCATE( DFB )
DEALLOCATE( DFF )
DEALLOCATE( DFG )
DEALLOCATE( DFI )
DEALLOCATE( DFH )

END SUBROUTINE END_POL

END MODULE TPM_POL
