MODULE TPM_FIELDS

#include "tsmbkind.h"

IMPLICIT NONE

SAVE

TYPE FIELDS_TYPE
REAL_B ,POINTER :: RPNM(:,:)
REAL_B ,POINTER :: RMU(:)
REAL_B ,POINTER :: RW(:)
REAL_B ,POINTER :: R1MU2(:)
REAL_B ,POINTER :: RACTHE(:)

REAL_B ,POINTER :: REPSNM(:)
REAL_B ,POINTER :: RN(:)
REAL_B ,POINTER :: RLAPIN(:)
INTEGER_M ,POINTER :: NLTN(:)
END TYPE FIELDS_TYPE

TYPE(FIELDS_TYPE),ALLOCATABLE,TARGET :: FIELDS_RESOL(:)
TYPE(FIELDS_TYPE),POINTER     :: F

END MODULE TPM_FIELDS
