MODULE TPM_FLT

USE PARKIND1  ,ONLY : JPIM     ,JPRB
USE BUTTERFLY_ALG_MOD,ONLY : BUTTERFLY_STRUCT
IMPLICIT NONE

SAVE


TYPE FLT_TYPE
INTEGER(KIND=JPIM) :: NSPOLEGL
INTEGER(KIND=JPIM) :: NDGNH
INTEGER(KIND=JPIM) :: INS2
INTEGER(KIND=JPIM) :: INA2
REAL(KIND=JPRB) ,POINTER :: RPNMS(:,:) ! Legendre polynomials
REAL(KIND=JPRB) ,POINTER :: RPNMA(:,:) ! Legendre polynomials
REAL(KIND=JPRB) :: RCS
REAL(KIND=JPRB) :: RCA

! Butterfly

INTEGER(KIND=JPIM) :: MAXCOLS
TYPE(BUTTERFLY_STRUCT) :: YBUT_STRUCT_S,YBUT_STRUCT_A

END TYPE FLT_TYPE

TYPE FLT_TYPE_WRAP
TYPE(FLT_TYPE),POINTER :: FA(:)
LOGICAL :: LUSEFLT
LOGICAL :: LUSERPNM
LOGICAL :: LKEEPRPNM
INTEGER(KIND=JPIM) :: IMLOC
INTEGER(KIND=JPIM) :: ITHRESHOLD
LOGICAL :: LSYM

END TYPE FLT_TYPE_WRAP

TYPE(FLT_TYPE_WRAP),ALLOCATABLE,TARGET :: FLT_RESOL(:)
TYPE(FLT_TYPE_WRAP),POINTER     :: S


END MODULE TPM_FLT







