MODULE TPM_FFT
USE PARKIND1  ,ONLY : JPIM     ,JPRB

IMPLICIT NONE

SAVE

TYPE FFT_TYPE
  REAL(KIND=JPRB)   ,POINTER :: TRIGS(:,:)
  INTEGER(KIND=JPIM),POINTER :: NFAX(:,:)
END TYPE FFT_TYPE

TYPE(FFT_TYPE),ALLOCATABLE,TARGET :: FFT_RESOL(:)
TYPE(FFT_TYPE),POINTER     :: T

END MODULE TPM_FFT
