INTERFACE
SUBROUTINE PASS_MYLEVS_TO_TRANS(KMYLEVS)
USE PARKIND1 ,ONLY : JPIM,JPRB
USE ABORT_TRANS_MOD ,ONLY : ABORT_TRANS
INTEGER(KIND=JPIM) , INTENT(IN) :: KMYLEVS(:)
END SUBROUTINE PASS_MYLEVS_TO_TRANS
END INTERFACE
