SUBROUTINE SETUP_TRANS(KSMAX,KDGL,KLOEN,LDSPLIT,KAPSETS)

#include "tsmbkind.h"

IMPLICIT NONE

INTEGER_M ,INTENT(IN) :: KSMAX,KDGL
INTEGER_M ,OPTIONAL,INTENT(IN) :: KLOEN(:)
LOGICAL   ,OPTIONAL,INTENT(IN) :: LDSPLIT
INTEGER_M ,OPTIONAL,INTENT(IN) :: KAPSETS


END SUBROUTINE SETUP_TRANS
