SUBROUTINE TRANS_INQ(KRESOL,KSPEC,KSPEC2,KSPEC2MX,KNUMP,&
                    &KGPTOT,KGPTOTG,KGPTOTMX,&
                    &PMU,PGW)

#include "tsmbkind.h"

IMPLICIT NONE

INTEGER_M ,OPTIONAL, INTENT(IN)  :: KRESOL

INTEGER_M ,OPTIONAL, INTENT(OUT) :: KSPEC
INTEGER_M ,OPTIONAL, INTENT(OUT) :: KSPEC2
INTEGER_M ,OPTIONAL, INTENT(OUT) :: KSPEC2MX
INTEGER_M ,OPTIONAL, INTENT(OUT) :: KNUMP
INTEGER_M ,OPTIONAL, INTENT(OUT) :: KGPTOT
INTEGER_M ,OPTIONAL, INTENT(OUT) :: KGPTOTG
INTEGER_M ,OPTIONAL, INTENT(OUT) :: KGPTOTMX

REAL_B    ,OPTIONAL, INTENT(OUT) :: PMU(:)
REAL_B    ,OPTIONAL, INTENT(OUT) :: PGW(:)

END SUBROUTINE TRANS_INQ
