! (C) Copyright 2026- ECMWF.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.

PROGRAM TEST_BLUESTEIN_ROUNDTRIP

USE PARKIND1      ,ONLY : JPIM, JPRB
USE BLUESTEIN_MOD ,ONLY : BLUESTEIN_FFT, BLUESTEIN_INIT, BLUESTEIN_TERM, FFTB_TYPE

IMPLICIT NONE

INTEGER(KIND=JPIM), PARAMETER :: KLOT = 3
INTEGER(KIND=JPIM), PARAMETER :: NTESTS = 4
INTEGER(KIND=JPIM), PARAMETER :: NSIZES(NTESTS) = (/ 28, 44, 52, 76 /)
REAL(KIND=JPRB), PARAMETER :: TOL_FACTOR = 1.0E5_JPRB

TYPE(FFTB_TYPE) :: TB
REAL(KIND=JPRB), ALLOCATABLE :: ORIG(:,:), WORK(:,:)
REAL(KIND=JPRB) :: MAXERR, TOL
INTEGER(KIND=JPIM) :: JN, N, K, J
LOGICAL :: LOK

TB%NDLON = MAXVAL(NSIZES)
TB%NLAT_COUNT = NTESTS
ALLOCATE(TB%NLATS(NTESTS))
TB%NLATS = NSIZES
CALL BLUESTEIN_INIT(TB)

LOK = .TRUE.
TOL = TOL_FACTOR * EPSILON(1.0_JPRB)

DO JN = 1, NTESTS
  N = NSIZES(JN)
  ALLOCATE(ORIG(KLOT,N+2))
  ALLOCATE(WORK(KLOT,N+2))

  DO J = 1, KLOT
    DO K = 1, N
      ORIG(J,K) = SIN(REAL((J+1)*K,JPRB) * 0.17_JPRB) + COS(REAL(J*(K+2),JPRB) * 0.11_JPRB)
    ENDDO
  ENDDO
  ORIG(:,N+1:N+2) = 0._JPRB

  WORK = ORIG
  CALL BLUESTEIN_FFT(TB,N,-1,KLOT,WORK)
  WORK(:,1:N+2) = WORK(:,1:N+2) / REAL(N,JPRB)
  CALL BLUESTEIN_FFT(TB,N,1,KLOT,WORK)

  MAXERR = MAXVAL(ABS(WORK(:,1:N) - ORIG(:,1:N)))
  WRITE(*,'("N=",I4," maxerr=",ES12.4)') N, MAXERR
  IF (MAXERR > TOL) LOK = .FALSE.

  DEALLOCATE(WORK)
  DEALLOCATE(ORIG)
ENDDO

CALL BLUESTEIN_TERM(TB)

IF (.NOT. LOK) THEN
  ERROR STOP 'Bluestein round-trip failed'
ENDIF

END PROGRAM TEST_BLUESTEIN_ROUNDTRIP
