MODULE TPMALD_FFT

! Module for Fourier transforms.

USE PARKIND1  ,ONLY : JPIM     ,JPRB

IMPLICIT NONE

SAVE

TYPE ALDFFT_TYPE
REAL(KIND=JPRB)   ,POINTER :: TRIGSE(:) ! list of trigonometric function values
INTEGER(KIND=JPIM),POINTER :: NFAXE(:)  ! list of factors of truncation
LOGICAL                    :: LFFT992=.FALSE.
END TYPE ALDFFT_TYPE

TYPE(ALDFFT_TYPE),ALLOCATABLE,TARGET :: ALDFFT_RESOL(:)
TYPE(ALDFFT_TYPE),POINTER     :: TALD

END MODULE TPMALD_FFT
