MODULE TPMALD_FIELDS

USE PARKIND1  ,ONLY : JPIM     ,JPRB

IMPLICIT NONE

SAVE

TYPE ALDFIELDS_TYPE

REAL(KIND=JPRB) ,POINTER :: RLEPINM(:) ! eigen-values of the inverse Laplace operator
END TYPE ALDFIELDS_TYPE

TYPE(ALDFIELDS_TYPE),ALLOCATABLE,TARGET :: ALDFIELDS_RESOL(:)
TYPE(ALDFIELDS_TYPE),POINTER     :: FALD

END MODULE TPMALD_FIELDS
